[allowlist]
  description = "Global Allowlist"

  # Ignore based on any subset of the file path
  paths = [
    # Ignore all example certs
    '''endpoints\/citrus-ssh\/src\/main\/resources\/org\/citrusframework\/ssh\/.*\.pem$''',
  ]
