[[changes-new]]
= What's new in Citrus 2.9.x?

[[changes-2-9-0]]
== Since Citrus 2.9.0
Beside all bug fixes included in 2.7.10, version 2.9.0 of Citrus contains a lot of new features for the jdbc integration
as well as deprecations concerning the XML DSL and the Java TestDesigner and improvements to the logging functionality
and documentation.

[[changes-2-9-0-jdbc]]
== New features of the JDBC integration

=== Execute Batch statements
https://github.com/citrusframework/citrus/issues/490[#490 - not supported jdbc statement function 'executeBatch']

We added the possibility to execute jdbc batch statements with the driver and validate them in a test case. For more
information, please have a look at the section concerning link:#jdbc-server-execute-batch[JDBC batch statements].

=== Support for BLOB and CLOB
https://github.com/citrusframework/citrus-db/issues/28

From this release on, it is possible to use BLOB und CLOB data in your requests and responses and even for validation.
By now, there are some restrictions to keep in mind while using this feature. More information concerning those can
be found in the section link:#jdbc-server-clob[CLOB support] and link:#jdbc-server-blob[BLOB support].