[[changes-2-7]]
== Changes in Citrus 2.7

Citrus 2.7 is using Java 8! The Citrus sources are compiled with Java 8 which means that from now on you need at least
Java 8 runtime to work with Citrus. With this Java 8 base Citrus
is proud to welcome two new crew members for supporting Selenium and Kubernetes in tests. Not enough we have the following
features included in the box.

[[changes-java-8]]
=== Java 8

Citrus is now using Java 8. This is mainly because we need to move on in using latest versions of Spring Framework,
Apache Camel and so on. If you are still stuck on Java 7 you can not update to 2.7 as the Citrus sources are compiled with
Java 8. Please contact us in case you really can not update to Java 8 in your project. We can think of a minor bugfix version
with Citrus 2.6 base that still supports Java 7 runtime. On the bright side we can now use the full power of Lambda expressions
and other Java 8 features in Citrus code base.

[[changes-kubernetes]]
=== Kubernetes support

Citrus is now able to interact with http://kubernetes.io/[Kubernetes] remote API in order to manage pods, services and other
resources on the Kubernetes platform. The Kubernetes client is based on the https://github.com/fabric8io/kubernetes-client[Fabric8 Java client]
that interacts with the Kubernetes API via REST services. So you can access Kubernetes resources within Citrus in order to
change or validate the resource state for containerized testing.
This is very useful when dealing with container application environments as part of the integration tests. Please stay tuned
for blog posts and tutorial samples on how Citrus can help you test Microservices with Docker and Kubernetes. The basic usage is
described in section link:#kubernetes[kubernetes].

[[changes-selenium]]
=== Selenium support

User interface and browser testing has not been a focus within Citrus integration testing until now that we can integrate
with the famous http://www.seleniumhq.org/[Selenium] UI testing library. Thanks to the great contributions made by the
community - especially by https://github.com/vdsrd[vdsrd@github] - we can use Selenium based actions and features directly
in a Citrus test case. The Citrus Java and XML DSL both provide comfortable access to the Selenium API in order to
simulate user interaction within a browser. The mix of user based actions and Citrus messaging transport simulation gives
complete new ways of handling complex integration scenarios. Read more about this in chapter link:#selenium[Selenium].

[[changes-before-after-suite]]
=== Environment based before/after suite

You can enable/disable before and after suite actions based on optional environment or system properties. Users can give
property names or property values that are checked before execution.
Only in case the environment property checks do pass the actions are executed before/after the test suite run.

[[wsaddressing-header-customization]]
=== WsAddressing header customization

We have improved the header customization options when using SOAP WSAddressing feature. You can now overwrite the default
WSAddressing headers per test action in addition to defining the headers on
client endpoint component level.

[[changes-jsonpath-data-dictionary]]
=== JsonPath data dictionary

Json data dictionary was based on a simple dot notated syntax. Now you can also use more complex JsonPath expressions in
order to overwrite elements in Json messages based on the data dictionary settings in Citrus. Read more about that in chapter
link:#data-dictionaries[data-dictionary].

[[changes-java-dsl-test-behavior]]
=== Java DSL test behavior

Test behaviors in Java DSL represent templates in XML DSL. The behavior encapsulates a set of test actions to a group that
can be applied to multiple Java DSL tests. This enables you to combine common test actions in Java DSL with more comfortable
reuse of test action definitions. See chapter link:#test-behavior[test-behavior] how to use that.

[[changes-auto-select-message-type]]
=== Auto select message type

Default message type for validation tasks in Citrus has been _XML_. Based on this message type the respective message validator
implementation applies for _XML_, _JSON_, _plain text_ and so on. You can now change this default message type by setting a
system property (`citrus.default.message.type`). Also Citrus improved the auto select algorithm when the default message type
is obviously not applicable. When a message arrives in Citrus the receiving action tries to find out which message validator
fits best according to the message payload. XML message content is automatically identified by `&lt;&gt;` characters. JSON message
payloads are identified by `{}` or `[]` characters for objects and array representations. This way Citrus tries to find the best
matching message validator for the incoming message. Before that Citrus has always been using the default message type _XML_.

Read about different message validators in link:#message-validation[message-validation].

[[changes-default-cucumber-steps]]
=== Default Cucumber steps

The Citrus Cucumber extension now defines default step definitions for Http, Docker and Selenium. These default steps are ready
for usage in any Cucumber Citrus feature specification. You can load the default steps as additional glue packages in your
Cucumber options. After that you are ready to go for using the default steps directly in feature specification files. With the
extensions you can perform Docker and Selenium commands very easy. Also you can describe the Http REST client-server communication
in BDD style. Read more about this in link:#cucumber[cucumber].

[[changes-db-transactions]]
=== Database transaction handling

When Citrus accesses data storage in form of SQL statements executed on some datasource the transaction handling has not been set in the past. Each SQL
statement has been committed immediately. Especially when executing multiple SQL statement via script this could lead to inconsistencies. With the new release you
can make use of Spring's transaction handling when executing SQL statements with Citrus. You can set a transaction handler with isolation levels and default transaction timeout settings.
This enables you to use transaction blocks for multiple statements with one single commit or rollback. Read more about this in chapter link:#sql-transaction-management[actions accessing the database].

[[changes-environment-settings]]
=== Environment settings

We added a mechanism to overwrite general settings in Citrus via system properties and environment variables. This makes Citrus ready for runtime environments such as Docker and Kubernetes where
you can use environment variables to change Citrus behavior. The available settings and variable names can be seen in chapter link:#configuration[configuration].

[[changes-http-cookies]]
=== Http cookie support

Setting Http cookie related Http headers has been possible in previous versions. We improved that cookie handling in Http request and response messages with a dedicated DSL for adding and verifying cookie information
in Http headers. The Citrus http-server is able to advice the client to set a new cookie with respective *Set-Cookie* headers in response messages. The http-client is able to verify the cookie attributes such as name, value, max-age and so on.
In addition to that the client is able to send the cookie name value pair in further requests as a reference via "*Cookie*" message headers. The complete new cookie handling is described in section link:#http-cookies[Http cookie handling].

[[changes-file-encoding]]
=== File resource encoding

The Citrus test case is able to load file resources in various situations e.g. when defining expected message contents. The file resource encoding and charset used a system-wide default setting which has been settable via system property (*citrus.file.encoding*).
In addition to that we have added the opportunity to overwrite this system-wide setting in each resource read operation. This means that everywhere where it is possible to load a file resource you can explicitly set a file encoding and charset for this read operation.
This enables you to use more than one system-wide file encoding setting when reading data from external file resources in Citrus.