[[changes-2-7-10]]
== Changes in Citrus 2.7.10

=== Fixed HTTP request parameter regression
Due to a regression introduced during a refactoring of the HTTP request parameter management, it was not possible
anymore to add two different values to a single key. To fix this regression, it was required to change the return type
of the public method `getQueryParams` of the type `HttpMessage` from `Map<String, String>` to
`Map<String, Collection<String>>`. If you used this method in your test suite, which should most likely not be the case,
please consider this change during a version update of Citrus.

For further details, please have a look into the concerning issue on Github :
https://github.com/citrusframework/citrus/issues/583[#583 - Param list support with same param name not available]

[[changes-maintenance-2-7-10]]
== Maintenance tasks
* https://github.com/citrusframework/citrus/issues/461[#461 - Rename argument for RepeatOnErrorBuilder#autoSleep to clarify expected unit]

[[changes-bugs-2-7-10]]
=== Fixed bugs
* https://github.com/citrusframework/citrus/issues/545[#545 - Missing HttpServer auto gzip decompression in request handling]
* https://github.com/citrusframework/citrus/issues/588[#588 - BooleanExpressionParser parses expression groups containing boolean strings inconsistently]

[[changes-security-2-7-10]]
=== Security fixes
* https://github.com/citrusframework/citrus/issues/612[#612 - Update org.springframework.ws.spring-xml to 3.0.6 or later]
* https://github.com/citrusframework/citrus/issues/639[#639 - Update jetty-server to 9.4.12.v20180830 or later]
* https://github.com/citrusframework/citrus/issues/642[#642 - Update jetty-server to 9.4.17.v20190418 or later]
* https://github.com/citrusframework/citrus/issues/649[#649 - Update camel-core to version 2.21.5 or later]

[[changes-2-7-9]]
== Changes in Citrus 2.7.9

[[changes-bugs-2-7-9]]
=== Fixed bugs

* https://github.com/citrusframework/citrus/issues/561[#561 - Lost cookie entries except the last one]
* https://github.com/citrusframework/citrus/issues/535[#535 - Inconsistent values of global variables]
* https://github.com/citrusframework/citrus/issues/569[#569 - duplicated cookie entries in http request]
* https://github.com/citrusframework/citrus/issues/455[#455 - Cookies are not recognized by HTTP client]
* https://github.com/citrusframework/citrus/issues/562[#562 - maven plugin creates invalid testNG Citrus tests]

[[fixed-breaking-changes-2-7-9]]
=== Fixed breaking changes

We've received reports from Citrus users pointing out several breaking changes in the public API that have been introduced
with minor versions. Because of that, we've reviewed the public API from release 2.7 until today and reconstructed the
the removed/changed methods to ease the migration to newer Citrus versions. All methods that have been added back for
downwards compatibility are marked as `@Deprecated` and will be removed with the next major release.

* https://github.com/citrusframework/citrus/issues/552[#552 - Breaking change in MessageContentBuilder.buildMessageContent() public API]
* https://github.com/citrusframework/citrus/issues/547[#547 - Breaking change in waitFor().http() public API]
* https://github.com/citrusframework/citrus/issues/557[#557 - Breaking change in waitFor().file(String) public API]
* https://github.com/citrusframework/citrus/issues/558[#558 - Breaking change in waitFor().file(File) public API]
* https://github.com/citrusframework/citrus/issues/551[#551 - Breaking change in selenium().browser().type() public API]
* https://github.com/citrusframework/citrus/issues/556[#556 - Breaking change in waitFor().message() public API]
* https://github.com/citrusframework/citrus/issues/553[#553 - Scp client builder does not offer autoReadFiles anymore]

[[changes-security-2-7-9]]
=== Security fixes
* https://github.com/citrusframework/citrus/issues/584[#584 - Update com.fasterxml.jackson.core:jackson-databind to version 2.9.8 or later]

[[changes-enhancements-2-7-9]]
=== Enhancements
* https://github.com/citrusframework/citrus/issues/591[#591 - Improve documentation concerning parallel messages]

[[changes-2-7-8]]
== Changes in Citrus 2.7.8

[[changes-sftp]]
=== STFP preferred authentication settings
https://github.com/citrusframework/citrus/issues/483[#483 - Add SFTP client preferred authentications setting]

We've change the default authentication order for the SFTP client, so that it prevents early keyboard interaction. To be
able to change the order of authentication methods depending on the current use case, we've introduced configuration
options for this.

For more information, please have a look at the link:#sftp-client[SFTP Client] section.


[[changes-maintenance]]
=== Maintenance tasks

* https://github.com/citrusframework/citrus/issues/520[#520 - update vertx-core because of vulnerabilities]
* https://github.com/citrusframework/citrus/issues/509[#509 - Inconsistencies in Java doc for RepeatOnError]

[[changes-bugs-2-7-8]]
=== Fixed bugs

* https://github.com/citrusframework/citrus/issues/451[#451 - Citrus-Maven-Plugin: 'Generate Docs'-Mojo fails due to broken path]
* https://github.com/citrusframework/citrus/issues/418[#418 - Thread leak in TestCase.finish()]
* https://github.com/citrusframework/citrus/issues/428[#428 - Citrus reports containing invalid XML]
* https://github.com/citrusframework/citrus/issues/505[#505 - Maven Goal 'citrus:create-test' generate test class with compile error]
* https://github.com/citrusframework/citrus/issues/516[#516 - Exception in async container is suppressed when used with TestNGCitrusTestRunner]
* https://github.com/citrusframework/citrus/issues/524[#524 - Initial local build failing in citrus-arquillian]

[[changes-2-7-7]]
== Changes in Citrus 2.7.7

[[changes-SshServer]]
=== Read SshServer key from classpath

It's now possible to load the host key from the classpath.

[[changes-bugs]]
=== Bugfix, bugfix, bugfix

See the complete list of https://github.com/citrusframework/citrus/milestone/12?closed=1[v2.7.7 bugfixes].

[[changes-2-7-6]]
== Changes in Citrus 2.7.6

[[changes-hamcrest-number-matchers]]
=== Hamcrest matchers

We have added new Hamcrest matcher support in XML. This is `isOneOf` and `isIn` as well as `closeTo`. All implementations are now available in XML when using `@assertThat()@` validation expressions.
Read more about it in section link:#matcher-assert-that[matcher-assert-that].

[[changes-wait-for-action]]
=== Wait for test action

The wait action is able to wait for a condition to pass during a test case. Up to now you were able to wait for Http URL to return a status code, a file to be present and a message to arrive. A new
condition implementation enables you to wait for another test action to perform successfully. In case of error or time delay in the test action the condition will wait until the action is finished. This
enables you to wait for Docker images to start, JMS messages to arrive and many more.

Read more about it in sections link:#containers-wait[wait-for] and link:#containers-wait-action[wait-for-action].

[[changes-sftp-scp]]
=== SFTP/SCP support

The FTP endpoints (client/server) in Citrus were enhanced to also handle SFTP and SCP secure file transfer. The new support results in new client and server components for SFTP and SCP so you can
choose how the files should be sent/received to/from the server.

Read more about it in sections link:#ftp[FTP] and link:#sftp[SFTP/SCP].

[[changes-jms-durable-scubscribers]]
=== JMS Topic durable subscribers

The Citrus JMS topic client is now able to use durable subscriptions and/or to start and reuse the subscription throughout the whole test suite. The topic subscription is then started at the very beginning
and incoming events are stored to a local in memory cache. This mechanism is used to not loose any events that are triggered before the test case is receiving the messages from that JMS topic.

Read more about it in section link:#jms-topic-subscriber[JMS topics] and link:#jms-topic-durable-subscription[JMS durable subscriber].

[[changes-http-query-params]]
=== Improved Http query param handling

Http clients and servers are able to add query parameter to a GET Http URL. The handling of those parameters has significantly changed in this release in order to simplify query parameter support in Citrus. You can now
validate a sub set of query parameters and you are now able to use validation matchers and `@ignore@` expressions when validating query parameters on the server.

Read more about it in section link:#http[Http support].

[[changes-validation-matcher-new-line]]
=== Validation matchers

We have added some new validation matcher implementations `ignoreNewLine`, `trim` and `trimAllWhitespace`.

Read more about it in section link:#matcher-ignore-new-line[ignore-new-line], link:#matcher-trim[trim] and link:#matcher-trim-all-whitespace[trim-all-whitespace].

[[changes-2-7-5]]
== Changes in Citrus 2.7.5

[[changes-message-selector]]
=== Message selector on non-XML payloads

Citrus has always been able to select messages on a queue or channel in a receive test action in order to pick a message
of matching headers and or payload contents from a list of inbound messages. This enabled us to perform parallel testing and in addition to that
we are able to realize test scenarios where multiple messages arrive unordered at the same time.

The message selector processing has been enhnaced with JsonPath support as well as validation matcher conditions. So you can filter messages of certain
nature based on non XML payloads, too.

Read more about message selectors in link:#message-selectors[message-selector] and link:#message-channel-selector[message-channel-selector].

[[changes-zip-archives]]
=== Send and receive zip archives

Citrus provides a special message implementation that automatically adds the payload in form of one to many files and directories to a zip archive. The final zipped content is then
provided as binary message payload. This makes it very easy to send and receive zipped files and directories within Citrus.

[[changes-ftp-rewrite]]
=== Support FTP store and retrieve file operations

The FTP support has been rewritten to a certain extend in this release. This is because the former implementation has been too close to the FTP protocol. The new implementation is much
more comfortable when it comes to store and retrieve files on a FTP server. Also you can now check on a server side that files are pushed or retrieved via client interaction.

This new FTP API is backward compatible to former tests but you should definitely have a look at the new capabilities in FTP support. Check out the new stuff in chapter link:#ftp[ftp].

[[changes-binary-message]]
=== Binary messages

Handling of binary message content has been possible in Citrus. We have had some issues though when using non standard binary Content-Type headers in Http communication. The binary content was then treated
as String content obviously corrupting the binary content while processing. Also the Http client has not been able to retrieve binary message content from the server in order to validate the binary
streams. All issues are fixed with this release and in combination with extended binary message content utilities we expand the framework to handle binary content on client and server side.

To mention only one of these enhancements we now have a binary message stream validator that is able to compare two input streams of binary content. See chapter link:#binary-message-validation[binary-message-validation] for details.

[[changes-2-7-4]]
== Changes in Citrus 2.7.4

[[changes-swagger]]
=== Test generation from swagger definitions

It's now possible to generate a basic Test setup from swagger.json files using the Citrus Maven plugin.

[[changes-jdbc]]
=== JDBC server

Preparing databases for testing can be hard times. Creating all tables and preparing the test data with all constraints and data integrity is often a full time job and
very exhausting. Instead of preparing a real database would'nt it be nice to just mock the database queries with proper result set generation just in time within the test? But at the same time
we need to really use JDBC to connect and retrieve the data from a JDBC mock server.

This is now possible with the new JDBC server integration in Citrus. You can receive incoming SQL statements (INSERT, UPDATE, SELECT, DELETE, ...) and respond with a proper data set and/or rows updated result.
This enables us to test the data access in a database persistence layer without having to actually create the tables and data needed for the test scenario.

Read about it in chapter link:#jdbc[JDBC server].

[[changes-async]]
=== Async container

Sometimes it is good to execute test actions in parallel so you can do things simultaneously in a test case. In some cases it is just to execute a single test action in parallel to the rest of the test. When using send operations
you already could have used `fork="true"` option on that test action. The async test action container provides such functionality for all other test actions, too. Just add a test action to the async container and
the action is executed in a separate thread. The test case is not blocked with that action execution and immediately executes the next action in place.

Read about it in chapter link:#containers-async[Async].

[[changes-property-functions]]
=== System/Env property functions

There are new functions available to access System properties and environment settings. This enables you to resolve property values in test cases at runtime. See how to use this functions in chapter link:#functions[functions].

[[changes-url-encode-functions]]
=== URL encode/decode functions

Two new functions enable you to URL encode/decode a String with proper URL escaping. See how to use this functions in chapter link:#functions[functions].

[[changes-2-7-3]]
== Changes in Citrus 2.7.3

[[changes-plaintext-ignore]]
=== Ignore sections in plain text

Plain text message validation is usually based on a complete String equals comparison. With latest release we added the possibility to ignore some sections with
well known `@ignore@` keyword placeholder. The message validator will automatically ignore words or character sections based on that. Read more about this in chapter
link:#plain-text-message-validation[plain text message validation].

Also possible is the extraction of sections as new test variables when using the `@variable()@` matcher in the plain text message content.

[[changes-json-schema-validation]]
=== Json schema validation

When dealing with Json message content the latest release allows adding of schema validation. The Json structure is validated with proper schema as of Open API (Swagger) schema rules.
As usual the available schema files are defined in a schema repository in the project configuration. Read more about this in chapter link:#json-schema-validation[json schema validation].

[[changes-junit5]]
=== JUnit5 support

With this release you are able to integrate Citrus with JUnit5 the new generation of the famous unit testing framework. We provide a Citrus JUnit5 extension that can do the trick.
Read more about this in chapter link:#run-with-junit5[run with JUnit5].

[[changes-refactoring]]
=== Refactoring

Deprecated APIs and classes that coexisted a long time are now removed. If your project is using on of these deprecated
classes you may run into compile time errors.
Please have a look at the Citrus API JavaDocs and documentation in order to find out how to use the new APIs and classes
that replaced the old deprecated stuff.

[[changes-bugfixes]]
== Bugfixes

Bugs are part of our software developers world and fixing them is part of your daily business, too. Finding and solving issues
makes Citrus better every day. For a detailed listing of all bugfixes please refer to the complete
https://www.citrusframework.org/changes-report.html[changes log] of each release.


[[changes-2-7]]
== Changes in Citrus 2.7

Citrus 2.7 is using Java 8! The Citrus sources are compiled with Java 8 which means that from now on you need at least
Java 8 runtime to work with Citrus. With this Java 8 base Citrus
is proud to welcome two new crew members for supporting Selenium and Kubernetes in tests. Not enough we have the following
features included in the box.

[[changes-java-8]]
=== Java 8

Citrus is now using Java 8. This is mainly because we need to move on in using latest versions of Spring Framework,
Apache Camel and so on. If you are still stuck on Java 7 you can not update to 2.7 as the Citrus sources are compiled with
Java 8. Please contact us in case you really can not update to Java 8 in your project. We can think of a minor bugfix version
with Citrus 2.6 base that still supports Java 7 runtime. On the bright side we can now use the full power of Lambda expressions
and other Java 8 features in Citrus code base.

[[changes-kubernetes]]
=== Kubernetes support

Citrus is now able to interact with http://kubernetes.io/[Kubernetes] remote API in order to manage pods, services and other
resources on the Kubernetes platform. The Kubernetes client is based on the https://github.com/fabric8io/kubernetes-client[Fabric8 Java client]
that interacts with the Kubernetes API via REST services. So you can access Kubernetes resources within Citrus in order to
change or validate the resource state for containerized testing.
This is very useful when dealing with container application environments as part of the integration tests. Please stay tuned
for blog posts and tutorial samples on how Citrus can help you test Microservices with Docker and Kubernetes. The basic usage is
described in section link:#kubernetes[kubernetes].

[[changes-selenium]]
=== Selenium support

User interface and browser testing has not been a focus within Citrus integration testing until now that we can integrate
with the famous http://www.seleniumhq.org/[Selenium] UI testing library. Thanks to the great contributions made by the
community - especially by https://github.com/vdsrd[vdsrd@github] - we can use Selenium based actions and features directly
in a Citrus test case. The Citrus Java and XML DSL both provide comfortable access to the Selenium API in order to
simulate user interaction within a browser. The mix of user based actions and Citrus messaging transport simulation gives
complete new ways of handling complex integration scenarios. Read more about this in chapter link:#selenium[Selenium].

[[changes-before-after-suite]]
=== Environment based before/after suite

You can enable/disable before and after suite actions based on optional environment or system properties. Users can give
property names or property values that are checked before execution.
Only in case the environment property checks do pass the actions are executed before/after the test suite run.

[[wsaddressing-header-customization]]
=== WsAddressing header customization

We have improved the header customization options when using SOAP WSAddressing feature. You can now overwrite the default
WSAddressing headers per test action in addition to defining the headers on
client endpoint component level.

[[changes-jsonpath-data-dictionary]]
=== JsonPath data dictionary

Json data dictionary was based on a simple dot notated syntax. Now you can also use more complex JsonPath expressions in
order to overwrite elements in Json messages based on the data dictionary settings in Citrus. Read more about that in chapter
link:#data-dictionaries[data-dictionary].

[[changes-java-dsl-test-behavior]]
=== Java DSL test behavior

Test behaviors in Java DSL represent templates in XML DSL. The behavior encapsulates a set of test actions to a group that
can be applied to multiple Java DSL tests. This enables you to combine common test actions in Java DSL with more comfortable
reuse of test action definitions. See chapter link:#test-behavior[test-behavior] how to use that.

[[changes-auto-select-message-type]]
=== Auto select message type

Default message type for validation tasks in Citrus has been _XML_. Based on this message type the respective message validator
implementation applies for _XML_, _JSON_, _plain text_ and so on. You can now change this default message type by setting a
system property (`citrus.default.message.type`). Also Citrus improved the auto select algorithm when the default message type
is obviously not applicable. When a message arrives in Citrus the receiving action tries to find out which message validator
fits best according to the message payload. XML message content is automatically identified by `&lt;&gt;` characters. JSON message
payloads are identified by `{}` or `[]` characters for objects and array representations. This way Citrus tries to find the best
matching message validator for the incoming message. Before that Citrus has always been using the default message type _XML_.

Read about different message validators in link:#message-validation[message-validation].

[[changes-default-cucumber-steps]]
=== Default Cucumber steps

The Citrus Cucumber extension now defines default step definitions for Http, Docker and Selenium. These default steps are ready
for usage in any Cucumber Citrus feature specification. You can load the default steps as additional glue packages in your
Cucumber options. After that you are ready to go for using the default steps directly in feature specification files. With the
extensions you can perform Docker and Selenium commands very easy. Also you can describe the Http REST client-server communication
in BDD style. Read more about this in link:#cucumber[cucumber].

[[changes-db-transactions]]
=== Database transaction handling

When Citrus accesses data storage in form of SQL statements executed on some datasource the transaction handling has not been set in the past. Each SQL
statement has been committed immediately. Especially when executing multiple SQL statement via script this could lead to inconsistencies. With the new release you
can make use of Spring's transaction handling when executing SQL statements with Citrus. You can set a transaction handler with isolation levels and default transaction timeout settings.
This enables you to use transaction blocks for multiple statements with one single commit or rollback. Read more about this in chapter link:#sql-transaction-management[actions accessing the database].

[[changes-environment-settings]]
=== Environment settings

We added a mechanism to overwrite general settings in Citrus via system properties and environment variables. This makes Citrus ready for runtime environments such as Docker and Kubernetes where
you can use environment variables to change Citrus behavior. The available settings and variable names can be seen in chapter link:#configuration[configuration].

[[changes-http-cookies]]
=== Http cookie support

Setting Http cookie related Http headers has been possible in previous versions. We improved that cookie handling in Http request and response messages with a dedicated DSL for adding and verifying cookie information
in Http headers. The Citrus http-server is able to advice the client to set a new cookie with respective *Set-Cookie* headers in response messages. The http-client is able to verify the cookie attributes such as name, value, max-age and so on.
In addition to that the client is able to send the cookie name value pair in further requests as a reference via "*Cookie*" message headers. The complete new cookie handling is described in section link:#http-cookies[Http cookie handling].

[[changes-file-encoding]]
=== File resource encoding

The Citrus test case is able to load file resources in various situations e.g. when defining expected message contents. The file resource encoding and charset used a system-wide default setting which has been settable via system property (*citrus.file.encoding*).
In addition to that we have added the opportunity to overwrite this system-wide setting in each resource read operation. This means that everywhere where it is possible to load a file resource you can explicitly set a file encoding and charset for this read operation.
This enables you to use more than one system-wide file encoding setting when reading data from external file resources in Citrus.