[[configuration]]
= Configuration options

You have several options to customize your Citrus project. Citrus uses default settings that can be overwritten to some
extent. As a framework Citrus internally works with components organized in a central context (e.g. the Spring application
context). Citrus registers components in the context in order to share those with the test execution runtime. You can
customize the behavior of these components over environment variables and system properties.

[[configuration-environment-settings]]
== Environment settings

Citrus as an application reads general settings from system properties and environment variables. The Citrus framework
settings initialize on the startup and evaluate environment settings in favor of using default values.

The environment settings are well suited for both usual Java runtime environment and containerized runtime environments
such as Docker or Kubernetes. The following settings do support this kind of environment configuration.

.System properties
|===
|System properties |Description

| citrus.application.properties
| File location for application property file that holds other settings. These properties get loaded as system properties on startup. (default="classpath:citrus-application.properties")

| citrus.java.config
| Class name for custom Java configuration (default=null)

| citrus.file.encoding
| Default file encoding used in Citrus when reading and writing file content (default=Charset.defaultCharset())

| citrus.default.message.type
| Default message type for validating payloads (default="XML")

| citrus.test.name.variable
| Default test name variable that is automatically created for each test (default="citrus.test.name")

| citrus.test.package.variable
| Default test package variable that is automatically created for each test (default="citrus.test.package")

| citrus.default.src.directory
| Default test source directory (default="src/test/")

| citrus.xml.file.name.pattern
| File name patterns used for XML test file package scan (default="/\\**/*Test.xml,/**/*IT.xml")

| citrus.java.file.name.pattern
| File name patterns used for Java test sources package scan (default="/\\**/*Test.java,/**/*IT.java")
|===

Same properties are settable via environment variables.

.Environment variables
|===
|Environment variable |Description

| CITRUS_APPLICATION_PROPERTIES
| File location for application property file that holds other settings. These properties get loaded as system properties on startup. (default="classpath:citrus-application.properties")

| CITRUS_JAVA_CONFIG
| Class name for custom Java configuration (default=null)

| CITRUS_FILE_ENCODING
| Default file encoding used in Citrus when reading and writing file content (default=Charset.defaultCharset())

| CITRUS_DEFAULT_MESSAGE_TYPE
| Default message type for validating payloads (default="XML")

| CITRUS_TEST_NAME_VARIABLE
| Default test name variable that is automatically created for each test (default="citrus.test.name")

| CITRUS_TEST_PACKAGE_VARIABLE
| Default test package variable that is automatically created for each test (default="citrus.test.package")

| CITRUS_DEFAULT_SRC_DIRECTORY
| Default test source directory (default="src/test/")

| CITRUS_XML_FILE_NAME_PATTERN
| File name patterns used for XML test file package scan (default="/\\**/*Test.xml,/**/*IT.xml")

| CITRUS_JAVA_FILE_NAME_PATTERN
| File name patterns used for Java test sources package scan (default="/\\**/*Test.java,/**/*IT.java")
|===

[[configuration-property-binding]]
== Property binding support

The Citrus project defines components and endpoints in the form of beans in the Citrus registry, which is either the Java configuration or a Spring bean configuration. The beans in the registry provide properties that you can overwrite with environment variables and system properties.

Each bean that is added to the Citrus registry is being post processed with the Citrus property binding support.
Users can overwrite these properties on components, endpoints and endpoint configuration with environment specific settings.

The Citrus property binding support follows a naming convention that looks like follows:

.Environment variables
[source, properties]
----
CITRUS_COMPONENT_<COMPONENT_NAME>_<PROPERTY_NAME>=<VALUE>
----

Also, specific to endpoints the naming convention looks like this:

.Environment variables
[source, properties]
----
CITRUS_ENDPOINT_<ENDPOINT_NAME>_<PROPERTY_NAME>=<VALUE>
CITRUS_ENDPOINT_CONFIG_<ENDPOINT_NAME>_<PROPERTY_NAME>=<VALUE>
----

According to that users can also use system property settings that follow the same rules:

.System properties
[source, properties]
----
citrus.component.<component-name>.<property-name>=<value>
citrus.endpoint.<endpoint-name>.<property-name>=<value>
citrus.endpoint.config.<endpoint-name>.<property-name>=<value>
----

The difference of using `CITRUS_ENDPOINT` compared to using `CITRUS_ENDPOINT_CONFIG` is that the latter targets the specific endpoint configuration of the bean. The former will just set properties on the endpoint itself.

The component or endpoint name references the bean name that is used to store the object into the Citrus registry.
The property name is the name of the setter method available on the object (without the `set` prefix)

Given an endpoint named `foo` with a `setPort(int port)` method the environment setting to overwrite the property would be like this:

.Environment variable
[source, properties]
----
CITRUS_ENDPOINT_FOO_PORT=12345
----

.System property
[source, properties]
----
citrus.endpoint.foo.port=12345
----

When the bean name or the property name uses camel case style you have multiple ways to represent this in the environment settings.

As an example the given endpoint named `myBean` exposes the method `setRequestUrl(String url)`.
You have multiple ways to set this property:

.Environment variable
[source, properties]
----
CITRUS_ENDPOINT_MYBEAN_REQUESTURL=http://whatever

CITRUS_ENDPOINT_MY_BEAN_REQUEST_URL=http://whatever
----

.System properties
[source, properties]
----
citrus.endpoint.myBean.requestUrl=http://whatever

citrus.endpoint.myBean.request-url=http://whatever
----

The property bindings may reference other beans in the Citrus registry.
Given a bean named `myLog` of type `org.citrusframework.LogModifier`, that is stored to the Citrus registry, you can be reference the bean with the `#bean:` prefix like this:

[source, properties]
----
CITRUS_ENDPOINT_FOO_LOG_MODIFIER=#bean:myLog
----

This will resolve the bean named `myLog` from the Citrus registry and set this as a reference on the endpoint `foo` with the `setLogModifier()` method.

The property binding support is enabled by default for components, endpoints and endpoint configuration.
You can disable the bindings with the environment setting:

.System properties
|===
|System properties |Description

| citrus.env.var.property.binding.enabled
| Set this to `false` to disable the property binding completely.

| citrus.component.property.binding.enabled
| Set this to `false` to disable the property binding for components.

| citrus.endpoint.property.binding.enabled
| Set this to `false` to disable the property binding for endpoints.

|===

.Environment variables
|===
|Environment variable |Description

| CITRUS_ENV_VAR_PROPERTY_BINDING_ENABLED
| Set this to `false` to disable the property binding completely.

| CITRUS_COMPONENT_PROPERTY_BINDING_ENABLED
| Set this to `false` to disable the property binding for components.

| CITRUS_ENDPOINT_PROPERTY_BINDING_ENABLED
| Set this to `false` to disable the property binding for endpoints.

|===

[[configuration-spring]]
== Spring configuration settings

When spring framework is enabled in Citrus you can set specific settings regarding the Spring
application context.

.System properties
|===
|System properties |Description

| citrus.spring.application.context
| File location for Spring XML configurations (default="classpath*:citrus-context.xml")

| citrus.spring.java.config
| Class name for Spring Java config (default=null)

|===

.Environment variables
|===
|Environment variable |Description

| CITRUS_SPRING_APPLICATION_CONTEXT
| File location for Spring XML configurations (default="classpath*:citrus-context.xml")

| CITRUS_SPRING_JAVA_CONFIG
| Class name for Spring Java config (default=null)

|===

[[configuration-property-file]]
== Property file settings

As mentioned in the previous section Citrus as a framework references some basic settings from system environment properties
or variables. You can overwrite these settings in a central property file which is loaded at the very beginning of the
Citrus runtime.

The properties in that file are automatically loaded as Java system properties. Just add a property file named
*citrus-application.properties* to your project classpath. This property file contains customized settings such as:

.citrus-application.properties
[source,properties]
----
citrus.spring.application.context=classpath*:citrus-custom-context.xml
citrus.spring.java.config=org.citrusframework.config.MyCustomConfig
citrus.file.encoding=UTF-8
citrus.default.message.type=XML
citrus.xml.file.name.pattern=/**/*Test.xml,/**/*IT.xml
----

Citrus automatically loads these application properties at the startup. All properties are also settable with Java system
properties directly. The location of the `citrus-application.properties` file is customizable with the system property
`citrus.application.properties or environment variable `CITRUS_APPLICATION_PROPERTIES`.
          `
.Custom property file location.
[source,shell]
----
CITRUS_APPLICATION_PROPERTIES=file:/custom/path/to/citrus-application.properties
----

NOTE: You can use *classpath:* and *file:* path prefix in order to give locate a classpath or file-system resource.
