[[containers-wait]]
== Wait

With this action you can make your test wait until a certain condition is satisfied. The attribute *seconds* defines the amount of time to wait in seconds. You can also use the milliseconds attribute for a more fine grained time value. The attribute *interval* defines the amount of time to wait *between* each check. The interval is always specified as millisecond time interval.

If the check does not exceed within the defined overall waiting time then the test execution fails with an appropriate error message. There are different types of conditions to check.

[horizontal]
http:: This condition is based on an Http request call on a server endpoint. Citrus will wait until the Http response is as defined (e.g. Http 200 OK). This is useful when you want to wait for a server to start.
file:: This condition checks for the existence of a file on the local file system. Citrus will wait until the file is present.
message:: This condition checks for the existence of a message in the local message store of the current test case. Citrus will wait until the message with the given name is present.
action:: This condition executes another test action and checks for successful execution. Citrus will wait until the nested action is executed without any errors.

When should somebody use this action? This action is very useful when you want your test to wait for a certain event to occur before continuing with the test execution. For example if you wish that your test waits until a Docker container is started or for an application to create a log file before continuing, then use this action. You can also create your own condition statements
and bind it to the test action.

[[containers-wait-http]]
=== Http condition

Next let us have a look at a simple example:

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void waitTest() {
    $(waitFor()
        .time(Duration.ofMillis(10000))
        .interval(2000)
        .http()
            .url("http://sample.org/resource")
            .status(200)
            .timeout(2000);
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="WaitTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <wait-for timeout="10" interval="2000">
          <http url="http://sample.org/resource" status="200" timeout="2000" />
        </wait-for>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: WaitTest
actions:
  - wait-for:
      timeout: "10"
      interval: "2000"
      http:
        url: path/to/resource/file.txt
        status: 200
        timeout: 2000
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="WaitTest">
        <actions>
            <wait seconds="10" interval="2000">
              <http url="http://sample.org/resource" status="200" timeout="2000" />
            </wait>
        </actions>
    </testcase>
</spring:beans>
----

The example waits for some Http server resource to be available with *Http 200 OK* response. Citrus will use *HEAD* request method by default. You can set the request method with the *method* attribute on the Http condition.

[[containers-wait-file]]
=== File condition

Next let us have a look at the file condition usage:

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void waitTest() {
    $(waitFor()
        .time(Duration.ofMillis(10000))
        .interval(2000)
        .file().path("path/to/resource/file.txt")
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="WaitTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <wait-for timeout="10" interval="2000">
          <file path="path/to/resource/file.txt" />
        </wait-for>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: WaitTest
actions:
  - wait-for:
      timeout: "10"
      interval: "2000"
      file:
        path: path/to/resource/file.txt
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="WaitTest">
        <actions>
            <wait seconds="10" interval="2000">
              <file path="path/to/resource/file.txt" />
            </wait>
        </actions>
    </testcase>
</spring:beans>
----

Citrus checks for the file to exist under the given path. Only if the file exists the test will continue with further test actions.

[[containers-wait-message]]
=== Message condition

Next let us have a look at the message condition usage:

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void waitTest() {
    $(waitFor()
        .time(Duration.ofMillis(10000))
        .interval(2000)
        .message().name("helloRequest")
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="WaitTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <wait-for timeout="10" interval="2000">
          <message name="helloRequest" />
        </wait-for>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: WaitTest
actions:
  - wait-for:
      timeout: "10"
      interval: "2000"
      message:
        name: "helloRequest"
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="WaitTest">
        <actions>
            <wait seconds="10" interval="2000">
              <message name="helloRequest" />
            </wait>
        </actions>
    </testcase>
</spring:beans>
----

Citrus checks for the message with the name *helloRequest* in the local message store. Only if the message with the given name is found the test will continue with further test actions. The local message
store is automatically filled with all exchanged messages (send or receive) in a test case. The message names are defined in the respective send or receive operations in the test.

[[containers-wait-action]]
=== Action condition

Now we would like to wait for some other test action to execute.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void waitTest() {
    $(waitFor()
        .time(Duration.ofMillis(10000))
        .interval(2000)
        .execution()
        .action(
            receive(jmsEndpoint)
                .message()
                .body("Wait for me!")
        )
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="WaitTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <wait-for timeout="10" interval="2000">
          <action>
            <receive endpoint="jmsEndpoint">
                <message>
                    <body><data>Wait for me!</data></body>
                </message>
            </receive>
          </action>
        </wait-for>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: WaitTest
actions:
  - wait-for:
      timeout: "10"
      interval: "2000"
      action:
        receive:
          endpoint: "jmsEndpoint"
          message:
            body: |
              Wait for me!
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="WaitTest">
        <actions>
            <wait seconds="10" interval="2000">
              <action>
                <receive endpoint="jmsEndpoint">
                    <message>
                        <payload>Wait for me!</payload>
                    </message>
                </receive>
              </action>
            </wait>
        </actions>
    </testcase>
</spring:beans>
----

You can add any test action to the wait condition so you can execute any other action and wait for its success. This enables us to also use the full send and receive operations on other message transports.
