[[vert-x-event-bus]]
= Vert.x event bus support

Vert.x is an application platform for the JVM that provides a network event bus for lightweight scalable messaging solutions. The Citrus Vert.x
components do participate on that event bus messaging as producer or consumer. With these components you can access Vert.x instances
available in your network in order to test those Vert.x applications in some integration test scenario.

NOTE: The Vert.x components in Citrus are kept in a separate Maven module. So you should add the module as Maven dependency to your project accordingly.

[source,xml]
----
<dependency>
  <groupId>org.citrusframework</groupId>
  <artifactId>citrus-vertx</artifactId>
  <version>${citrus.version}</version>
</dependency>
----

The next sections discuss sending and receiving operations on the Vert.x event bus with Citrus.

[[vert-x-endpoint]]
== Vert.x endpoint

As usual Citrus uses an endpoint component in order to specify some message destination to send and receive messages to and from.
The Vert.x endpoint component is defined as follows in your Citrus Spring configuration.

.Citrus Bean
[source,java,indent=0,role="primary"]
----
@BindToRegistry
public VertxEndpoint simpleVertxEndpoint() {
    return new VertxEndpointBuilder()
        .host("localhost")
        .port(5001)
        .pubSubDomain(false)
        .address("news-feed")
        .build();
}

private VertxInstanceFactory vertxInstanceFactory() {
    return new CachingVertxInstanceFactory();
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Bean
public VertxEndpoint simpleVertxEndpoint() {
    return new VertxEndpointBuilder()
        .host("localhost")
        .port(5001)
        .pubSubDomain(false)
        .address("news-feed")
        .build();
}

private VertxInstanceFactory vertxInstanceFactory() {
    return new CachingVertxInstanceFactory();
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:citrus="http://www.citrusframework.org/schema/config"
       xmlns:citrus-vertx="http://www.citrusframework.org/schema/vertx/config"
       xsi:schemaLocation="
           http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd
           http://www.citrusframework.org/schema/config
           http://www.citrusframework.org/schema/config/citrus-config.xsd
           http://www.citrusframework.org/schema/vertx/config
           http://www.citrusframework.org/schema/vertx/config/citrus-vertx-config.xsd">

    <citrus-vertx:endpoint id="simpleVertxEndpoint"
          host="localhost"
          port="5001"
          pub-sub-domain="false"
          address="news-feed"/>

    <bean id="vertxInstanceFactory" class="org.citrusframework.vertx.factory.CachingVertxInstanceFactory"/>
</beans>
----

NOTE: Citrus provides a special Vert.x configuration schema that is used in our Spring Xml bean configurations.
You have to include the `citrus-vertx` namespace in your Spring configuration XML files as seen in the example above.

The endpoint holds some general information how to access the Vert.x event bus. Host and port values define the Vert.x Hazelcast
cluster hostname and port. Citrus starts a new Vert.x instance using this cluster. So all other Vert.x instances connected to this
cluster host will receive the event bus messages from Citrus during the test. In your test case you can use this endpoint component
referenced by its id or name in order to send and receive messages on the event bus address *news-feed* . In Vert.x the event bus
address defines the destination for event consumers to listen on. As already mentioned cluster hostname and port are optional, so
Citrus will use *localhost* and a new random port on the cluster host if nothing is specified.

The Vert.x event bus supports publish-subscribe and point-to-point message communication patterns. By default the *pubSubDomain* in
Citrus is false so the event bus sender will initiate a point-to-point communication on the event bus address. This means that only
one single consumer on the event bus address will receive the message. If there are more consumers on the address the first to come
wins and receives the message. In contrary to that the publish-subscribe scenario would deliver the message to all available consumers
on the event bus address simultaneously. You can enable the *pubSubDomain* on the Vert.x endpoint component for this communication pattern.

The Vert.x endpoint needs an instance factory implementation in order to create the embedded Vert.x instance. By default the bean name
*vertxInstanceFactory* is recognized by all Vert.x endpoint components. We will talk about Vert.x instance factories in more detail
later on in this chapter.

As message content you can send and receive JSON objects or simple character sequences to the event bus. Let us have a look at a
simple sample sending action that uses the new Vert.x endpoint component:

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void vertxTest() {
    then(send()
            .endpoint(simpleVertxEndpoint)
            .message()
                .type(MessageType.PLAINTEXT)
                .body("Hello from Citrus!")
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="VertxTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
      <send endpoint="simpleVertxEndpoint">
        <message type="plaintext">
            <body>
              <data>Hello from Citrus!</data>
            </body>
        </message>
      </send>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: VertxTest
actions:
  - send:
      endpoint: "simpleVertxEndpoint"
      message:
        type: PLAINTEXT
        body:
          data: "Hello from Citrus!"
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<testcase name="vertxTest">
    <actions>
        <send endpoint="simpleVertxEndpoint">
          <message type="plaintext">
            <payload>Hello from Citrus!</payload>
          </message>
        </send>
    </actions>
</testcase>
----

As the Vert.x Citrus endpoint is bidirectional you can also receive messages from the event bus.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void vertxTest() {
    then(receive()
            .endpoint(simpleVertxEndpoint)
            .message()
                .type(MessageType.PLAINTEXT)
                .body("Hello from Vert.x!")
                .header("citrus_vertx_address", "news-feed")
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="VertxTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
      <receive endpoint="simpleVertxEndpoint">
        <message type="plaintext">
            <body>
              <data>Hello from Vert.x!</data>
            </body>
            <headers>
              <header name="citrus_vertx_address" value="news-feed"/>
            </headers>
        </message>
      </receive>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: VertxTest
actions:
  - receive:
      endpoint: "simpleVertxEndpoint"
      message:
        type: PLAINTEXT
        body:
          data: "Hello from Vert.x!"
        headers:
          - name: citrus_vertx_address
            value: news-feed
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<testcase name="vertxTest">
    <actions>
        <receive endpoint="simpleVertxEndpoint">
          <message type="plaintext">
            <payload>Hello from Vert.x!</payload>
          </message>
          <header>
            <element name="citrus_vertx_address" value="news-feed"/>
          </header>
        </receive>
    </actions>
</testcase>
----

Citrus automatically adds some special message headers to the message, so you can validate the Vert.x event bus address.
This completes the simple send and receive operations on a Vert.x event bus.
Now let's move on to synchronous endpoints where Citrus waits for a reply on the event bus.

[[synchronous-vert-x-endpoint]]
== Synchronous Vert.x endpoint

The synchronous Vert.x event bus producer sends a message and waits synchronously for the response to arrive on some reply address destination.
The reply address name is generated automatically and set in the request message header attributes so the receiving counterpart in this
communication can send its reply to that event bus address. The basic configuration for a synchronous Vert.x endpoint component looks like follows:

.Citrus Bean
[source,java,indent=0,role="primary"]
----
@BindToRegistry
public VertxSnycEndpoint vertxSyncEndpoint() {
    return new VertxSyncEndpointBuilder()
        .timeout(1000)
        .address("hello")
        .pollingInterval(300)
        .build();
}

private VertxInstanceFactory vertxInstanceFactory() {
    return new CachingVertxInstanceFactory();
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Bean
public VertxSnycEndpoint vertxSyncEndpoint() {
    return new VertxSyncEndpointBuilder()
        .timeout(1000)
        .address("hello")
        .pollingInterval(300)
        .build();
}

private VertxInstanceFactory vertxInstanceFactory() {
    return new CachingVertxInstanceFactory();
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:citrus="http://www.citrusframework.org/schema/config"
       xmlns:citrus-vertx="http://www.citrusframework.org/schema/vertx/config"
       xsi:schemaLocation="
           http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd
           http://www.citrusframework.org/schema/config
           http://www.citrusframework.org/schema/config/citrus-config.xsd
           http://www.citrusframework.org/schema/vertx/config
           http://www.citrusframework.org/schema/vertx/config/citrus-vertx-config.xsd">

    <citrus-vertx:sync-endpoint id="vertxSyncEndpoint"
          address="hello"
          timeout="1000"
          polling-interval="300"/>
</beans>
----

Synchronous endpoints poll for synchronous reply messages to arrive on the event bus reply address. The poll interval is an optional
setting in order to manage the amount of reply message handshake attempts. Once the endpoint was able to receive the reply message
synchronously the test case can receive the reply. In case all message handshake attempts do fail because the reply message is not
available in time we raise some timeout error and the test will fail.

NOTE: The Vert.x endpoint uses temporary reply address destinations. The temporary reply address in generated and is only used once
for a single communication handshake. After that the reply address is dismissed again.

When sending a message to the synchronous Vert.x endpoint the producer will wait synchronously for the response message to arrive
on the reply address. You can receive the reply message in your test case using the same endpoint component. So we have two actions
on the same endpoint, first send then receive.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void vertxTest() {
    when(send()
            .endpoint(vertxSyncEndpoint)
            .message()
                .type(MessageType.PLAINTEXT)
                .body("Hello from Citrus!")
    );

    then(receive()
            .endpoint(vertxSyncEndpoint)
            .message()
                .type(MessageType.PLAINTEXT)
                .body("Hello from Vert.x!")
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="VertxTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
      <send endpoint="vertxSyncEndpoint">
        <message type="plaintext">
            <body>
              <data>Hello from Citrus!</data>
            </body>
        </message>
      </send>

      <receive endpoint="vertxSyncEndpoint">
        <message type="plaintext">
            <body>
              <data>Hello from Vert.x!</data>
            </body>
        </message>
      </receive>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: VertxTest
actions:
  - send:
      endpoint: "vertxSyncEndpoint"
      message:
        type: PLAINTEXT
        body:
          data: "Hello from Citrus!"
  - receive:
      endpoint: "vertxSyncEndpoint"
      message:
        type: PLAINTEXT
        body:
          data: "Hello from Vert.x!"
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<testcase name="vertxTest">
    <actions>
        <send endpoint="vertxSyncEndpoint">
          <message type="plaintext">
            <payload>Hello from Citrus!</payload>
          </message>
        </send>

        <receive endpoint="vertxSyncEndpoint">
          <message type="plaintext">
            <payload>Hello from Vert.x!</payload>
          </message>
        </receive>
    </actions>
</testcase>
----

In the last section we saw that synchronous communication is based on reply messages on temporary reply event bus address. We saw that
Citrus is able to send messages to event bus address and wait for reply messages to arrive. This next section deals with the same synchronous
communication, but send and receive roles are switched. Now Citrus receives a message and has to send a reply message to a temporary reply address.

We handle this synchronous communication with the same synchronous Vert.x endpoint component. Only difference is that we initially
start the communication by receiving a message from the endpoint. Knowing this Citrus is able to send a synchronous response back.
Again just use the same endpoint reference in your test case. The handling of the temporary reply address is done automatically behind the scenes.
So we have again two actions in our test case, but this time first receive then send.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void vertxTest() {
    when(receive()
            .endpoint(vertxSyncEndpoint)
            .message()
                .type(MessageType.PLAINTEXT)
                .body("Hello from Vert.x!")
    );

    then(send()
            .endpoint(vertxSyncEndpoint)
            .message()
                .type(MessageType.PLAINTEXT)
                .body("This is the reply from Citrus!")
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="VertxTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
      <receive endpoint="vertxSyncEndpoint">
        <message type="plaintext">
            <body>
              <data>Hello from Vert.x!</data>
            </body>
        </message>
      </receive>

      <send endpoint="vertxSyncEndpoint">
        <message type="plaintext">
            <body>
              <data>This is the reply from Citrus!</data>
            </body>
        </message>
      </send>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: VertxTest
actions:
  - receive:
      endpoint: "vertxSyncEndpoint"
      message:
        type: PLAINTEXT
        body:
          data: "Hello from Vert.x!"
  - send:
      endpoint: "vertxSyncEndpoint"
      message:
        type: PLAINTEXT
        body:
          data: "This is the reply from Citrus!"
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<testcase name="vertxTest">
    <actions>
        <receive endpoint="vertxSyncEndpoint">
          <message type="plaintext">
            <payload>Hello from Vert.x!</payload>
          </message>
        </receive>

        <send endpoint="vertxSyncEndpoint">
          <message type="plaintext">
            <payload>This is the reply from Citrus!</payload>
          </message>
        </send>
    </actions>
</testcase>
----

The synchronous message endpoint for Vert.x event bus communication will handle all reply address destinations and provide those behind the scenes.

[[vert-x-instance-factory]]
== Vert.x instance factory

Citrus starts an embedded Vert.x instance at runtime in order to participate in the Vert.x cluster. Within this cluster multiple Vert.x
instances are connected via the event bus. For starting the Vert.x event bus Citrus uses a cluster hostname and port definition. You can
customize this cluster host in order to connect to a very special cluster in your network.

Now Citrus needs to manage the Vert.x instances created during the test run. By default Citrus will look for an instance factory bean
named *vertxInstanceFactory* . You can choose the factory implementation to use in your project. By default you can use the caching factory
implementation that caches the Vert.x instances so we do not connect more than one Vert.x instance to the same cluster host.
Citrus offers following instance factory implementations:

org.citrusframework.vertx.factory.CachingVertxInstanceFactory:: default implementation that reuses the Vert.x instance based on given
cluster host and port. With this implementation we ensure to connect a single Citrus Vert.x instance to a cluster host.
org.citrusframework.vertx.factory.SingleVertxInstanceFactory:: creates a single Vert.x instance and reuses this instance for all endpoints.
You can also set your very custom Vert.x instance via configuration for custom Vert.x instantiation.

The instance factory implementations do implement the *_VertxInstanceFactory_* interface. So you can also provide your very special implementation.
By default, Citrus looks for a bean named *vertxInstanceFactory* but you can also define your very special factory implementation onm an endpoint component.
The Vert.x instance factory is set on the Vert.x endpoint as follows:

.Citrus Bean
[source,java,indent=0,role="primary"]
----
@BindToRegistry
public VertxEndpoint vertxHelloEndpoint() {
    return new VertxEndpointBuilder()
        .address("news-feed")
        .vertxInstanceFactory(singleVertxInstanceFactory())
        .build();
}

private VertxInstanceFactory singleVertxInstanceFactory() {
    return new CachingVertxInstanceFactory();
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Bean
public VertxEndpoint vertxHelloEndpoint() {
    return new VertxEndpointBuilder()
        .address("news-feed")
        .vertxInstanceFactory(singleVertxInstanceFactory())
        .build();
}

private VertxInstanceFactory singleVertxInstanceFactory() {
    return new SingleVertxInstanceFactory();
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:citrus="http://www.citrusframework.org/schema/config"
       xmlns:citrus-vertx="http://www.citrusframework.org/schema/vertx/config"
       xsi:schemaLocation="
       http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
       http://www.citrusframework.org/schema/config
       http://www.citrusframework.org/schema/config/citrus-config.xsd
       http://www.citrusframework.org/schema/vertx/config
       http://www.citrusframework.org/schema/vertx/config/citrus-vertx-config.xsd">

    <citrus-vertx:endpoint id="vertxHelloEndpoint"
          address="news-feed"
          vertx-factory="singleVertxInstanceFactory"/>

    <bean id="singleVertxInstanceFactory"
          class="org.citrusframework.vertx.factory.SingleVertxInstanceFactory"/>
</beans>
----
