[[jdbc]]
= JDBC support

Database communication is an essential part of many applications, when persistent data storage is required.
May it be orders, customer data, product recommendations or product information, if persistent storage is in place,
the data contains a certain business value. Therefore it's important that your software handles your persistent storage
the right way. To ensure that, Citrus offers a JDBC server endpoint that allows you to verify the communication between
your application and a real database server which is accessible via the Citrus-JDBC-Driver.

To enable the JDBC support for your test project, you'll have to add the following dependency.

[source,xml]
----
<dependency>
  <groupId>org.citrusframework</groupId>
  <artifactId>citrus-jdbc</artifactId>
  <version>${citrus.version}</version>
  <scope>test</scope>
</dependency>
----

[[jdbc-driver]]
== The Citrus-JDBC-Driver

The Citrus-JDBC-Driver is a JDBC conform driver that realizes the communication with the Citrus-JDBC-Server. To be able
to use Citrus-JDBC within a CI/CD setup, we recommend to ensure that your software is able to exchange the JDBC driver
by configuration. The Citrus-JDBC-Driver is available on maven central under
`org.citrusframework.citrus-db-driver`. After the driver has been downloaded and configured to be used by your
application, please make sure that the driver configuration matches the Citrus-JDBC-Server configuration in your
tests.

.Example jdbc driver configuration
[source,xml]
----
<systemProperties>
    <systemProperty>
      <name>todo.persistence.type</name>
      <value>jdbc</value>
    </systemProperty>
    <systemProperty>
      <name>todo.jdbc.driverClassName</name>
      <value>org.citrusframework.db.driver.JdbcDriver</value>
    </systemProperty>
    <systemProperty>
      <name>todo.jdbc.url</name>
      <value>jdbc:citrus:http://localhost:3306/testdb</value>
    </systemProperty>
</systemProperties>
----

.Citrus-JDBC-Server matching the driver config
[source,java]
----
@Bean
public JdbcServer jdbcServer() {
    return CitrusEndpoints.jdbc()
        .server()
        .host("localhost")
        .databaseName("testdb")
        .port(3306)
        .build();
}
----

[[jdbc-server]]
== The Citrus-JDBC-Server

To setup a JDBC endpoint within your tests, just configure it as any other endpoint via e.g.  XML, Spring Bean or by
Citrus Annotations.

.Spring Bean
[source,java,indent=0,role="primary"]
----
@Bean
public JdbcServer jdbcServer() {
    return CitrusEndpoints.jdbc()
        .server()
        .host("localhost")
        .databaseName("testdb")
        .port(4567)
        .timeout(10000L)
        .autoStart(true)
        .autoTransactionHandling(false)
        .build();
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<citrus-jdbc:server id="testServer"
                      host="citrus-jdbc-test-server"
                      port="4567"
                      database-name="test-db"
                      max-connections="50"
                      auto-start="true"/>
----

.Citrus Annotations
[source,java,indent=0,role="secondary"]
----
@CitrusEndpoint
@JdbcServerConfig(
            databaseName = "testdb",
            autoStart = true,
            port = 4567)
private JdbcServer jdbcServer;
----

After that configuration has been done, you'll be able to use the Server within your tests to receive and send messages
from or to your system under test.

[source,java]
----
@Test
@CitrusTest
public void testAddTodoEntry() {
    variable("todoName", "citrus:concat('todo_', citrus:randomNumber(4))");
    variable("todoDescription", "Description: ${todoName}");

    http()
        .client(todoClient)
        .send()
        .post("/todolist")
        .fork(true)
        .contentType("application/x-www-form-urlencoded")
        .payload("title=${todoName}&description=${todoDescription}");

    receive(jdbcServer)
        .messageType(MessageType.JSON)
        .message(JdbcMessage.execute(
            "@startsWith('INSERT INTO todo_entries (id, title, description, done) VALUES (?, ?, ?, ?)')@"));<1>

    send(jdbcServer)
        .message(JdbcMessage.result().rowsUpdated(1));<2>

    http()
        .client(todoClient)
        .receive()
        .response(HttpStatus.FOUND);

    http()
        .client(todoClient)
        .send()
        .get("/todolist")
        .fork(true)
        .accept("text/html");

    receive(jdbcServer)
            .message(JdbcMessage.execute("SELECT id, title, description FROM todo_entries"));<3>

    send(jdbcServer)
        .messageType(MessageType.JSON)
        .message(JdbcMessage.result().dataSet("[ {" +
                    "\"id\": \"" + UUID.randomUUID().toString() + "\"," +
                    "\"title\": \"${todoName}\"," +
                    "\"description\": \"${todoDescription}\"," +
                    "\"done\": \"false\"" +
                "} ]"));<4>

    http()
        .client(todoClient)
        .receive()
        .response(HttpStatus.OK)
        .messageType(MessageType.XHTML)
        .xpath("(//xh:li[@class='list-group-item']/xh:span)[last()]", "${todoName}");
}
----
<1> Expects a `INSERT` statement matching the given expression.
<2> Responds with a result set stating, that one row has been updated/created.
<3> Expects a `SELECT` statement matching the given statement.
<4> Responds with the DataSet specified as JSON string.

[[jdbc-server-transactions]]
=== Transactions
When it comes to complex modifications of your database, transactions are commonly used.
Citrus is able to verify the behavior of your system under test concerning start, commit and rollback
actions of transactions. The verification of transactions has to be enabled in the server Citrus-JDBC-Server
configuration. For more information, please have a look at the <<jdbc-server-configuration>> section.

.Verifiying transaction commit
[source,java]
----
receive(jdbcServer)
    .message(JdbcMessage.startTransaction());<1>

receive(jdbcServer)
    .message(JdbcMessage.execute("@startsWith('INSERT INTO todo_entries (id, title, description, done) VALUES (?, ?, ?, ?)')@"));

send(jdbcServer)
    .message(JdbcMessage.result().rowsUpdated(1));

receive(jdbcServer)
    .message(JdbcMessage.commitTransaction());<2>
----
<1> Verify, that the transaction has been started.
<2> Verify, that the modification of the database has been committed.

It is also possible to simulate an erroneous modification including the verification of a rollback.

.Verifiying transaction rollback
[source,java]
----
receive(jdbcServer)
    .message(JdbcMessage.startTransaction());<1>

receive(jdbcServer)
    .message(JdbcMessage.execute("@startsWith('INSERT INTO todo_entries (id, title, description, done) VALUES (?, ?, ?, ?)')@"));

send(jdbcServer)
    .message(JdbcMessage.result().exception("Could not execute something"));

receive(jdbcServer)
    .message(JdbcMessage.rollbackTransaction());<2>
----
<1> Verify, that the transaction has been started.
<2> Verify, that a rollback occurred after the database exception has been send.

[[jdbc-server-prepared-statements]]
=== Prepared statements
Because prepared statements work slightly different than simple database queries, the validation of those is also
slightly different. Currently, Citrus offers you the possibility to verify that your application has created the
correct prepared statement, that it was executed with the correct parameters and that it has been closed.

.Verifying prepared statement
[source,java]
----
receive(jdbcServer)
    .message(JdbcMessage.createPreparedStatement("INSERT INTO todo_entries (id, title, description, done) VALUES (?, ?, ?, ?)"));<1>

receive(jdbcServer)
    .message(JdbcMessage.execute(
        "INSERT INTO todo_entries (id, title, description, done) VALUES (?, ?, ?, ?) - (1,sample,A sample todo,false)"));<2>

receive(jdbcServer)
    .message(JdbcMessage.closeStatement());<3>
----
<1> Verify that the given prepared statement has been created.
<2> Verify that the statement has been executed with the parameters `1,sample,A sample todo,false`.
<3> Verify that the statement has been closed.

Please notice, that the verification of `createPreparedStatement` and `closeStatement` messages has to be activated
via configuration. For more information, please have a look at the <<jdbc-server-configuration>> section.

[[jdbc-server-callable-statements]]
=== Callable statements / stored procedures
As well as prepared statements, callable statements are different from simple queries. Callable statements are used
on jdbc level to access stored procedures, functions, etc. on the database server.

.Verifying callable statement
[source,java]
----
receive(jdbcServer)
    .message(JdbcMessage.createCallableStatement("{CALL limitedToDoList(?)}"));<1>

receive(jdbcServer)
    .message(JdbcMessage.execute("{CALL limitedToDoList(?)} - (1)"));<2>

send(jdbcServer)
    .messageType(MessageType.XML)
    .message(JdbcMessage.result().dataSet("" +
            "<dataset>" +
                "<row>" +
                    "<id>1</id>"+
                    "<title>sample</title>"+
                    "<description>A sample todo</description>" +
                    "<done>false</done>" +
                 "</row>" +
                "</dataset>"));

receive(jdbcServer)
    .message(JdbcMessage.closeStatement());<3>
----
<1> Verify that the given callable statement has been created.
<2> Verify that the statement has been executed with the parameter `1`.
<3> Verify that the statement has been closed.

As you might have noticed, callable statements and prepared statements have nearly the same workflow in Citrus. The only
difference is the creation of the statement itself. It is also the case that the verification of
`createCallableStatement` and `closeStatement` messages has to be activated via configuration. For more information,
please have a look at the <<jdbc-server-configuration>> section.

[[jdbc-server-configuration]]
=== Configuration

As already mentioned, you're able to configure the JDBC endpoint in different ways (XML, Spring Bean, etc. ).
The following properties are available to configure the server for your test scenario.

[cols="2,2,2,5a"]
|===
| Property | Mandatory | Default | Description

| id
| Yes
|
| Only required for XML configuration.

| auto connect
| No
| true
| Determines whether the server should automatically accept connection related messages or validate them.
This includes `openConnection` and `closeConnection`.

| auto create statement
| No
| true
| Determines whether the server should automatically accept statement related messages or validate them.
This includes `createStatement`, `createPreparedStatement`, `createCallableStatement` and `closeStatement`.

| auto transaction handling
| No
| true
| Determines whether the server should automatically accept transaction related messages or validate them.
This includes `startTransaction`, `commitTransaction` and `rollbackTransaction`.

| auto handle queries
| No
| Collection of system queries for different databases
| Determines whether the server should automatically respond with a positive answer for matching queries, e.g. `SELECT USER FROM DUAL`. You can override the currently defined validation queries when setting `citrus.jdbc.auto.handle.query` system property within the citrus-application.properties. The property value is expected to be a  semicolon separated list of regex patterns. Every query can be specified as a regular expression, e.g. `SELECT.*FROM DUAL;SELECT \\w;`.

| host
| Yes
|
| The hostname of the server. There has to be a valid route between the test suite, the system under test and the
database server.

| port
| No
| 4567
| The port the server listens to.

| database name
| Yes
|
| The database name to work on

| max connections
| No
| 20
| The maximum amount of open connections to be accepted by the server.

| polling interval
| No
| 500
| Polling interval when waiting for synchronous reply message to arrive.

| timeout
| No
| 5000
| Send/receive timeout setting

| debug logging
| No
| false
| Determines whether the inbound channel debug logging should be enabled.

|===

In addition, there are advanced configuration possibilities to customize the behavior of the JDBC server.

[cols="2,2,2,5a"]
|===
| Property | Mandatory | Default | Description

| correlator
| No
| DefaultMessageCorrelator
| A MessageCorrelator implementation to identify messages.

| endpoint adapter
| No
| JdbcEndpointAdapterController
| An Endpoint adapter implementation creating the messages for validation.

|===

[[jdbc-message]]
== JdbcMessage

The JdbcMessage class is the central location to specifying your expected inbound and outbound communication for the
JDBC endpoint.

[cols="5,2,5a"]
|===
| Message | receive/send | Description

| `JdbcMessage.openConnection(Properties properties)`
| receive
| States that a connection has been opened with the given properties. The evaluation of connections has to be enabled
via the endpoint configuration.

| `JdbcMessage.closeConnection()`
| receive
| States that the connection has been closed. The evaluation of connections has to be enabled
via the endpoint configuration.

| `JdbcMessage.createStatement()`
| receive
| States that a statement has been created. The evaluation of statement handling has to be enabled via the endpoint
configuration.

| `JdbcMessage.createPreparedStatement(String sql)`
| receive
| States that a SQL statement matching the given expression has been created. The evaluation of statement handling
has to be enabled via the endpoint configuration.

| `JdbcMessage.createCallableStatement(String sql)`
| receive
| States that a callable statement referencing a function or procedure that is matching the given expression has been
created. The evaluation of statement handling has to be enabled via the endpoint configuration.

| `JdbcMessage.closeStatement()`
| receive
| States that a statement has been closed. The evaluation of statement handling has to be enabled via the endpoint
configuration.

| `JdbcMessage.execute(String sql)`
| receive
| States that a SQL statement matching the given expression has been executed.

| `JdbcMessage.startTransaction()`
| receive
| States that a transaction start has been received. The evaluation of transaction handling has to be enabled via
the endpoint configuration.

| `JdbcMessage.commitTransaction()`
| receive
| States that a commit for a transaction has been received. The evaluation of transaction handling has to be enabled via
the endpoint configuration.

| `JdbcMessage.rollbackTransaction()`
| receive
| States that a rollback of the transaction has been received. The evaluation of transaction handling has to be enabled
via the endpoint configuration.

| `JdbcMessage.result()`
| send
| Sends a positive empty result to the system under test.

| `JdbcMessage.result(boolean success)`
| send
| Sends empty result to the system under test which is a success or a failure based on the given boolean value.

| `JdbcMessage.exception(String exceptionText)`
| send
| Sends an exception to the system under test. Regarding the driver documentation, the error will be an SQLException.

| `JdbcMessage.rowsUpdated(int number)`
| send
| Sends a positive result to the system under test where the payload is the number of updated rows.

| `JdbcMessage.dataSet(DataSet dataSet)`
| send
| Sends a positive result to the system under test where the payload is the specified DataSet.

| `JdbcMessage.dataSet(String dataSet)`
| send
| Sends a positive result to the system under test where the payload is the specified DataSet. To use this, you have
to specify the format of the dataSet String. Please refer to the section <<jdbc-message-dataset-parsing>>.

| `JdbcMessage.dataSet(Resource dataSet)`
| send
| Sends a positive result to the system under test where the payload is the content of the specified resource.
To use this, you have to specify the format of the dataSet String. Please refer to the section
<<jdbc-message-dataset-parsing>>.

| `JdbcMessage.success()`
| send
| Sends a positive empty result to the system under test.

| `JdbcMessage.error()`
| send
| Sends an empty error result to the system under test.

|===

[[jdbc-message-dataset-parsing]]
=== DataSet parsing

Citrus provides different ways to prepare the response DataSets for your system under test. You can specify your
DataSets as Java Objects, as XML or JSON Strings or as resource file containing your XML or JSON DataSet as text.

.Java dataset creation example
[source,java]
----
Row sheldon = new Row();
sheldon.getValues().put("id", "1");
sheldon.getValues().put("name", "Sheldon");
sheldon.getValues().put("profession", "physicist");

Row leonard = new Row();
leonard.getValues().put("id", "2");
leonard.getValues().put("name", "Leonard");
leonard.getValues().put("profession", "physicist");
leonard.getValues().put("email", "leo@bigbangtheory.org");

Row penny = new Row();
penny.getValues().put("id", "3");
penny.getValues().put("name", "Penny");
penny.getValues().put("profession", "this_and_that");

Table table = new Table("user");
table.getRows().add(sheldon);
table.getRows().add(leonard);
table.getRows().add(penny);

DataSet userDataSet = new TableDataSetProducer(table).produce();

send(jdbcServer).message(JdbcMessage.result().dataSet(userDataSet));
----

If you use the XML or JSON notation as string or within a resource, you'll have to specify that in your test setup.

.Java json dataset creation example
[source,java]
----
receive(jdbcServer)
                .message(JdbcMessage.execute("SELECT id, title, description FROM todo_entries"));

send(jdbcServer)
        .messageType(MessageType.JSON)<1>
        .message(JdbcMessage.result().dataSet("[ {" +
                    "\"id\": \"" + UUID.randomUUID().toString() + "\"," +
                    "\"title\": \"${todoName}\"," +
                    "\"description\": \"${todoDescription}\"," +
                    "\"done\": \"false\"" +
                "} ]"));
----
<1> Tells Citrus that the response has to be interpreted as JSON.

.Java xml dataset creation example
[source,java]
----
receive(jdbcServer)
        .message(JdbcMessage.execute("SELECT id, title, description FROM todo_entries"));
send(jdbcServer)
        .messageType(MessageType.XML)<1>
        .message(JdbcMessage.result().dataSet("" +
                "<dataset>" +
                    "<row>" +
                        "<id>${todoId}</id>"+
                        "<title>${todoName}</title>"+
                        "<description>${todoDescription}</description>" +
                        "<done>false</done>" +
                     "</row>" +
                "</dataset>"));
----
<1> Tells Citrus that the response has to be interpreted as XML.

NOTE: Technically it is not required to specify the messages as `MessageType.XML`, because the default message type
in citrus currently *is* XML. Nevertheless we highly recommend to specify the message type. This will ensure that your
tests sustain future changes.
