[[jmx]]
= JMX support

JMX is a standard Java API for making beans accessible to others in terms of management and remote configuration. JMX is the short term for Java Management Extensions and is often used in JEE application servers to manage bean attributes and operations from outside (e.g. another JVM). A managed bean server hosts multiple managed beans for JMX access. Remote connections to JMX can be realized with RMI (Remote method invocation) capabilities.

Citrus is able to connect to JMX managed beans as client and server. As a client Citrus can invoke managed bean operations and read write managed bean attributes. As a server Citrus is able to expose managed beans as mbean server. Clients can access those Citrus managed beans and get proper response objects as result. Doing so you can use the JVM platform managed bean server or some RMI registry for providing remote access.

NOTE: The JMX components in Citrus are kept in a separate Maven module. So you should check that the module is available as Maven dependency in your project

[source,xml]
----
<dependency>
  <groupId>org.citrusframework</groupId>
  <artifactId>citrus-jmx</artifactId>
  <version>${citrus.version}</version>
</dependency>
----

As usual Citrus provides a customized jmx configuration schema that is used in Spring configuration files. Simply include the citrus-jmx namespace in the configuration XML files as follows.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns:citrus="http://www.citrusframework.org/schema/config"
      xmlns:citrus-jmx="http://www.citrusframework.org/schema/jmx/config"
      xsi:schemaLocation="
      http://www.springframework.org/schema/beans
      http://www.springframework.org/schema/beans/spring-beans.xsd
      http://www.citrusframework.org/schema/config
      http://www.citrusframework.org/schema/config/citrus-config.xsd
      http://www.citrusframework.org/schema/jmx/config
      http://www.citrusframework.org/schema/jmx/config/citrus-jmx-config.xsd">

      [...]

      </beans>
----

Now you are ready to use the customized Http configuration elements with the citrus-jmx namespace prefix.

Next sections describe the JMX message support in Citrus in more detail.

[[jmx-client]]
== JMX client

On the client side we want to call some managed bean by either accessing managed attributes with read/write or by invoking a managed bean operation. For proper mbean server connectivity we should specify a client component for JMX that sends out mbean invocation calls.

[source,xml]
----
<citrus-jmx:client id="jmxClient"
      server-url="platform"/>
----

The client component specifies the target managed bean server that we want to connect to. In this example we are using the JVM platform mbean server. This means we are able to access all JVM managed beans such as Memory, Threading and Logging. In addition to that we can access all custom managed beans that were exposed to the platform mbean server.

In most cases you may want to access managed beans on a different JVM or application server. So we need some remote connection to the foreign mbean server.

[source,xml]
----
<citrus-jmx:client id="jmxClient"
      server-url="service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi"
      username="user"
      password="s!cr!t"
      auto-reconnect="true"
      delay-on-reconnect="5000"/>
----

In this example above we connect to a remote mbean server via RMI using the default RMI registry *localhost:1099* and the service name *jmxrmi* . Citrus is able to handle different remote transport protocols. Just define those in the *server-url* .

Now that we have setup the client component we can use it in a test case to access a managed bean.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void jmxMessageTest() {
    $(send(jmxClient)
        .message(JmxMessage.invocation("java.lang:type=Memory")
            .attribute("Verbose"))
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="JmxMessageTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <send endpoint="jmxClient">
            <message>
                <body>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>java.lang:type=Memory</mbean>
                          <attribute name="Verbose"/>
                        </mbean-invocation>
                    </payload>
                </body>
            </message>
        </send>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: JmxMessageTest
actions:
  - send:
      endpoint: "jmxClient"
      message:
        body: |
          <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
              <mbean>java.lang:type=Memory</mbean>
              <attribute name="Verbose"/>
          </mbean-invocation>
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="JmxMessageTest">
        <actions>
            <send endpoint="jmxClient">
                <message>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>java.lang:type=Memory</mbean>
                          <attribute name="Verbose"/>
                        </mbean-invocation>
                    </payload>
                </message>
            </send>
        </actions>
    </testcase>
</spring:beans>
----

As you can see we just used a normal send action referencing the jmx client component that we have just added. The message payload is an XML representation of the managed bean access. This is a special Citrus XML representation. Citrus will convert this XML payload to the actuel managed bean access. In the example above we try to access a managed bean with object name *java.lang:type=Memory* . The object name is defined in JMX specification and consists of a key *java.lang:type* and a value *Memory* . So we identify the managed bean on the server by its type.

Now that we have access to the managed bean we can read its managed attributes such as *Verbose* . This is a boolean type attribute so the mbean invocation result will be a respective Boolean object. We can validate the managed bean attribute access in a receive action.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void jmxMessageTest() {
    $(receive(jmxClient)
        .message(JmxMessage.result(false))
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="JmxMessageTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <receive endpoint="jmxClient">
            <message>
                <body>
                    <payload>
                        <mbean-result xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <object type="java.lang.Boolean" value="false"/>
                        </mbean-result>
                    </payload>
                </body>
            </message>
        </receive>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: JmxMessageTest
actions:
  - receive:
      endpoint: "jmxClient"
      message:
        body: |
          <mbean-result xmlns="http://www.citrusframework.org/schema/jmx/message">
              <object type="java.lang.Boolean" value="false"/>
          </mbean-result>
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="JmxMessageTest">
        <actions>
            <receive endpoint="jmxClient">
                <message>
                    <payload>
                        <mbean-result xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <object type="java.lang.Boolean" value="false"/>
                        </mbean-result>
                    </payload>
                </message>
            </receive>
        </actions>
    </testcase>
</spring:beans>
----

In the sample above we receive the mbean result and expect a *java.lang.Boolean* object return value. The return value content is also validated within the mbean result payload.

Some managed bean attributes might also be settable for us. So we can define the attribute access as write operation by specifying a value in the send action payload.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void jmxMessageTest() {
    $(send(jmxClient)
        .message(JmxMessage.invocation("java.lang:type=Memory")
            .attribute("Verbose", true))
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="JmxMessageTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <send endpoint="jmxClient">
            <message>
                <body>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>java.lang:type=Memory</mbean>
                          <attribute name="Verbose" value="true" type="java.lang.Boolean"/>
                        </mbean-invocation>
                    </payload>
                </body>
            </message>
        </send>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: JmxMessageTest
actions:
  - send:
      endpoint: "jmxClient"
      message:
        body: |
          <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
              <mbean>java.lang:type=Memory</mbean>
              <attribute name="Verbose" value="true" type="java.lang.Boolean"/>
          </mbean-invocation>
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="JmxMessageTest">
        <actions>
            <send endpoint="jmxClient">
                <message>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>java.lang:type=Memory</mbean>
                          <attribute name="Verbose" value="true" type="java.lang.Boolean"/>
                        </mbean-invocation>
                    </payload>
                </message>
            </send>
        </actions>
    </testcase>
</spring:beans>
----

Now we have write access to the managed attribute *Verbose* . We do specify the value and its type *java.lang.Boolean* . This is how we can set attribute values on managed beans.

Last not least we are able to access managed bean operations.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void jmxMessageTest() {
    $(send(jmxClient)
        .message(JmxMessage.invocation("org.citrusframework.jmx.mbean:type=HelloBean")
            .operation("sayHello")
            .parameter("Hello JMX!"))
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="JmxMessageTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <send endpoint="jmxClient">
            <message>
                <body>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>org.citrusframework.jmx.mbean:type=HelloBean</mbean>
                          <operation name="sayHello">
                            >parameter>
                              >param type="java.lang.String" value="Hello JMX!"/>
                            >/parameter>
                          >/operation>
                        </mbean-invocation>
                    </payload>
                </body>
            </message>
        </send>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: JmxMessageTest
actions:
  - send:
      endpoint: "jmxClient"
      message:
        body: |
          <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
              <mbean>org.citrusframework.jmx.mbean:type=HelloBean</mbean>
              <operation name="sayHello">
                >parameter>
                  >param type="java.lang.String" value="Hello JMX!"/>
                >/parameter>
              >/operation>
          </mbean-invocation>
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="JmxMessageTest">
        <actions>
            <send endpoint="jmxClient">
                <message>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>org.citrusframework.jmx.mbean:type=HelloBean</mbean>
                          <operation name="sayHello">
                            >parameter>
                              >param type="java.lang.String" value="Hello JMX!"/>
                            >/parameter>
                          >/operation>
                        </mbean-invocation>
                    </payload>
                </message>
            </send>
        </actions>
    </testcase>
</spring:beans>
----

In the example above we access a custom managed bean and invoke its operation *sayHello* . We are also using operation parameters for the invocation. This should call the managed bean operation and return its result if any as usual.

This completes the basic JMX managed bean access as client. Now we also want to discuss the server side were Citrus is able to provide managed beans for others

[[jmx-server]]
== JMX server

The server side is always a little bit more tricky because we need to simulate custom managed bean access as a server. First of all Citrus provides a server component that specifies the connection properties for clients such as transport protocols, ports and mbean object names. Let's create a new server that accepts incoming requests via RMI on a remote registry *localhost:1099* .

[source,xml]
----
<citrus-jmx:server id="jmxServer"
      server-url="service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi">
    <citrus-jmx:mbeans>
        <citrus-jmx:mbean type="org.citrusframework.jmx.mbean.HelloBean"/>
        <citrus-jmx:mbean type="org.citrusframework.jmx.mbean.NewsBean" objectDomain="org.citrusframework.news" objectName="name=News"/>
    </citrus-jmx:mbeans>
</citrus-jmx:server>
----

As usual we define a *server-url* that controls the JMX connector access to the mbean server. In this example above we open a JMX RMI connector for clients using the registry *localhost:1099* and the service name *jmxrmi* By default Citrus will not attempt to create this registry automatically so the registry has to be present before the server start up. With the optional server property *create-registry* set to *true* you can auto create the registry when the server starts up. These properties do only apply when using a remote JMX connector server.

Besides using the whole server-url as property we can also construct the connection by host, port, protocol and binding properties.

[source,xml]
----
<citrus-jmx:server id="jmxServer"
      host="localhost"
      port="1099"
      protocol="rmi"
      binding="jmxrmi">
    <citrus-jmx:mbeans>
        <citrus-jmx:mbean type="org.citrusframework.jmx.mbean.HelloBean"/>
        <citrus-jmx:mbean type="org.citrusframework.jmx.mbean.NewsBean" objectDomain="org.citrusframework.news" objectName="name=News"/>
    </citrus-jmx:mbeans>
</citrus-jmx:server>
----

On last thing to mention is that we could have also used *platform* as server-url in order to use the JVM platform mbean server instead.

Now that we clarified the connectivity we need to talk about how to define the managed beans that are available on our JMX mbean server. This is done as nested *mbean* configuration elements. Here the managed bean definitions describe the managed bean with its objectDomain, objectName, operations and attributes. The most convenient way of defining such managed bean definitions is to give a bean type which is the fully qualified class name of the managed bean. Citrus will use the package name and class name for proper objectDomain and objectName construction.

Let's have a closer look at the first mbean definition in the example above. So the first managed bean is defined by its class name *org.citrusframework.jmx.mbean.HelloBean* and therefore is accessible using the objectName *org.citrusframework.jmx.mbean:type=HelloBean* . In addition to that Citrus will read the class information such as available methods, getters and setters for constructing a proper MBeanInfo. In the second managed bean definition in our example we have used additional custom objectDomain and objectName values. So the *NewsBean* will be accessible with *org.citrusframework.news:name=News* on the managed bean server.

This is how we can define the bindings of managed beans and what clients need to search for when finding and accessing the managed beans on the server. When clients try to find the managed beans they have to use proper objectNames accordingly. ObjectNames that are not defined on the server will be rejected with managed bean not found error.

Right now we have to use the qualified class name of the managed bean in the definition. What happens if we do not have access to that mbean class or if there is not managed bean interface available at all? Citrus provides a generic managed bean that is able to handle any managed bean interaction. The generic bean implementation needs to know the managed operations and attributes though. So let's define a new generic managed bean on our server:

[source,xml]
----
<citrus-jmx:server id="jmxServer"
server-url="service:jmx:rmi:///jndi/rmi://localhost:1099/jmxrmi">
    <citrus-jmx:mbeans>
        <citrus-jmx:mbean name="fooBean" objectDomain="foo.object.domain" objectName="type=FooBean">
            <citrus-jmx:operations>
                <citrus-jmx:operation name="fooOperation">
                    <citrus-jmx:parameter>
                        <citrus-jmx:param type="java.lang.String"/>
                        <citrus-jmx:param type="java.lang.Integer"/>
                    </citrus-jmx:parameter>
                </citrus-jmx:operation>
                <citrus-jmx:operation name="barOperation"/>
            </citrus-jmx:operations>
            <citrus-jmx:attributes>
                <citrus-jmx:attribute name="fooAttribute" type="java.lang.String"/>
                <citrus-jmx:attribute name="barAttribute" type="java.lang.Boolean"/>
            </citrus-jmx:attributes>
        </citrus-jmx:mbean>
    </citrus-jmx:mbeans>
</citrus-jmx:server>
----

The generic bean definition needs to define all operations and attributes that are available for access. Up to now we are restricted to using Java base types when defining operation parameter and attribute return types. There is actually no way to define more complex return types. Nevertheless Citrus is now able to expose the managed bean for client access without having to know the actual managed bean implementation.

Now we can use the server component in a test case to receive some incoming managed bean access.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void jmxMessageTest() {
    $(receive(jmxServer)
        .message(JmxMessage.invocation("org.citrusframework.jmx.mbean:type=HelloBean")
            .operation("sayHello")
            .parameter("Hello JMX!"))
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="JmxMessageTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <receive endpoint="jmxServer">
            <message>
                <body>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>org.citrusframework.jmx.mbean:type=HelloBean</mbean>
                          <operation name="sayHello">
                            >parameter>
                              >param type="java.lang.String" value="Hello JMX!"/>
                            >/parameter>
                          </operation>
                        </mbean-invocation>
                    </payload>
                </body>
            </message>
        </receive>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: JmxMessageTest
actions:
  - receive:
      endpoint: "jmxServer"
      message:
        body: |
          <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
              <mbean>org.citrusframework.jmx.mbean:type=HelloBean</mbean>
              <operation name="sayHello">
                >parameter>
                  >param type="java.lang.String" value="Hello JMX!"/>
                >/parameter>
              </operation>
          </mbean-invocation>
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="JmxMessageTest">
        <actions>
            <receive endpoint="jmxServer">
                <message>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>org.citrusframework.jmx.mbean:type=HelloBean</mbean>
                          <operation name="sayHello">
                            >parameter>
                              >param type="java.lang.String" value="Hello JMX!"/>
                            >/parameter>
                          </operation>
                        </mbean-invocation>
                    </payload>
                </message>
            </receive>
        </actions>
    </testcase>
</spring:beans>
----

In this very first example we expect a managed bean access to the bean *org.citrusframework.jmx.mbean:type=HelloBean* . We further expect the operation *sayHello* to be called with respective parameter values. Now we have to define the operation result that will be returned to the calling client as operation result.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void jmxMessageTest() {
    $(send(jmxServer)
        .message(JmxMessage.result("Hello from JMX!"))
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="JmxMessageTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <send endpoint="jmxServer">
            <message>
                <body>
                    <payload>
                        <mbean-result xmlns="http://www.citrusframework.org/schema/jmx/message">
                            <object type="java.lang.String" value="Hello from JMX!"/>
                        </mbean-result>
                    </payload>
                </body>
            </message>
        </send>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: JmxMessageTest
actions:
  - send:
      endpoint: "jmxServer"
      message:
        body: |
          <mbean-result xmlns="http://www.citrusframework.org/schema/jmx/message">
            <object type="java.lang.String" value="Hello from JMX!"/>
          </mbean-result>
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="JmxMessageTest">
        <actions>
            <send endpoint="jmxServer">
                <message>
                    <payload>
                        <mbean-result xmlns="http://www.citrusframework.org/schema/jmx/message">
                            <object type="java.lang.String" value="Hello from JMX!"/>
                        </mbean-result>
                    </payload>
                </message>
            </send>
        </actions>
    </testcase>
</spring:beans>
----

The operation returns a String *Hello from JMX!* . This is how we can expect operation calls on managed beans. Now we already have seen that managed beans also expose attributes. The next example is handling incoming attribute read access.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void jmxMessageTest() {
    $(receive(jmxServer)
        .message(JmxMessage.invocation("org.citrusframework.news:name=News")
            .attribute("newsCount"))
    );

    $(send(jmxServer)
        .message(JmxMessage.result(100))
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="JmxMessageTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
        <receive endpoint="jmxServer">
            <message>
                <body>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>org.citrusframework.news:name=News</mbean>
                            >attribute name="newsCount"/>
                        </mbean-invocation>
                    </payload>
                </body>
            </message>
        </receive>
        <send endpoint="jmxServer">
            <message>
                <body>
                    <payload>
                        <mbean-result xmlns="http://www.citrusframework.org/schema/jmx/message">
                            <object type="java.lang.Integer" value="100"/>
                        </mbean-result>
                    </payload>
                </body>
            </message>
        </send>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: JmxMessageTest
actions:
  - receive:
      endpoint: "jmxServer"
      message:
        body: |
          <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
              <mbean>org.citrusframework.news:name=News</mbean>
                >attribute name="newsCount"/>
          </mbean-invocation>
  - send:
      endpoint: "jmxServer"
      message:
        body: |
          <mbean-result xmlns="http://www.citrusframework.org/schema/jmx/message">
            <object type="java.lang.Integer" value="100"/>
          </mbean-result>
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans">
    <testcase name="JmxMessageTest">
        <actions>
            <receive endpoint="jmxServer">
                <message>
                    <payload>
                        <mbean-invocation xmlns="http://www.citrusframework.org/schema/jmx/message">
                          <mbean>org.citrusframework.news:name=News</mbean>
                            >attribute name="newsCount"/>
                        </mbean-invocation>
                    </payload>
                </message>
            </receive>

            <send endpoint="jmxServer">
                <message>
                    <payload>
                        <mbean-result xmlns="http://www.citrusframework.org/schema/jmx/message">
                            <object type="java.lang.Integer" value="100"/>
                        </mbean-result>
                    </payload>
                </message>
            </send>
        </actions>
    </testcase>
</spring:beans>
----

The receive action expects read access to the *NewsBean* attribute *newsCount* and returns a result object of type *java.lang.Integer* . This way we can expect all attribute access to our managed beans. Write operations will have an attribute value specified.

This completes the JMX server capabilities with managed bean access on operations and attributes.
