[[sftp]]
= SFTP/SCP support

With Citrus it is possible to start your own sftp server for accepting incoming client requests. You can also use Citrus as a SFTP client to send FTP commands. The next sections deal with SFTP connectivity.

NOTE: The SFTP components in Citrus are maintained in their own Maven module. So you should add the module as Maven dependency to your project accordingly.

[source,xml]
----
<dependency>
  <groupId>org.citrusframework</groupId>
  <artifactId>citrus-ftp</artifactId>
  <version>2.7.6</version>
</dependency>
----

As Citrus provides a customized SFTP configuration schema for the Spring application context configuration files we have to add name to the top level *beans* element. Simply include the sftp-config namespace in the configuration XML files as follows.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:citrus="http://www.citrusframework.org/schema/config"
    xmlns:citrus-sftp="http://www.citrusframework.org/schema/sftp/config"
    xsi:schemaLocation="
    http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.citrusframework.org/schema/config
    http://www.citrusframework.org/schema/config/citrus-config.xsd
    http://www.citrusframework.org/schema/http/config
    http://www.citrusframework.org/schema/sftp/config/citrus-sftp-config.xsd">

      [...]

      </beans>
----

Now we are ready to use the customized Citrus SFTP configuration elements with the citrus-sftp namespace prefix.

[[sftp-client]]
== SFTP client

We want to use Citrus to connect to some FTP server using secure file transfer and authentication. Citrus offers a client component doing exactly this SFTP client connection.

.XML
[source,xml]
----
<citrus-sftp:client id="sftpClient"
           strict-host-checking="false"
           port="2222"
           username="citrus"
           private-key-path="classpath:ssh/citrus.priv"
           timeout="10000"/>
----

.Java
[source, java]
----
@Bean
public SftpClient sftpClient() {
    return CitrusEndpoints.sftp()
            .client()
            .strictHostChecking(false)
            .port(2222)
            .username("citrus")
            .privateKeyPath("classpath:ssh/citrus.priv")
            .build();
}
----

The configuration above describes a Citrus sftp client. The sftp-client connects to the server using the user credentials
and/or the private key authentication. The client will automatically authenticate to the server when opening a new connection.
As the Citrus stfp client supports various authentication methods, the following order is default: `publickey,password,keyboard-interactive`.
You're able to configure the default order with the `preferred-authentications` attribute in XML or the
`preferredAuthentications` method in Java.

.XML
[source,xml]
----
<citrus-sftp:client id="sftpClient"
           strict-host-checking="false"
           port="2222"
           username="citrus"
           private-key-path="classpath:ssh/citrus.priv",
           preferred-authentications="publickey,password,gssapi-with-mic,keyboard-interactive"
           timeout="10000"/>
----

.Java
[source, java]
----
@Bean
public SftpClient sftpClient() {
    return CitrusEndpoints.sftp()
            .client()
            .strictHostChecking(false)
            .port(2222)
            .username("citrus")
            .privateKeyPath("classpath:ssh/citrus.priv")
            .preferredAuthentications("publickey,password,gssapi-with-mic,keyboard-interactive")
            .build();
}
----

[[sftp-client-commands]]
=== SFTP client commands

In a test case you are now able to use the client to push commands to the server.

.XML DSL
[source,xml]
----
<send endpoint="sftpClient">
  <message>
    <payload>
      <ftp:command>
        <ftp:signal>MKD</ftp:signal>
        <ftp:arguments>test</ftp:arguments>
      </ftp:command>
    </payload>
  </message>
</send>

<receive endpoint="sftpClient">
  <message>
    <payload>
      <ftp:command-result>
        <ftp:success>true</ftp:success>
        <ftp:reply-code>257</ftp:reply-code>
        <ftp:reply-string>257 Pathname created</ftp:reply-string>
      </ftp:command-result>
    </payload>
  </message>
</receive>
----

.Java DSL
[source,java]
----
send(sftpClient)
    .message(FtpMessage.command(FTPCmd.MKD).arguments("test"));

CommandResult result = new CommandResult();
result.setSuccess(true);
result.setReplyCode(String.valueOf(257));
result.setReplyString("257 Pathname created");

receive(sftpClient)
    .message(FtpMessage.result(result));
----

As you can see most of the sftp communication parameters are specified in a ftp command message. Citrus automatically converts those information to proper FTP commands and response messages.

[[sftp-client-store]]
=== Store files

The client is able to store files on the server using file transfer.

.XML DSL
[source,xml]
----
<send endpoint="sftpClient">
  <message>
    <payload>
      <ftp:put-command>
        <ftp:file path="test/hello.txt" type="ASCII"/>
        <ftp:target path="/test/hello.txt"/>
      </ftp:put-command>
    </payload>
  </message>
</send>

<receive endpoint="sftpClient">
  <message>
    <payload>
      <ftp:put-command-result>
        <ftp:success>true</ftp:success>
        <ftp:reply-code>226</ftp:reply-code>
        <ftp:reply-string>@contains('Transfer complete')@</ftp:reply-string>
      </ftp:put-command-result>
    </payload>
  </message>
</receive>
----

.Java DSL
[source,java]
----
send(sftpClient)
        .message(FtpMessage.put("test/hello.txt", DataType.ASCII).arguments(""));

PutCommandResult result = new PutCommandResult();
        result.setSuccess(true);
        result.setReplyCode(String.valueOf(226));
        result.setReplyString("@contains(Transfer complete)@");

receive(sftpClient)
        .message(FtpMessage.result(result));
----

The file store operation uses the put command as message payload when sending the file request. The file content is loaded from external file resource. You can choose the transfer type `ASCII` and `BINARY`.
When the file is stored on server side we receive a success result message with respective reply code and string for validation.

[[sftp-client-retrieve]]
=== Retrieve files

We are able to retrieve files from a SFTP server. We need to specify the target file path that we want to get on the server user home directory.

.XML DSL
[source,xml]
----
<send endpoint="sftpClient">
  <message>
    <payload>
      <ftp:get-command>
        <ftp:file path="test/hello.txt" type="ASCII"/>
        <ftp:target path="target/test/hello.txt"/>
      </ftp:get-command>
    </payload>
  </message>
</send>

<receive endpoint="sftpClient">
  <message>
    <payload>
      <ftp:get-command-result>
        <ftp:success>true</ftp:success>
        <ftp:reply-code>226</ftp:reply-code>
        <ftp:reply-string>@contains('Transfer complete')@</ftp:reply-string>
        <ftp:file path="target/test/hello.txt">
          <ftp:data>citrus:readFile('classpath:test/hello.txt')</ftp:data>
        </ftp:file>
      </ftp:get-command-result>
    </payload>
  </message>
</receive>
----

.Java DSL
[source,java]
----
send(sftpClient)
        .message(FtpMessage.get("test/hello.txt", "target/test/hello.txt", DataType.ASCII));

receive(sftpClient)
        .message(FtpMessage.result(getRetrieveFileCommandResult("target/test/hello.txt", new ClassPathResource("test/hello.txt"))));
----

[source,java]
----
private GetCommandResult getRetrieveFileCommandResult(String path, Resource content) throws IOException {
    GetCommandResult result = new GetCommandResult();
    result.setSuccess(true);
    result.setReplyCode(String.valueOf(226));
    result.setReplyString("@contains('Transfer complete')@");

    GetCommandResult.File entryResult = new GetCommandResult.File();
    entryResult.setPath(path);
    entryResult.setData(FileUtils.readToString(content));
    result.setFile(entryResult);

    return result;
}
----

When file transfer is complete we are able to verify the file content in a command result. The file content is provided as data string.

[[sftp-client-list]]
=== List files

Listing files on the server is possible with the list command.

.XML
[source,xml]
----
<send endpoint="sftpClient">
  <message>
    <payload>
      <ftp:list-command>
        <ftp:target path="test" />
      </ftp:list-command>
    </payload>
  </message>
</send>

<receive endpoint="sftpClient">
  <message>
    <payload>
      <ftp:list-command-result>
        <ftp:success>true</ftp:success>
        <ftp:reply-code>150</ftp:reply-code>
        <ftp:reply-string>List files complete</ftp:reply-string>
        <ftp:files>
          <ftp:file path="."/>
          <ftp:file path=".."/>
          <ftp:file path="hello.txt"/>
        </ftp:files>
      </ftp:list-command-result>
    </payload>
  </message>
</receive>
----

.Java
[source,java]
----
send(sftpClient)
        .message(FtpMessage.list("test"));

receive(sftpClient)
        .message(FtpMessage.result(getListCommandResult("hello.txt")));
----

[source,java]
----
private ListCommandResult getListCommandResult(String ... fileNames) {
    ListCommandResult result = new ListCommandResult();
    result.setSuccess(true);
    result.setReplyCode(String.valueOf(226));
    result.setReplyString("@contains('Closing data connection')@");

    ListCommandResult.Files.File currentDir = new ListCommandResult.Files.File();
    currentDir.setPath(".");
    expectedFiles.getFiles().add(currentDir);

    ListCommandResult.Files.File parentDir = new ListCommandResult.Files.File();
    parentDir.setPath("..");
    expectedFiles.getFiles().add(parentDir);

    ListCommandResult.Files expectedFiles = new ListCommandResult.Files();

    for (String fileName : fileNames) {
        ListCommandResult.Files.File entry = new ListCommandResult.Files.File();
        entry.setPath(fileName);
        expectedFiles.getFiles().add(entry);
    }

    result.setFiles(expectedFiles);

    return result;
}
----

Listing files results in a command result that gives us the list of files on the server directory. We are able to verify that list with respective file paths.

[[sftp-server]]
== SFTP server

Now that we are able to access SFTP as a client we might also want to simulate the server side. Therefore Citrus offers a server component that is listening on a port for incoming SFTP connections. The server has a default home directory on the local file system specified. But you can also define home directories per user. For now let us have a look at the server configuration component:

.XML
[source,xml]
----
<citrus-sftp:server id="sftpServer"
                   port="2222"
                   auto-start="true"
                   user="citrus"
                   password="admin"
                   allowed-key-path="classpath:ssh/citrus_pub.pem"/>
----

.Java
[source,java]
----
@Bean
public SftpServer sftpServer() {
    return CitrusEndpoints.sftp()
            .server()
            .port(2222)
            .autoStart(true)
            .user("citrus")
            .password("admin")
            .allowedKeyPath("classpath:ssh/citrus_pub.pem")
            .build();
}
----

The *sftpServer* is a small but fully qualified SFTP server implementation in Citrus. The server receives a `user` that defines the user account and its home directory. All commands
will be performed in this user home directory. You can set the user home directory using the `userHomePath` attribute on the server. By default this is a directory located in `${user.dir}/target/{serverName}/home/{user}`.

In case you want to setup some files in that directory in order to provide it to clients, please copy those files to that home directory prior to the test. The server adds the public key to the list of allowed keys.

The following listings show how to handle incoming commands representing different file operation such as store and retrieve. In the test we indicate the server response that we would link the server to respond with. Positive command results accept the client command and execute the command. As we have a fully qualified sftp server running the client can store, retrieve files and create and change directories.
All incoming commands result in a file system change in the user home directory. So stored files are stored in that working directory and retrieved files are read form that directory. In the test case we only receive the commands for validation purpose and to indicate server
success or failure response.

[[sftp-server-command]]
=== SFTP server commands

Now we would like to use the server in a test case. Each operation that arrives on the server is automatically forwarded to the test case for validation. This means that we can
verify any command on the server by using a normal receive action in our test.

.XML DSL
[source,xml]
----
<receive endpoint="sftpServer">
  <message>
    <payload>
      <ftp:command>
        <ftp:signal>MKD</ftp:signal>
        <ftp:arguments>/test</ftp:arguments>
      </ftp:command>
    </payload>
  </message>
</receive>

<send endpoint="sftpServer">
  <message>
    <payload>
      <ftp:command-result>
        <ftp:success>true</ftp:success>
      </ftp:command-result>
    </payload>
  </message>
</send>
----

.Java DSL
[source,java]
----
receive(sftpServer)
    .message(FtpMessage.command(FTPCmd.MKD).arguments("test"));

send(sftpServer)
    .message(FtpMessage.success());
----

The receive action uses the command signal and argument for validation. In the sample above we receive a `MKD` signal with argument `/test` which implies a create directory command. The server respectively the
test case is now able to simulate the response for this command. We respond with a success command result. Following from that the Citrus SFTP server implementation will create that directory in the user home directory
and respond to the client with a proper success message.

Of course you can also simulate error scenarios here. Just respond in the test with a negative command result.

[[sftp-server-store]]
=== Store files

Clients are able to store files on the server component. Each file store operation is executed in the user home directory when the command result is successful. In a test you can verify the `STOR` signal coming from the client.

.XML DSL
[source,xml]
----
<echo>
  <message>Store file on server</message>
</echo>

<receive endpoint="sftpServer">
  <message>
    <payload>
      <ftp:put-command>
        <ftp:signal>STOR</ftp:signal>
        <ftp:file path="@ignore@" type="ASCII"/>
        <ftp:target path="/test/hello.txt"/>
      </ftp:put-command>
    </payload>
  </message>
</receive>

<send endpoint="sftpServer">
  <message>
    <payload>
      <ftp:command-result>
        <ftp:success>true</ftp:success>
      </ftp:command-result>
    </payload>
  </message>
</send>
----

.Java DSL
[source,java]
----
receive(sftpServer)
        .message(put("@ignore@","/test/hello.txt", DataType.ASCII));

send(sftpServer)
        .message(FtpMessage.success());
----

After that you should find a new file in the user home directory with the given file path. The file transfer is automatically handled by the Citrus SFTP server component.

[[sftp-server-retrieve]]
=== Retrieve files

Clients should be able to get files from the server by using get/retrieve commands. In the request the client needs to give the target file path based on the user home directory.

.XML DSL
[source,xml]
----
<echo>
  <message>Retrieve file from server</message>
</echo>

<receive endpoint="sftpServer">
  <message>
    <payload>
      <ftp:get-command>
        <ftp:signal>RETR</ftp:signal>
        <ftp:file path="/test/hello.txt" type="ASCII"/>
        <ftp:target path="@ignore@"/>
      </ftp:get-command>
    </payload>
  </message>
</receive>

<send endpoint="sftpServer">
  <message>
    <payload>
      <ftp:command-result>
        <ftp:success>true</ftp:success>
      </ftp:command-result>
    </payload>
  </message>
</send>
----

.Java DSL
[source,java]
----
receive(sftpServer)
        .message(FtpMessage.get("/test/hello.txt", "@ignore@", DataType.ASCII));

send(sftpServer)
        .message(FtpMessage.success());
----

The file request is verified with proper signal and arguments. When the server command result is positive the Citrus SFTP server will transfer the file content to the calling client.

[[sftp-server-list]]
=== List files

When clients request for listing files on the server we get a list command on the server.

.XML DSL
[source,xml]
----
<receive endpoint="sftpServer">
  <message>
    <payload>
      <ftp:command>
        <ftp:signal>LIST</ftp:signal>
        <ftp:arguments>test</ftp:arguments>
      </ftp:command>
    </payload>
  </message>
</receive>

<send endpoint="sftpServer">
  <message>
    <payload>
      <ftp:command-result>
        <ftp:success>true</ftp:success>
      </ftp:command-result>
    </payload>
  </message>
</send>
----

.Java DSL
[source,java]
----
receive(sftpServer)
        .message(FtpMessage.command(FTPCmd.LIST).arguments("test"));

send(sftpServer)
        .message(FtpMessage.success());
----

As you can see the list command is verified with proper signal and arguments that specifies the target folder to list the files for. When the command result is positive the
SFTP server implementation will send back a proper list command result for that given directory in the user home directory.

[[scp-client]]
== SCP client

As Citrus provides a customized SCP configuration schema for the Spring application context configuration files we have to add name to the top level *beans* element. Simply include the scp-config namespace in the configuration XML files as follows.

[source,xml]
----
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:citrus="http://www.citrusframework.org/schema/config"
    xmlns:citrus-scp="http://www.citrusframework.org/schema/scp/config"
    xsi:schemaLocation="
    http://www.springframework.org/schema/beans
    http://www.springframework.org/schema/beans/spring-beans.xsd
    http://www.citrusframework.org/schema/config
    http://www.citrusframework.org/schema/config/citrus-config.xsd
    http://www.citrusframework.org/schema/http/config
    http://www.citrusframework.org/schema/scp/config/citrus-scp-config.xsd">

      [...]

      </beans>
----

Now we are ready to use the customized Citrus SCP configuration elements with the citrus-scp namespace prefix.

We want to use Citrus to connect to some FTP server using secure file copy with SCP. Citrus offers a client component doing exactly this SCP client connection.

.XML
[source,xml]
----
<citrus-scp:client id="scpClient"
               port="2222"
               username="citrus"
               password="admin"
               private-key-path="classpath:ssh/citrus.priv"/>
----

.Java
[source, java]
----
@Bean
public ScpClient scpClient() {
    return CitrusEndpoints.scp()
            .client()
            .port(2222)
            .username("citrus")
            .password("admin")
            .privateKeyPath("classpath:ssh/citrus.priv")
            .build();
}
----

The configuration above describes a Citrus scp client. The scp-client connects to the server using the user credentials and/or the private key authentication. The client will automatically authenticate to the server when opening a new connection.

[[scp-client-store]]
=== Store files

The client is able to store files on the server using file transfer.

.XML DSL
[source,xml]
----
<send endpoint="scpClient">
  <message>
    <payload>
      <ftp:put-command>
        <ftp:file path="test/hello.txt" type="ASCII"/>
        <ftp:target path="/test/hello.txt"/>
      </ftp:put-command>
    </payload>
  </message>
</send>

<receive endpoint="scpClient">
  <message>
    <payload>
      <ftp:put-command-result>
        <ftp:success>true</ftp:success>
        <ftp:reply-code>226</ftp:reply-code>
        <ftp:reply-string>@contains('Transfer complete')@</ftp:reply-string>
      </ftp:put-command-result>
    </payload>
  </message>
</receive>
----

.Java DSL
[source,java]
----
send(scpClient)
        .message(FtpMessage.put("test/hello.txt", DataType.ASCII).arguments(""));

PutCommandResult result = new PutCommandResult();
        result.setSuccess(true);
        result.setReplyCode(String.valueOf(226));
        result.setReplyString("@contains(Transfer complete)@");

receive(scpClient)
        .message(FtpMessage.result(result));
----

The file store operation uses the put command as message payload when sending the file request. The file content is loaded from external file resource. You can choose the transfer type `ASCII` and `BINARY`.
When the file is stored on server side we receive a success result message with respective reply code and string for validation.

[[scp-client-retrieve]]
=== Retrieve files

We are able to retrieve files from a SFTP server. We need to specify the target file path that we want to get on the server user home directory.

.XML DSL
[source,xml]
----
<send endpoint="scpClient">
  <message>
    <payload>
      <ftp:get-command>
        <ftp:file path="test/hello.txt" type="ASCII"/>
        <ftp:target path="target/test/hello.txt"/>
      </ftp:get-command>
    </payload>
  </message>
</send>

<receive endpoint="scpClient">
  <message>
    <payload>
      <ftp:get-command-result>
        <ftp:success>true</ftp:success>
        <ftp:reply-code>226</ftp:reply-code>
        <ftp:reply-string>@contains('Transfer complete')@</ftp:reply-string>
        <ftp:file path="target/test/hello.txt">
          <ftp:data>citrus:readFile('classpath:test/hello.txt')</ftp:data>
        </ftp:file>
      </ftp:get-command-result>
    </payload>
  </message>
</receive>
----

.Java DSL
[source,java]
----
send(scpClient)
        .message(FtpMessage.get("test/hello.txt", "target/test/hello.txt", DataType.ASCII));

receive(scpClient)
        .message(FtpMessage.result(getRetrieveFileCommandResult("target/test/hello.txt", new ClassPathResource("test/hello.txt"))));
----

[source,java]
----
private GetCommandResult getRetrieveFileCommandResult(String path, Resource content) throws IOException {
    GetCommandResult result = new GetCommandResult();
    result.setSuccess(true);
    result.setReplyCode(String.valueOf(226));
    result.setReplyString("@contains('Transfer complete')@");

    GetCommandResult.File entryResult = new GetCommandResult.File();
    entryResult.setPath(path);
    entryResult.setData(FileUtils.readToString(content));
    result.setFile(entryResult);

    return result;
}
----

When file transfer is complete we are able to verify the file content in a command result. The file content is provided as data string.

