[[preface]]
[[preface]]
= Preface

Integration tests are a critical part of software testing. In contrast to unit tests where the primary goal is to verify a
single class or method in isolation to other parts of the software the integration tests look at a wider scope with
several components and software parts interacting with each other.

Integration tests often rely on infrastructure components such as I/O, databases, 3rd party services and so on. In combination with
messaging and multiple message transports as client and/or server the automated tests become a tough challenge. Testers need sufficient
tool support to master this challenge for automated integration test. Citrus as an Open Source framework is here to help you master this
challenge.

In a typical enterprise application and middleware scenario automated integration testing of message-based interfaces is exhausting
and sometimes barely possible. Usually the tester is forced to simulate several interface partners in an end-to-end integration test.

The first thing that comes to one's mind is manual testing. No doubt manual testing is fast. In a long term perspective
manual testing is time-consuming and causes severe problems regarding maintainability as they are error prone and not repeatable.

Citrus provides a complete test automation tool for integration testing of message-based enterprise applications. You can test
your message interfaces (Http REST, SOAP, JMS, Kafka, TCP/IP, FTP, ...) to other applications as client and server.
Every time a code change is made all automated Citrus tests ensure the stability of software interfaces and its message communication.

Regression testing and continuous integration is very easy as Citrus fits into your build lifecycle (Maven or Gradle) as usual
Java unit test (JUnit, TestNG, Cucumber).

With powerful validation capabilities for various message formats like XML, CSV or JSON Citrus is ready to provide fully
automated integration tests for end-to-end use cases. Citrus effectively composes complex messaging use cases with response
generation, error simulation, database interaction and more.

This documentation provides a reference guide to all features of the Citrus test framework. It gives a detailed picture of
effective integration testing with automated integration test environments. Since this document is open, please do not
hesitate to give feedback in form of comments, change requests, fixes and pull requests. We are more than happy to continuously
improve this documentation with your help!
