[[run-java]]
= Running tests in Java

The Citrus test holds a sequence of test actions. Each action represents a very special purpose such as sending or
receiving a message.

Despite the fact that message exchange is one of the main actions in an integration test framework for message-based applications
Citrus is more than just that. Each test case in Citrus is able to perform various actions such as connecting to the database,
transforming data, adding iterations and conditional steps.

With the default Citrus actions provided out of the box users can accomplish very complex use cases in integration testing.
In Citrus you can configure and add test actions in Java using a test action runner API that leverages a fluent builder pattern API.

[[java-test-runner]]
== Test action runner

The test action runner is the entry to the fluent Java API. You can configure test actions with a fluent builder style API and
immediately run the actions with the runner.

See the following example to see the Java domain specific language in action.

.Test action runner
[source,java]
----
import org.testng.annotations.Test;
import org.citrusframework.annotations.CitrusTest;
import org.citrusframework.dsl.testng.TestNGCitrusSupport;

@Test
public class Service_IT extends TestNGCitrusSupport {

    @CitrusTest(name = "Service_IT")
    public void serviceTest() {
        run(echo("Before service call"));

        run(echo("After service call"));
    }
}
----

The test action runner executes each test action immediately as you use the provided `run()` method. All actions provided in Citrus
represent a certain functionality (e.g. send/receive messages, delay the test, access a database). Citrus ships with a wide range of
link:#actions[test actions], but you are also able to write your own test actions and execute them during a test.

By default, all actions run sequentially in the same order as they are defined in the test case. In case one single action fails
the whole test case is failing. Of course, you can leverage parallel action execution with the usage of link:#containers[test containers].

IMPORTANT: The *TestNGCitrusSupport* and *JUnit4CitrusSupport* base classes are not thread safe by default. This is simply
because the base class is holding state to the current test action runner instance in order to delegate method calls
to this instance. Parallel test execution is not available with this approach. Fortunately there is a way to support parallel
test execution through resource injection. Read more about this in link:#junit4-parallel[JUnit4] or link:#junit4-parallel[TestNG]
support.

[[java-test-runner-gherkin]]
== Gherkin test action runner

The test action runner is also available as Gherkin style runner with `given()`, `when()`, `then()` methods. The Gherkin test action runner
follows the Behavior Driven Development concepts of structuring the test into the three parts: *Given* a certain context, *when* an event
occurs, *then* an outcome should be verified.

.Gherkin test action runner
[source,java]
----
@Test
public class Service_IT extends TestNGCitrusSupport {

    @CitrusTest(name = "Service_IT")
    public void serviceTest() {
        given(
            echo("Setup the context")
        );

        when(
            echo("Trigger the event")
        );

        then(
            echo("Verify the outcome")
        );
    }
}
----

[[java-test-meta-information]]
== Test meta information

The user is able to provide some additional information about the test case. The meta-info section at the very beginning of the
test case holds information like author, status or creation date.

.Test meta information
[source,java]
----
@CitrusTest
public void sampleTest() {
    description("This is a Test");
    author("Christoph");
    status(Status.FINAL);

    run(echo("Hello Citrus!"));
}
----

The status allows the following values:

* DRAFT
* READY_FOR_REVIEW
* DISABLED
* FINAL

This information gives the reader first impression about the test and is also used to generate test documentation. By default,
Citrus is able to generate test reports in HTML and Excel in order to list all tests with their metadata information and description.

NOTE: Tests with the status DISABLED will not be executed during a test suite run. So someone can just start adding planned
test cases that are not finished yet in status DRAFT. In case a test is not runnable yet because it is not finished, someone
may disable a test temporarily to avoid causing failures during a test run.

The test description should give a short introduction to the intended use case scenario that will be tested. The user should get
a short summary of what the test case is trying to verify.

[[java-test-finally]]
== Finally block

Java developers might be familiar with the concept of try-catch-finally blocks. The *_finally_* section contains a list of
test actions that will be executed guaranteed at the very end of the test case even if errors did occur during the execution before.

This is the right place to tidy up things that were previously created by the test like cleaning up the database for instance.

.Finally block
[source,java]
----
@CitrusTest
public void sampleTest() {
    given(
        doFinally()
            .actions(echo("Do finally - regardless of any error before"))
    );

    echo("Hello Test Framework");
}
----

As an example imagine that you have prepared some data inside the database at the beginning of the test and you need to make
sure the data is cleaned up at the end of the test case.

.Finally block example
[source,java]
----
@CitrusTest
public void finallyBlockTest() {
    variable("orderId", "citrus:randomNumber(5)");
    variable("date", "citrus:currentDate('dd.MM.yyyy')");

    given(
        doFinally()
            .actions(sql(dataSource).statement("DELETE FROM ORDERS WHERE ORDER_ID='${orderId}'"))
    );

    when(
        sql(dataSource).statement("INSERT INTO ORDERS VALUES (${orderId}, 1, 1, '${date}')")
    );

    then(
        echo("ORDER creation time: citrus:currentDate('dd.MM.yyyy')")
    );
}
----

In the example the first action creates an entry in the database using an *_INSERT_* statement. To be sure that the entry
in the database is deleted after the test, the finally section contains the respective *_DELETE_* statement that is always
executed regardless the test case state (successful or failed).

NOTE: The finally section must be placed at the very beginning of the test. This is because the test action runner
is immediately executing each test action as it is called within the Java DSL methods. This is the only way the test case
can perform the final actions also in case of previous error.

A finally block placed at the very end of the test will not take action unless put in a traditional Java try-finally-block:

.Traditional try-finally block
[source,java]
----
@CitrusTest
public void finallyBlockTest() {
    variable("orderId", "citrus:randomNumber(5)");
    variable("date", "citrus:currentDate('dd.MM.yyyy')");

    try {
        when(
            sql(dataSource).statement("INSERT INTO ORDERS VALUES (${orderId}, 1, 1, '${date}')")
        );

        then(
            echo("ORDER creation time: citrus:currentDate('dd.MM.yyyy')")
        );
    } finally {
        then(
            sql(dataSource).statement("DELETE FROM ORDERS WHERE ORDER_ID='${orderId}'")
        );
    }
}
----

Using the traditional Java `try-finally` feels more natural no doubt. Please notice that the Citrus report and logging will
not account the traditional finally block actions then. Good news is whatever layout you choose the outcome is always the same.

The finally block is executed safely even in case some previous test action raises an error for some reason.

[[java-test-behaviors]]
== Test behaviors

The concept of test behaviors is a good way to reuse test action blocks in the Java DSL. Test behaviors combine action
sequences to a logical unit. The behavior defines a set of test actions that can be applied multiple times to different
test cases.

The behavior is a separate Java DSL class with a single _apply_ method that configures the test actions. Test behaviors
follow this basic interface:

.Test behaviors
[source,java]
----
@FunctionalInterface
public interface TestBehavior {

    /**
     * Behavior building method.
     */
    void apply(TestActionRunner runner);

}
----

The behavior is provided with the test action runner and all actions in the behavior should run on that runner. Every time
the behavior is applied to a test the actions get executed accordingly.

.Test behaviors
[source,java]
----
public class FooBehavior implements TestBehavior {
    public void apply(TestActionRunner runner) {
        runner.run(createVariable("foo", "test"));

        runner.run(echo("fooBehavior"));
    }
}

public class BarBehavior implements TestBehavior {
    public void apply(TestActionRunner runner) {
        runner.run(createVariable("bar", "test"));

        runner.run(echo("barBehavior"));
    }
}
----

The listing above shows two test behaviors that add very specific test actions and test variables to the test case. As
you can see the test behavior is able to use the same Java DSL action methods and defines test variables and actions as
a normal test case would do. You can apply the behaviors multiple times in different tests:

[source,java]
----
@CitrusTest
public void behaviorTest() {
    run(apply(new FooBehavior()));

    run(echo("Successfully applied bar behavior"));

    run(apply(new BarBehavior()));

    run(echo("Successfully applied bar behavior"));
}
----

The behavior is applied to the test case by calling the *apply()* method. As a result the behavior is executed adding
its logic at this point of the test execution. The same behavior can now be called in multiple test cases so we have a reusable
set of test actions.

A behavior may use different variable names than the test and vice versa. No doubt the behavior will fail as soon as special
variables with respective values are not present. Unknown variables cause the behavior and the whole test to fail with errors.

So a good approach would be to harmonize variable usage across behaviors and test cases, so that templates and test cases
do use the same variable naming. The behavior automatically knows all variables in the test case and all test variables
created inside the behavior are visible to the test case after applying.

IMPORTANT: When a behavior changes variables this will automatically affect the variables in the whole test. So if you
change a variable value inside a behavior and the variable is defined inside the test case the changes will affect
the variable in a global test context. This means we have to be careful when executing a behavior several times in a test,
especially in combination with parallel containers (see link:#containers-parallel[containers-parallel]).


[[java-custom-actions]]
== Run custom code

In general, you are able to mix Citrus Java DSL actions with custom Java code as you like.

.Run custom code
[source,java]
----
import org.testng.annotations.Test;
import org.citrusframework.annotations.CitrusTest;
import org.citrusframework.dsl.testng.TestNGCitrusSupport;

@Test
public class Service_IT extends TestNGCitrusSupport {

    private MyService myService = new MyService();

    @CitrusTest(name = "Service_IT")
    public void serviceTest() {
        run(echo("Before service call"));

        myService.doSomething("Now calling custom service");

        run(echo("After service call"));
    }
}
----

The test above uses a mix of Citrus test actions and custom service calls. The test logic will execute as expected. It is
recommended though to wrap custom code in a test action in order to have a consistent test reporting and failure management
in Citrus.

.Test action wrapper
[source,java]
----
import org.testng.annotations.Test;
import org.citrusframework.annotations.CitrusTest;
import org.citrusframework.dsl.testng.TestNGCitrusSupport;

@Test
public class Service_IT extends TestNGCitrusSupport {

    private MyService myService = new MyService();

    @CitrusTest(name = "Service_IT")
    public void serviceTest() {
        run(echo("Before service call"));

        run(
            action(context -> {
                myService.doSomething("Now calling custom service");
            })
        );

        run(echo("After service call"));
    }
}
----

The sample above wraps the call to the custom service `myService` in an abstract test action represented as Java lambda expression.
This way the service call becomes part of the Citrus test execution and failures are reported properly. Also you have access to the
current test context which holds the list of test variables as well as many other Citrus related test objects (e.g. message store).

This is why you should wrap custom code in a test action and run that code via the test action runner methods. You can also put your custom code in
a test action implementation and reference the logic from multiple tests.

[[java-bind-to-registry]]
== Bind objects to registry

The Citrus context is a place where objects can register themselves in order to enable dependency injection and instance sharing
in multiple tests. Once you register the object in the context others can resolve the reference with its given name.

In a simple example the context can register a new endpoint that is injected in several tests.

You can access the Citrus context within the provided before/after methods on the test.

.Register endpoint in Citrus context
[source,java]
----
public class CitrusRegisterEndpoint_IT extends TestNGCitrusSupport {

    @Override
    public void beforeSuite(CitrusContext context) {
        context.bind("foo", new FooEndpoint());
    }
}
----

With the CitrusContext you can bind objects to the registry. Each binding receives a name so others can resolve the instance
reference for injection.

.Inject endpoint in other tests
[source,java]
----
public class InjectEndpoint_IT extends TestNGCitrusSupport {

    @CitrusEndpoint
    private FooEndpoint foo;

    @Test
    @CitrusTest
    public void injectEndpointTest() {
        $(send(foo)
                .message()
                .body("Hello foo!"));

        $(receive(foo)
                .message()
                .body("Hello Citrus!"));
    }
}
----

The `@CitrusEndpoint` annotation injects the endpoint resolving the instance with the given name `foo`.
Test methods can use this endpoint in the following send and receive actions.

[[java-bind-to-registry-annotation]]
=== @BindToRegistry

An alternative to using the `bind()` method on the CitrusContext is to use the `@BindToRegistry` annotation.
Methods and fields annotated will automatically register in the CitrusContext registry.

.@BindToRegistry annotation
[source,java]
----
public class CitrusRegisterEndpoint_IT extends TestNGCitrusSupport {

    @CitrusFramework
    private Citrus citrus;

    @BindToRegistry(name = "fooQueue")
    private MessageQueue queue = new DefaultMessageQueue("fooQueue");

    @BindToRegistry
    public FooEndpoint foo() {
        return new FooEndpoint();
    }
}
----

The annotation is able to specify an explicit binding name.
The annotation works with public methods and fields in tests.

[[java-configuration-class]]
=== Configuration classes

As an alternative to adding the registry binding configuration directly to the test you can load configuration classes.

Configuration classes are automatically loaded before a test suite run and all methods and fields are parsed for potential bindings.
You can use the environment settings `citrus.java.config` and/or `CITRUS_JAVA_CONFIG` to set a default configuration class.

.citrus-application.properties
[source,properties]
----
citrus.java.config=MyConfig.class
----

.MyConfig.class
[source,java]
----
public class MyConfig {

    @BindToRegistry(name = "fooQueue")
    private MessageQueue queue = new DefaultMessageQueue("fooQueue");

    @BindToRegistry
    public void foo() {
        return new FooEndpoint();
    }
}
----

[[java-configuration-class-annotation]]
=== @CitrusConfiguration

Each test is able to use the `@CitrusConfiguration` annotation to add registry bindings, too.

.@CitrusConfiguration annotation
[source,java]
----
@CitrusConfiguration(classes = MyConfig.class)
public class CitrusRegisterEndpoint_IT extends TestNGCitrusSupport {

    @CitrusEndpoint
    private FooEndpoint foo;

    @Test
    @CitrusTest
    public void injectEndpointTest() {
        $(send(foo)
                .message()
                .body("Hello foo!"));

        $(receive(foo)
                .message()
                .body("Hello Citrus!"));
    }
}
----

The `@CitrusConfiguration` annotation is able to load configuration classes and bind all components to the registry for later usage.
The test can inject endpoints and other components using the `@CitrusEndpoint` and `@CitrusResource` annotation on fields.

[[java-resource-injection]]
== Resource injection

Resource injection is a convenient mechanism to access Citrus internal objects such as TestRunner or TestContext instances. The following sections
deal with resource injection of different objects.

[[java-resource-injection-citrus]]
=== Inject Citrus framework

You can access the Citrus framework instance in order to access all components and functionalities. Just use the `@CitrusFramework`
annotation in your test class.

.Citrus framework injection
[source,java]
----
public class CitrusInjection_IT extends TestNGCitrusSupport {

    @CitrusFramework
    private Citrus citrus;

    @Test
    @CitrusTest
    public void injectCitrusTest() {
        citrus.getCitrusContext().getMessageListeners().addMessageListener(new MyListener());
    }
}
----

The framework instance provides access to the Citrus context which is a central registry for all components. The example above adds
a new message listener.

IMPORTANT: The Citrus context is a shared component. Components added will perform with all further tests and changes made
affect all tests.

[[java-resource-injection-runner]]
=== Test action runner injection

The test action runner is the entry to the fluent Java API. You can inject the runner as a method parameter.

.Test action runner injection
[source,java]
----
public class RunnerInjection_IT extends JUnit4CitrusSupport {

    @Test
    @CitrusTest
    public void injectResources(@CitrusResource TestCaseRunner runner) {

        runner.given(
            createVariable("random", "citrus:randomNumber(10)")
        );

        runner.run(
            echo("The random number is: ${random}")
        );
    }
}
----

The parameter requires the `@CitrusResource` annotations in order to mark the parameter for Citrus resource injection.

Now each method uses its own runner instance which makes sure that parallel test execution can take place without having
the risk of side effects on other tests running at the same time.

[[java-resource-injection-test-context]]
=== Test context injection

The Citrus test context combines a set of central objects and functionalities that a test is able to make use of. The test context
holds all variables and is able to resolve functions and validation matchers.

In general a tester will not have to explicitly access the test context because the framework is working with it behind the scenes.
In terms of advanced operations and customizations accessing the test context may be a good idea though.

Each test action implementation has access to the test context as it is provided to the execution method in the interface:

.Test action interface
[source,java]
----
@FunctionalInterface
public interface TestAction {
    /**
     * Main execution method doing all work
     * @param context
     */
    void execute(TestContext context);
}
----

In addition Citrus provides a resource injection mechanism that allows to access the current test context in a test class or test method.

.Inject as method parameter
[source,java]
----
public class TestContextInjection_IT extends JUnit4CitrusSupport {

    @Test
    @CitrusTest
    public void resourceInjectionIT(@CitrusResource TestContext context) {
        context.setVariable("myVariable", "some value");

        run(echo("${myVariable}"));
    }
}
----

As you can see the test method defines a parameter of type *org.citrusframework.context.TestContext*. The annotation *@CitrusResource*
tells Citrus to inject this parameter with the according instance of the context for this test.

Now you have access to the context and all its capabilities such as variable management. As an alternative you can inject
the test context as a class member variable.

.Inject as member
[source,java]
----
public class TestContextInjection_IT extends JUnit4CitrusSupport {

    @CitrusResource
    private TestContext context;

    @Test
    @CitrusTest
    public void resourceInjectionIT() {
        context.setVariable("myVariable", "some value");

        run(echo("${myVariable}"));
    }
}
----

[[java-resource-injection-endpoint]]
=== Endpoint injection

Endpoints play a significant role when sending/receiving messages over various transports. An endpoint defines how to connect
to a message transport (e.g. Http endpoint URL, JMS message broker connection, Kafka connection and topic selection).

Endpoints can live inside the Citrus context (e.g. in Spring application context) or you can inject the endpoint into the test class
with given configuration.

.Endpoint injection
[source,java]
----
public class EndpointInjectionJavaIT extends TestNGCitrusSpringSupport {

    @CitrusEndpoint
    @DirectEndpointConfig(queueName = "FOO.test.queue")
    private Endpoint directEndpoint;

    @Test
    @CitrusTest
    public void injectEndpoint() {
        run(send(directEndpoint)
                .message()
                .type(MessageType.PLAINTEXT)
                .body("Hello!"));

        run(receive(directEndpoint)
                .message()
                    .type(MessageType.PLAINTEXT)
                    .body("Hello!"));
    }
}
----

The sample above creates a new endpoint as a direct in-memory channel endpoint. Citrus reads the `@CitrusEndpoint` annotation and
adds the configuration as given in the `@DirectEndpointConfig` annotation. This way you can create and inject endpoints directly to
your test.

TIP: Citrus also supports the Spring framework as a central bean registry. You can add endpoints as Spring beans and use the
`@Autowired` annotation to inject the endpoint in your test.
