[[run-xml-tests]]
== XML

As an alternative to coding tests in a programming language you can specify the test logic in XML only, too.
The XML language gives you some XSD schema and a set of elements that you can choose from to specify test actions.

As usual, you need to choose one of the supported test engines in Citrus to actually run the test (e.g. link:#runtime-junit5[JUnit Jupiter] or link:#runtime-testng[TestNG]).
You can then use the `@CitrusTestSource` annotation to load the XML file that represents the test case.

.MyFirstXmlIT.java
[source,java]
----
package org.citrusframework;

import org.citrusframework.annotations.CitrusTestSource;
import org.citrusframework.testng.TestNGCitrusSupport;
import org.testng.annotations.Test;

public class MyFirstXmlIT extends TestNGCitrusSpringSupport {

    @Test
    @CitrusTestSource(type = "xml", name="my-test.xml")
    public void myFirstXmlIT() {
    }
}
----

The test logic itself is defined in the XML file like this:

.my-test.xml
[source,xml]
----
<test name="EchoTest" author="Christoph" status="FINAL"
      xmlns="http://citrusframework.org/schema/xml/testcase"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://citrusframework.org/schema/xml/testcase
      http://citrusframework.org/schema/xml/testcase/citrus-testcase.xsd">
  <description>Sample test in XML</description>

  <variables>
    <variable name="text" value="Hello from Citrus!"/>
  </variables>

  <actions>
    <echo message="${text}"/>
  </actions>
</test>
----

[[run-xml-groovy-configuration]]
=== Configuration scripts

The XML test is able to create endpoints and other configuration entities as part of the test.
The test leverages the Groovy programming language that provides a comfortable way to define beans in the Citrus registry.
You can set any of the supported properties on the configuration components.

.my-test.xml
[source,xml]
----
<test name="EchoTest" author="Christoph" status="FINAL"
      xmlns="http://citrusframework.org/schema/xml/testcase"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://citrusframework.org/schema/xml/testcase
      http://citrusframework.org/schema/xml/testcase/citrus-testcase.xsd">
  <description>Sample test in XML</description>

  <variables>
    <variable name="text" value="Hello from Citrus!"/>
  </variables>

  <actions>
    <groovy>
      <endpoints>
        <script>
        configuration {
            queues {
                queue('say-hello')
            }

            endpoints {
                direct('hello')
                    .asynchronous()
                    .queue('say-hello')
            }
        }
        </script>
      </endpoints>
    </groovy>

    <send endpoint="hello">
      <message>
        <body>
          <data>Hello Citrus!</data>
        </body>
      </message>
    </send>
  </actions>
</test>
----

The test above creates a new `direct` endpoint called `hello` that uses an im-memory queue `say-hello`.
The send action is able to reference the endpoint by its name to send a message body to the queue.

[[run-xml-templates]]
=== Templates

Templates group action sequences to a logical unit.
You can think of templates as reusable components that are used in several tests.
The maintenance is much more efficient because you need to apply changes only on the templates and all referenced use cases are updated automatically.

The template gets identified by a unique name.
Inside a test case we apply the template referencing this unique name.
Have a look at a first example:

.echo-template.xml
[source,xml]
----
<template name="echo">
  <description>Sample template in XML</description>
  <parameters>
    <parameter name="message" value="Citrus rocks!"/>
  </parameters>

  <actions>
    <echo message="${message}"/>
  </actions>
</template>
----

The code example above describes a template called `echo`.
Templates hold a sequence of test actions or calls other templates themselves.
The template may define a set of parameters that represent customizable user input when applying the template.

The template is available for multiple tests that may apply the template as part of their test action sequence.

.Apply templates
[source,xml]
----
<test name="ApplyTemplateTest" author="Christoph" status="FINAL"
      xmlns="http://citrusframework.org/schema/xml/testcase"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://citrusframework.org/schema/xml/testcase
      http://citrusframework.org/schema/xml/testcase/citrus-testcase.xsd">
  <description>Sample test in XML</description>

  <actions>
    <apply-template name="echo"/>

    <apply-template name="echo">
      <parameters>
        <parameter name="message" value="Hello from Citrus!"/>
      </parameters>
    </apply-template>
  </actions>
</test>
----

The example references the `echo` template and call it as part of the test with `<apply-template/>`.
You can customize the template parameter to overwrite the default variable `text` with a custom value.

The example above assumes that you have added the template to the Citrus bean registry with the name `echo`.
If this is not the case you may also reference the file resource path when applying the template:

.Apply templates
[source,xml]
----
<test name="ApplyTemplateTest" author="Christoph" status="FINAL"
      xmlns="http://citrusframework.org/schema/xml/testcase"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://citrusframework.org/schema/xml/testcase
      http://citrusframework.org/schema/xml/testcase/citrus-testcase.xsd">
  <description>Sample test in XML</description>

  <actions>
    <apply-template file="classpath:templates/xml/echo-template.xml">
      <parameters>
        <parameter name="message" value="Hello from Citrus!"/>
      </parameters>
    </apply-template>
  </actions>
</test>
----

[[run-xml-template-parameters]]
==== Template parameters

How to handle test variables when dealing with templates, in particular when templates are defined in separate source files?
A template may use different variable names compared to those names used a test and vice versa.
The template fails immediately when respective variables are not present.
Therefore, templates introduce the concept of parameters to declare its variable names.

Assume you have the following template:

.sayHello template
[source,xml]
----
<template name="sayHello">
  <description>Sample template in XML</description>
  <parameters>
    <parameter name="user" value="Citrus"/>
  </parameters>

  <actions>
    <echo message="Hello ${user}!"/>
  </actions>
</template>
----

The template `sayHello` in the example uses the variable `${user}`.

In case the test case already uses the template parameter as a value you do not need to set this variable explicitly on the apply template action.

.Implicit template parameter
[source,xml]
----
<test name="SayHelloTemplateTest" author="Christoph" status="FINAL"
      xmlns="http://citrusframework.org/schema/xml/testcase"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://citrusframework.org/schema/xml/testcase
      http://citrusframework.org/schema/xml/testcase/citrus-testcase.xsd">
  <description>Sample test in XML</description>

  <variables>
    <variable name="user" value="Christoph"/>
  </variables>

  <actions>
    <apply-template name="sayHello"/>
  </actions>
</test>
----

.Output
[source,text]
----
Hello Christoph!
----

NOTE: The implicit template parameter may break as soon as the template or the test changes its parameter or variable name.

The test case may also explicitly set the template parameter when applying the template:

.Explicit template parameter
[source,xml]
----
<test name="SayHelloTemplateTest" author="Christoph" status="FINAL"
      xmlns="http://citrusframework.org/schema/xml/testcase"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://citrusframework.org/schema/xml/testcase
      http://citrusframework.org/schema/xml/testcase/citrus-testcase.xsd">
  <description>Sample test in XML</description>

  <variables>
    <variable name="username" value="Mickey"/>
  </variables>

  <actions>
    <apply-template name="sayHello">
      <parameters>
        <parameter name="user" value="${username}"/>
      </parameters>
    </apply-template>
  </actions>
</test>
----

.Output
[source,text]
----
Hello Mickey!
----

The variable *username* is already present in the test case and gets translated into the *user* parameter.
Following from that the template works fine although test and template do work on different variable names.

With template parameters you are able to solve the calibration effort when working with templates and variables.
It is always a good idea to check the used variables/parameters inside a template when calling it.
There might be a variable that is not declared yet inside your test.
So you need to define this value as a parameter.

[[run-xml-template-paremeter-scope]]
==== Template parameter scope

A template is able to change a test variable value for the rest of the test case.
It is important to know about this when changing test variables in a template as it affects the descendant test actions.
Especially when running test actions or templates in parallel to each other this might lead to unexpected behavior.
You may choose the template parameter scope for this scenario.

IMPORTANT: When a template works on variable values and parameters changes to these variables will automatically affect the
variables in the whole test. So if you change a variable's value inside a template and the variable is defined inside the
test case the changes will affect the variable in a global context. We have to be careful with this when executing a template
several times in a test, especially in combination with parallel containers (see link:#containers-parallel[containers-parallel]).

.print template
[source,xml]
----
<template name="print">
  <description>Sample template in XML</description>
  <parameters>
    <parameter name="index" value="0"/>
    <parameter name="area" value="Atlantis"/>
  </parameters>

  <actions>
    <echo message="#${index} Hello ${area}!"/>
  </actions>
</template>
----

.Global scope parameter (default)
[source,xml]
----
<test name="SayHelloTemplateTest" author="Christoph" status="FINAL"
      xmlns="http://citrusframework.org/schema/xml/testcase"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://citrusframework.org/schema/xml/testcase
      http://citrusframework.org/schema/xml/testcase/citrus-testcase.xsd">
  <description>Sample test in XML</description>

  <actions>
    <parallel>
      <actions>
        <apply-template name="print">
          <parameters>
            <parameter name="index" value="1"/>
            <parameter name="area" value="Europe"/>
          </parameters>
        </apply-template>
        <apply-template name="print">
          <parameters>
            <parameter name="index" value="2"/>
            <parameter name="area" value="Asia"/>
          </parameters>
        </apply-template>
        <apply-template name="print">
          <parameters>
            <parameter name="index" value="3"/>
            <parameter name="area" value="Africa"/>
          </parameters>
        </apply-template>
      </actions>
    </parallel>
  </actions>
</test>
----

In the listing above a template *print* is called several times in a parallel container.
The parameter values will be handled in a global context, so it is quite likely to happen that the template instances influence each other during execution.
We might get such print messages:

.Output
[source,text]
----
#2 Hello Europe!
#2 Hello Africa!
#3 Hello Africa!
----

Index parameters do not fit and the message *'Hello Asia'* is completely gone.
This is because templates overwrite parameters to each other as they are executed in parallel at the same time.
To avoid this behavior we need to tell the template that it should handle parameters as well as variables in a local context.
This will enforce that each template instance is working on a dedicated local context.
See the *global-context* attribute that is set to *false* in this example:

.print template
[source,xml]
----
<template name="print" global-context="false">
  <description>Sample template in XML</description>
  <parameters>
    <parameter name="index" value="0"/>
    <parameter name="area" value="Atlantis"/>
  </parameters>

  <actions>
    <echo message="#${index} Hello ${area}!"/>
  </actions>
</template>
----

After that template instances will not influence each other anymore.
But notice that variable changes inside the template then do not affect the test case neither.
