[[runtimes]]
= Runtimes

A Citrus test case is nothing but Java unit test leveraging well-known standard tools such as https://junit.org[JUnit],
https://testng.org[TestNG] or https://cucumber.io[Cucumber] as a runtime.

Chances are very high that Java developers are familiar with at least one of the standard tools. Everything you can do
with JUnit and TestNG you can do with Citrus tests as well (e.g. Maven build integration, run tests from your favorite IDE,
include tests into a continuous build tool).

NOTE: Why is Citrus related to unit test frameworks although it represents a framework for integration testing? The answer to this question is quite simple: This is because Citrus wants to benefit from standard libraries such as JUnit
and TestNG for Java test execution. Both unit testing frameworks offer various ways of execution and are widely supported
by other tools (e.g. continuous build, build lifecycle, development IDE).

You can write the Citrus test code in a Java domain specific language or in form of an link:#run-xml-tests[XML test]
declaration file that gets loaded as part of the test. The Java domain specific language in Citrus is a set of classes
and methods to leverage the test code in form of a fluent API. Users can simply configure a test action with the different
options using a fluent builder pattern style DSL.

.Citrus Java DSL
[source,java]
----
@CitrusTest(name = "Hello_IT")
public void helloTest() {
    given(
        variable("user", "Citrus")
    );

    then(
        echo().message("Hello ${user}!"
    ));
}
----

The sample above is a very simple Citrus test that creates a test variable and prints a message to the console. The Java DSL you write
is the same for all runtimes (JUnit, TestNG, Cucumber, etc.) and should help you to also solve very complex test scenarios.

The following sections have a closer look at the different runtimes for Citrus.

include::runtimes-testng.adoc[]
include::runtimes-junit5.adoc[]
include::runtimes-junit4.adoc[]
include::runtimes-cucumber.adoc[]
include::runtimes-quarkus.adoc[]
include::runtimes-main.adoc[]
include::runtimes-sharded.adoc[]
