[[setup]]
= Setup

This chapter discusses how to get started with Citrus. It deals with the installation and set up of the framework, so you
are ready to start writing test cases after reading this chapter.

Usually you add Citrus as a test-scoped dependency library in your project. Build tools like Maven or Gradle provide standard
integration for test libraries such as Citrus. As Citrus tests are nothing but normal unit tests (JUnit, TestNG, Cucumber)
you can run the tests with the standard unit test build integration (e.g. via maven-failsafe plugin).

This chapter describes the Citrus project setup possibilities, choose one of them that fits best to include Citrus into your project.

[[setup-maven]]
== Using Maven

Citrus uses link:https://maven.apache.org/[Maven] internally as a project build tool and provides extended support for Maven projects.
Maven will ease up your life as it manages project dependencies and provides extended build life cycles and conventions for
compiling, testing, packaging and installing your Java project.

In case you already use Maven in your project you can just add Citrus as a test-scoped dependency.

As Maven handles all project dependencies automatically you do not need to download any Citrus project artifacts in advance.
If you are new to Maven please refer to the official Maven documentation and find out how to https://maven.apache.org/[set up a Maven project].

Assuming you have a proper Maven project setup you can integrate Citrus with it. Just add the Citrus project dependencies
in your Maven pom.xml as a dependency like follows.

* We add Citrus as test-scoped project dependency to the project POM (pom.xml)

.Add Citrus base dependency
[source,xml]
----
<dependency>
  <groupId>org.citrusframework</groupId>
  <artifactId>citrus-base</artifactId>
  <version>${citrus.version}</version>
  <scope>test</scope>
</dependency>
----

* The dependency above adds the base functionality of Citrus. You need to add modules as you require them.

.Add modules as required in your project. For instance Http support
[source,xml]
----
<dependency>
  <groupId>org.citrusframework</groupId>
  <artifactId>citrus-http</artifactId>
  <version>${citrus.version}</version>
  <scope>test</scope>
</dependency>
----

.Choose test runtime (JUnit, TestNG, Cucumber) that is used to run the tests.
[source,xml]
----
<dependency>
  <groupId>org.citrusframework</groupId>
  <artifactId>citrus-testng</artifactId>
  <version>${citrus.version}</version>
  <scope>test</scope>
</dependency>
----

* Citrus integrates nicely with the https://spring.io/projects/spring-framework[Spring framework].
In case you want to use the Spring dependency injection and bean configuration capabilities just
add the Spring support in Citrus.

.Add Spring support
[source,xml]
----
<dependency>
  <groupId>org.citrusframework</groupId>
  <artifactId>citrus-spring</artifactId>
  <version>${citrus.version}</version>
  <scope>test</scope>
</dependency>
----

* Also, Citrus provides a Maven plugin that you can add. The plugin provides some convenience functionalities such
as creating new tests from command line.

.Add Citrus Maven plugin
[source,xml]
----
<plugin>
  <groupId>org.citrusframework.mvn</groupId>
  <artifactId>citrus-maven-plugin</artifactId>
  <version>${citrus.version}</version>
  <configuration>
    <author>Donald Duck</author>
    <targetPackage>org.citrusframework</targetPackage>
  </configuration>
</plugin>
----

The Maven project is now ready to use Citrus. You can start writing new test cases with the Citrus Maven plugin:

.Create new test
[source,bash]
----
mvn citrus:create-test
----

The command above starts an interactive command line interface that helps you to create a test.

Once you have written the Citrus test cases you can execute them automatically in your Maven software build lifecycle.
The tests will be included into your project's integration-test phase using the Maven failsafe plugin. Here is a sample
failsafe configuration for Citrus.

.Maven failsafe plugin
[source,xml]
----
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-failsafe-plugin</artifactId>
  <version>${maven.failsafe.version}</version>
  <executions>
    <execution>
      <id>integration-tests</id>
      <goals>
        <goal>integration-test</goal>
        <goal>verify</goal>
      </goals>
    </execution>
  </executions>
</plugin>
----

The Citrus test sources go to the default Maven test source directory `src/test/java` and `src/test/resources`.

You are now ready to call the usual Maven *verify* goal (`mvn verify`) in order to build your project and run the tests.
The Citrus integration tests are executed automatically during the build process.

.Run all tests with Maven
[source,bash]
----
mvn verify
----

.Run single test by its name
[source,bash]
----
mvn verify -Dit.test=MyFirstCitrusIT
----

IMPORTANT: The Maven failsafe plugin by default executes tests with specific name pattern. This is because integration
tests should not execute in Maven unit test phase, too. Your integration tests should follow
the failsafe name pattern with each test name beginning or ending with *'IT'*.

NOTE: If you need additional assistance in setting up a Citrus Maven project please visit our Maven setup tutorial
on https://citfrusframework.org[https://citrusframework.org/tutorials.html].

[[setup-gradle]]
== Using Gradle

As Citrus tests are nothing but normal JUnit or TestNG tests the integration to Gradle as build tool is as easy as adding
the source files to a folder in your project. With the Gradle task execution for integration tests you are able to execute
the Citrus tests like you would do with normal unit tests.

The Gradle build configuration goees to the **build.gradle** and **settings.gradle** files. The files define the project name
and the project version.

.Gradle project configuration
[source,groovy]
----
rootProject.name = 'citrus-sample-gradle'
group 'org.citrusframework.samples'
version '${citrus.version}'
----

The Citrus libraries are available on Maven central repository. This means you should add this repository so Gradle knows
how to download the required Citrus artifacts.

.Add Maven central repository
[source,groovy]
----
repositories {
    mavenCentral()
}
----

Citrus stable release versions are available on Maven central. Now let's move on with adding the Citrus libraries to the project.

.Add Citrus test scoped dependencies
[source,groovy]
----
dependencies {
    testCompile group: 'org.citrusframework', name: 'citrus-base', version: '${citrus.version}'
    testCompile group: 'org.citrusframework', name: 'citrus-http', version: '${citrus.version}'
    testCompile group: 'org.testng', name: 'testng', version: '6.11'
    [...]
}
----

Citrus provides various modules that encapsulate different functionalities. The `citrus-base` module is the basis and holds core functionality. In addition, you may
add further modules that match your project needs (e.g. add Http support with `citrus-http`).

As a runtime the project chose to use TestNG. You can also use JUnit or Cucumber as a test runtime. Each of those frameworks integrates seamlessly with the Gradle build.

.Choose test runtime provider
[source,groovy]
----
test {
    useTestNG()
}
----

Of course JUnit is also supported. This completes the Gradle build configuration settings. You can move on to writing some Citrus integration tests and add those to *src/test/java* directory.

You can use the Gradle wrapper for compile, package and test the sample with Gradle build command line.

.Run the build with Gradle
[source,bash]
----
gradlew clean build
----

This executes all Citrus test cases during the build. You will be able to see Citrus performing some integration test logging output.

If you just want to execute all tests you can call:

.Run all tests
[source,bash]
----
gradlew clean check
----

Of course, you can also run the Citrus tests from your favorite Java IDE. Just start the Citrus test as a normal unit test
using the Gradle integration in IntelliJ, Eclipse or VSCode.
