[[test-variables]]
= Test variables

The usage of test variables is a core concept when writing maintainable tests. The key identifiers of a test case should
be exposed as test variables at the very beginning of a test. This avoids hard coded identifiers and multiple redundant values
inside the test.

.Java
[source,java,indent=0,role="primary"]
----
public void fooService_IT() {
    variable("text", "Hello Citrus!");
    variable("customerId", "123456789");

    run(echo("Text: ${text} Id: ${id}"));
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<testcase name="FooService_IT">
  <variables>
    <variable name="text" value="Hello Citrus!"/>
    <variable name="customerId" value="123456789"/>
  </variables>

  <actions>
    <echo>
      <message>Text: ${text} Id: ${id}</message>
    </echo>
  </actions>
</testcase>
----

Test variables help significantly when writing complex tests with lots of identifiers and semantic data. The
variables are valid for the whole test case. You can reference a variable multiple times using a common variable
expression `${variable-name}`.

The usage of variables should make the test easier to maintain and more flexible. All essential entities and identifiers are present
right at the beginning of the test, which may also give the opportunity to easily create test variants by simply changing
the variable values for other test scenarios (e.g. different error codes, identifiers).

The name of the variable is arbitrary. Of course, you need to be careful with special characters and reserved XML entities
like '&amp;', '&lt;', '&gt;'. In general, you can apply to the Java naming convention, and you will be fine.

[[global-variables]]
== Global variables

You can work with different variable scopes (local or global). Local variables are accessible throughout a single test.
Global variables are visible for all tests yet global variables are immutable, so tests cannot change their values.

This is a good opportunity to declare constant values for all tests. As these variables are global we need to add those
to the basic Citrus context. The following example demonstrates how to add global variables in Citrus:

.Citrus Bean
[source,java,indent=0,role="primary"]
----
@BindToRegistry
public GlobalVariables globalVariables() {
    return new GlobalVariables.Builder()
        .variable("projectName", "Citrus Integration Testing")
        .variable("userName", "TestUser")
        .build();
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Bean
public GlobalVariables globalVariables() {
    return new GlobalVariables.Builder()
        .variable("projectName", "Citrus Integration Testing")
        .variable("userName", "TestUser")
        .build();
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
           http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd">

    <citrus:global-variables>
      <citrus:variable name="projectName" value="Citrus Integration Testing"/>
      <citrus:variable name="userName" value="TestUser"/>
    </citrus:global-variables>
</beans>
----

We add the Spring bean component to the application context file. The component receives a list of name-value variable
elements. You can reference the global variables in your test cases as usual.

Another possibility to set global variables is to load those from external property files. This may give you more powerful
global variables with user specific properties for instance. See how to load property files as global variables in this example:

.Citrus Bean
[source,java,indent=0,role="primary"]
----
@BindToRegistry
public GlobalVariablesPropertyLoader propertyLoader() {
    GlobalVariablesPropertyLoader propertyLoader = new GlobalVariablesPropertyLoader();

    propertyLoader.getPropertyFiles().add("classpath:global-variable.properties");

    return propertyLoader;
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Bean
public GlobalVariablesPropertyLoader propertyLoader() {
    GlobalVariablesPropertyLoader propertyLoader = new GlobalVariablesPropertyLoader();

    propertyLoader.getPropertyFiles().add("classpath:global-variable.properties");

    return propertyLoader;
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="
           http://www.springframework.org/schema/beans
           http://www.springframework.org/schema/beans/spring-beans.xsd">

    <citrus:global-variables>
      <citrus:file path="classpath:global-variable.properties"/>
    </citrus:global-variables>
</beans>
----

You can use the `GlobalVariablesPropertyLoader` component and add it to the context as a Spring bean. Citrus loads the
given property file content as global test variables. You can mix property file and name-value pair variable definitions
in the global variables component.

NOTE: The global variables can have variable expressions and Citrus functions. It is possible to use previously defined
global variables as values of new variables, like in this example:

.global-variable.properties
[source,properties]
----
user=Citrus
greeting=Hello ${user}!
date=citrus:currentDate('yyyy-MM-dd')
----

[[variables-extract]]
== Extract variables

Imagine you receive a message in your test with some generated message identifier values. You have no chance to predict the
identifier value because it was generated at runtime by a foreign application. You can ignore the value in order to protect
your validation. In many cases you might want to save this identifier in order to use this value in the respective response
message or somewhat later on in the test.

The solution is to extract dynamic values from received messages and save those to test variables at runtime.

[[variables-extract-json-path]]
=== JsonPath expressions

When an incoming message is passing the message validation the user can extract some values of that received message to
new test variables for later use in the test.

[source,xml]
----
<message type="json">
  <data>
    { "user":
      {
        "name": "Admin",
        "password": "secret",
        "admin": "true",
        "aliases": ["penny","chef","master"]
      }
    }
  </data>
  <extract>
    <message path="$.user.name" variable="userName"/>
    <message path="$.user.aliases" variable="userAliases"/>
    <message path="$.user[?(@.admin)].password" variable="adminPassword"/>
  </extract>
</message>
----

With this example we have extracted three new test variables via JSONPath expression evaluation. The three test variables
will be available to all upcoming test actions. The variable values are:

[source,properties]
----
userName=Admin
userAliases=["penny","chef","master"]
adminPassword=secret
----

As you can see we can also extract complex JSONObject items or JSONArray items. The test variable value is a String representation
of the complex object.

[[variables-extract-xpath]]
=== XPath expressions

Add this code to your message receiving action.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void receiveMessageTest() {
    when(
        receive("helloService")
            .extract(extract().fromBody()
                    .expression("//TestRequest/VersionId", "versionId"))
            .extract(extract().fromHeaders()
                    .header("Operation", "operation"))
    );

    then(
        echo("Operation from header is: ${operation}")
    );

    then(
        echo("Version from body is: ${versionId}")
    );
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="ReceiveMessageTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
      <receive endpoint="helloService">
        <message>
          <body>
              <data>[...]</data>
          </body>
        </message>
        <extract>
          <header name="Operation"
                  variable="operation"/>
          <body path="/TestRequest/VersionId"
                variable="versionId"/>
        </extract>
      </receive>

      <echo>
        <message>Operation from header is: ${operation}</message>
      </echo>

      <echo>
        <message>Version from body is: ${versionId}</message>
      </echo>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: ReceiveMessageTest
actions:
  - receive:
      endpoint: helloService
      message:
        body:
          data: {}
        extract:
          header:
            - name: "Operation"
              variable: "operation"
          body:
            - path: "/TestRequest/VersionId"
              variable: "versionId"
  - echo:
      message: "Operation from header is: ${operation}"
  - echo:
      message: "Version from body is: ${versionId}"
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
          xmlns:spring="http://www.springframework.org/schema/beans"
          xsi:schemaLocation="http://www.springframework.org/schema/beans
          http://www.springframework.org/schema/beans/spring-beans.xsd
          http://www.citrusframework.org/schema/testcase
          http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">
  <testcase name="ReceiveMessageTest">
    <actions>
        <receive endpoint="helloService">
            <message>
              <data>[...]</data>
            </message>
            <extract>
              <header name="Operation"
                      variable="operation"/>
              <message path="/TestRequest/VersionId"
                       variable="versionId"/>
            </extract>
        </receive>

        <echo>
          <message>Operation from header is: ${operation}</message>
        </echo>

        <echo>
          <message>Version from body is: ${versionId}</message>
        </echo>
    </actions>
  </testcase>
</spring:beans>
----

As you can see Citrus is able to extract both header and message body content into test variables. The extraction will automatically
create a new variable in case it does not exist. The time the variable was created all following test actions can access the
test variables as usual. So you can reference the variable values in response messages or other test steps ahead.

TIP: We can also use expression result types in order to manipulate the test variable outcome. In case we use a *boolean* result
type the existence of elements can be saved to variable values. The result type *node-set* translates a node list result to
a comma separated string of all values in this node list. Simply use the expression result type attributes as shown in previous
sections.

[[variables-object-graph]]
== Object graphs and the scenario container

A test variable can hold any Java object, not just strings. Store a rich object with `setVariable` (or `variable(...)` in the
Java DSL) and traverse its fields, list/array elements, and map entries directly in `${...}` expressions. A common pattern is
to keep all scenario-lifetime data under a single `container` variable — sometimes called the scenario container or data
container — so every test step reads from one predictable root instead of scattered variables:

[source,plaintext]
----
❌ Scattered: separate variables per domain, static helpers, ad-hoc context entries
✓ Container:  container
              ├── customer   → Customer entity (Java object)
              ├── order      → Order entity (Java object)
              ├── currencies → reference data (Java List)
              └── campaign   → runtime-created data (Java Map or object)
----

[source,java,indent=0]
----
context.setVariable("container", scenarioContainer);
echo("Customer id is ${container.customer.id}, first currency is ${container.currencies[0].code}");
----

NOTE: Never store credentials, tokens, or secrets in the container. It lives in plain memory in the test context and is
designed for business fixtures, not sensitive material. Container data should be treated as read-only once published: write
it during setup, then only read it during test execution.

[[variables-object-graph-resolution]]
=== How Citrus resolves path expressions

When Citrus encounters `${container.customer.id}`, it walks the path segment by segment:

1. **Root resolution**: find the `container` variable in the `TestContext`.
2. **Segment parsing**: split the remainder into segments: `customer` → `id`.
3. **Reflection traversal**: for `customer`, read the `customer` field of the container object; for `id`, read the `id`
field of the customer object. Each step uses the declared or inherited Java field (including `static` fields).
4. **Type conversion**: convert the final value to a string for expression substitution.

Resolution rules by segment type:

| Segment | Syntax | What Citrus does | Example |
|---|---|---|---|
| Object field | `.fieldName` | Reads the declared or inherited Java field via reflection | `${container.customer}` |
| Nested object | `.field.subfield` | Traverses into the referenced object | `${container.customer.address.city}` |
| Static field | `.CONSTANT` | Reads a `static` field | `${container.data.CONSTANT}` |
| Array or `List` index | `[N]` | Reads element `N` (`Array.get` for arrays, `List.get` for lists); `N` may have multiple digits | `${container.currencies[12].code}` |
| Map key | `.keyName` | Reads `map.get(keyName)` | `${container.campaign.id}` |

The index grammar is strict: `[N]` holds one or more ASCII digits only — no signs, no spaces, one index per segment
(`matrix[0][1]` is not supported). Indexes beyond the `int` range fail with a Citrus error. Resolution uses fields, not
property getters: a value exposed only through `getX()` with no backing field `x` cannot be resolved.

What Citrus CAN resolve:

[source,plaintext]
----
✓ Direct field access:      ${container.customer}
✓ Nested field access:      ${container.customer.id}
✓ Array indexing:            ${container.intVals[1]}
✓ List indexing:             ${container.currencies[0].code}
✓ Multi-digit indexes:       ${container.currencies[12].code}
✓ Nested array/list+field:   ${containerArray[3].data[1].data}
✓ Map key access:            ${container.campaign.id}
✓ Static final fields:       ${container.data.CONSTANT}
✓ Inherited fields:          (fields from parent classes)
----

What Citrus CANNOT resolve:

[source,plaintext]
----
❌ Method invocation:        ${container.getCustomer().getId()}
❌ Conditional expressions:  ${container.customer != null ? ...}
❌ Lambda/functional:        ${container.list.stream().filter(...)}
❌ Constructor calls:         ${new String("test")}
❌ Sets and other collections (only arrays and java.util.List support [N])
----

[[variables-object-graph-example]]
=== Worked example

Given a holder class such as the `DataContainer` used in the Citrus test suite:

[source,java,indent=0]
----
private static class DataContainer {
    private final int number = 99;
    private final Object data;
    private final int[] intVals = new int[] {0, 1, 2, 3, 4};
    private final List<String> strVals = List.of("A", "B", "C");
    private static final String CONSTANT = "FOO";

    public DataContainer(Object data) {
        this.data = data;
    }
}
----

| Field | Type | Notes |
|---|---|---|
| `number` | `int` | Primitive, always accessible |
| `data` | `Object` | Can hold any type, including nested holders for deep traversal |
| `intVals` | `int[]` | Primitive array, supports `[N]` |
| `strVals` | `List<String>` | List, supports `[N]` exactly like an array |
| `CONSTANT` | `String` | `static final`, accessible by name |

Resolution walkthrough with `context.setVariable("container", new DataContainer(new DataContainer("nested")))`:

[source,plaintext]
----
${container.number}           → 99                                  (direct field)
${container.data.data}        → "nested"                            (nested traversal)
${container.data.number}      → 99                                  (field of nested object)
${container.data.CONSTANT}    → "FOO"                               (static field)
${container.intVals[1]}       → 1                                   (array index)
${container.strVals[1]}       → "B"                                 (list index)
${containerArray[3].data[1].data} → "B"                             (index composes with nesting)
----

[[variables-object-graph-conversion]]
=== Type conversion

The resolved value is converted to a string (`String.valueOf`, or `toString()` for objects):

| Java type | Result | Example |
|---|---|---|
| `String` | As-is | `"hello"` → `"hello"` |
| `int`, `long`, `double`, wrappers | `String.valueOf()` | `99` → `"99"` |
| `boolean` | `String.valueOf()` | `true` → `"true"` |
| `LocalDate` and other objects | `toString()` | `2024-01-15` → `"2024-01-15"` |

When you need the raw object instead of its string form, use `TestContext.getVariableObject("container.customer")`.

[[variables-object-graph-errors]]
=== Errors

Unknown segments fail fast with a `CitrusRuntimeException`:

* Unknown variable root (`${nope.id}`), unknown field (`${container.bogus}`), or an indexed segment on a value that
is neither an array nor a `List` (`Expected an instance of Array type...`).
* A field that exists but currently holds `null` also fails: guard optional data in your test (e.g. assert presence
first) rather than relying on the exception. The same applies to missing map keys.
* Out-of-bounds indexes propagate the JDK exception (`IndexOutOfBoundsException` for lists,
`ArrayIndexOutOfBoundsException` for arrays).

[[variables-object-graph-practices]]
=== Best practices

* Use direct expressions for values that must exist (`${container.customer.id}`) — a failure then means a real bug.
* Keep container data read-only after publication: publish once during setup, read many times.
* Use descriptive names matching your domain (`${container.customer.name}`, not `${container.c.name}`).
* Verify the container is populated before access; a clear setup assertion beats a cryptic resolution error later.

[[variables-object-graph-troubleshooting]]
=== Troubleshooting

* `Unknown variable 'container'` — the container has not been published to the `TestContext` yet. Check that setup ran
before the failing step.
* `Unknown segment-value for segment 'X'` — the field name is misspelled, does not exist on the entity, or currently
holds `null`. Check the entity class for the exact camelCase field name.
* `Expected an instance of Array type...` — `[N]` was applied to a value that is neither an array nor a `List` (e.g. a
`Set` or a plain object). Only arrays and `java.util.List` support indexed access.
* Stale data from a previous test — variables live for the whole test case, so republish the container per test instead
of reusing it across tests.

[[variables-path-expressions]]
== Path expressions

Some elements in message body might be of dynamic nature. Just think of generated identifiers or timestamps. This is the right
time to use test variables and dynamic message element overwrite. You can overwrite specific elements in the message body
with path expressions (XPath or JsonPath).

[[variables-json-path-expressions]]
=== JsonPath expressions

First thing we want to do with JsonPath is to manipulate a message content before it is actually processed. This is very
useful when working with message file resources that are reused across multiple test cases. Each test case can manipulate
the message content individually with JsonPath before processing the message content.

Let's have a look at this simple sample Json message body:

.Json message body user.json
[source,json]
----
{ "user":
  {
    "id": citrus:randomNumber(10),
    "name": "Unknown",
    "admin": "?",
    "projects":
      [{
        "name": "Project1",
        "status": "open"
      },
      {
        "name": "Project2",
        "status": "open"
      },
      {
        "name": "Project3",
        "status": "closed"
      }]
  }
}
----

Citrus can load the file content and uses it as message body when sending or receiving messages in a test case. You can apply
JsonPath expressions in order to manipulate the message content.

[source,xml]
----
<message type="json">
  <resource file="file:path/to/user.json" />
  <element path="$.user.name" value="Admin" />
  <element path="$.user.admin" value="true" />
  <element path="$..status" value="closed" />
</message>
----

When all path expressions are evaluated the resulting message looks like follows:

[source,json]
----
{ "user":
  {
    "id": citrus:randomNumber(10),
    "name": "Admin",
    "admin": "true",
    "projects":
      [{
        "name": "Project1",
        "status": "closed"
      },
      {
        "name": "Project2",
        "status": "closed"
      },
      {
        "name": "Project3",
        "status": "closed"
      }]
  }
}
----

The JsonPath expressions set the username to *Admin* . The *admin* boolean property was set to *true* and all project
status values were set to *closed*. In case a JsonPath expression should fail to find a matching element within the message
structure the test case will fail.

With this JsonPath mechanism you are able to manipulate message content before it is sent or received within Citrus. This
makes life very easy when using message resource files that are reused across multiple test cases.

[[variables-xpath-expressions]]
=== XPath expressions

In case of XML message bodies you can use XPath expressions to manipulate the body content before any message processing
takes place.

.Java
[source,java,indent=0,role="primary"]
----
@CitrusTest
public void receiveMessageTest() {
    receive("helloService")
        .message()
            .header("Operation", "sayHello")
            .body("""
            <TestMessage xmlns="http://citrusframework.org/schemas/test">
              <MessageId>${messageId}</MessageId>
              <CreatedAt>?</CreatedAt>
              <VersionId>${version}</VersionId>
            </TestMessage>
            """)
            .process(processor().path()
                .expression("/TestMessage/CreatedAt", "${date}"));
}
----

.XML
[source,xml,indent=0,role="secondary"]
----
<test name="ReceiveMessageTest" xmlns="http://citrusframework.org/schema/xml/testcase">
    <actions>
      <receive endpoint="helloService">
        <message>
          <headers>
            <header name="Operation" value="sayHello"/>
          </headers>
          <body>
            <payload>
                <TestMessage xmlns="http://citrusframework.org/schemas/test">
                  <MessageId>${messageId}</MessageId>
                  <CreatedAt>?</CreatedAt>
                  <VersionId>${version}</VersionId>
                </TestMessage>
            </payload>
          </body>
          <expression path="/TestMessage/CreatedAt" value="${date}"/>
        </message>
      </receive>
    </actions>
</test>
----

.YAML
[source,yaml,indent=0,role="secondary"]
----
name: ReceiveMessageTest
actions:
  - receive:
      endpoint: helloService
      message:
        body:
          data: |
            <TestMessage xmlns="http://citrusframework.org/schemas/test">
              <MessageId>${messageId}</MessageId>
              <CreatedAt>?</CreatedAt>
              <VersionId>${version}</VersionId>
            </TestMessage>
        expressions:
          - path: "/TestMessage/CreatedAt"
            value: "${date}"
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
          xmlns:spring="http://www.springframework.org/schema/beans"
          xsi:schemaLocation="http://www.springframework.org/schema/beans
          http://www.springframework.org/schema/beans/spring-beans.xsd
          http://www.citrusframework.org/schema/testcase
          http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">
  <testcase name="ReceiveMessageTest">
    <actions>
        <receive endpoint="helloService">
            <message>
              <payload>
                <TestMessage xmlns="http://citrusframework.org/schemas/test">
                  <MessageId>${messageId}</MessageId>
                  <CreatedAt>?</CreatedAt>
                  <VersionId>${version}</VersionId>
                </TestMessage>
              </payload>
              <element path="/TestMessage/CreatedAt" value="${date}"/>
            </message>
        </receive>
    </actions>
  </testcase>
</spring:beans>
----

The program listing above shows ways of setting variable values inside a message template. First you can simply place variable
expressions inside the message (see how `${messageId}` is used in the sample). In addition to that you can also use path
expressions to explicitly overwrite message elements before message processing takes place.

The sample above uses an XPath expression that evaluates and searches for the right element in the message body in order
to set the given value. The previously defined variable *${date}* replaces the respective element value. Of course this
works with XML attributes too (e.g. path expression `/TestMessage/Person/@age`).

Both ways via XPath or JsonPath or inline variable expressions are equal to each other. With respect to the complexity of
XML namespaces and XPath you may find the inline variable expression more comfortable to use. Anyway feel free to choose
the way that fits best for you.

This is how you can overwrite values in message templates in order to increase maintainability and robustness of your test.

TIP: Validation matchers put validation mechanisms to a new level offering dynamic assertion statements for validation.
Have a look at the possibilities with assertion statements in link:#validation-matcher[validation-matcher].

[[escaping-variables-expression]]
== Escape variables

The test variable expression syntax `${variable-name}` is preserved to evaluate to a test variable within the current
test context. In case the same syntax is used in one of your message content values you need to escape the syntax from
being interpreted as test variable expression. You can do this by using the variable expression escaping character sequence
`//` wrapping the actual variable name like this:

.Plain text message content with escapes
[source,plaintext]
----
This is an escaped variable expression ${//escaped//} and should not lead to unknown variable exceptions within Citrus.
----

The escaped expression `${//escaped//}` above will result in the string *${escaped}* where _escaped_ is not treated as a
test variable name but as a normal string in the message body.

This way you are able to have the same variable syntax in a message content without interfering with the Citrus variable
expression syntax. As a result Citrus will not complain about not finding the test variable *escaped* in the current context.

The variable syntax escaping characters `//` are automatically removed when the expression is processed by Citrus. So we
will get the following result after processing.

.Parsed plain text mesage content
[source,plaintext]
----
This is an escaped variable expression ${escaped} and should not lead to unknown variable exceptions within Citrus.
----
