[[test-suite-actions]]
= Test suite actions

A test framework should also provide the functionality to do some work before and after the test run.
Typical tasks in the section before or after a test could be preparing data in a database or starting/stopping a service.
These tasks fit best into the initialization or cleanup phase of Citrus.

[[before-suite]]
== Before suite

You can influence the behavior of a whole test run in the initialization phase of the test suite.
Before any of the tests has started this section is executed once for the whole test run.
See the next code example to find out how it works with actions that take place before the first test is executed:

.Citrus Bean
[source,java,indent=0,role="primary"]
----
public class BeanConfiguration {

    @BindToRegistry
    public SequenceBeforeSuite beforeSuite() {
        return new SequenceBeforeSuite.Builder()
                .actions(
                    echo().message("This is run before suite")
                );
    }
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Configuration
public class BeanConfiguration {
    @Bean
    public SequenceBeforeSuite beforeSuite() {
        return new SequenceBeforeSuite.Builder()
                .actions(
                    echo().message("This is run before suite")
                );
    }
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:citrus="http://www.citrusframework.org/schema/config"
              xmlns:citrus-test="http://www.citrusframework.org/schema/testcase"
              xsi:schemaLocation="http://www.springframework.org/schema/beans
                                  http://www.springframework.org/schema/beans/spring-beans.xsd
                                  http://www.citrusframework.org/schema/config
                                  http://www.citrusframework.org/schema/config/citrus-config.xsd
                                  http://www.citrusframework.org/schema/testcase
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">

    <citrus:before-suite id="actionsBeforeSuite">
        <citrus:actions>
            <!-- list of actions before suite -->
            <citrus-test:echo>
              <citrus-test:message>This is run before suite</message>
            </citrus-test:echo>
        </citrus:actions>
    </citrus:before-suite>
</spring:beans>
----

NOTE: It is important to notice that the Citrus Spring bean XML configuration components belong to a separate namespace `citrus:http://www.citrusframework.org/schema/config`. You need to add the namespace declaration to the Spring bean XML root element of configuration file accordingly.
Test actions use a different namespace `citrus-test:http://www.citrusframework.org/schema/testcase` so we need to include both namespaces.

The Citrus configuration component holds a list of Citrus test actions that get executed before the test suite.
You can add all Citrus test actions here as you would do in a normal test case definition.

.Citrus Bean
[source,java,indent=0,role="primary"]
----
public class BeanConfiguration {

    @BindToRegistry
    public SequenceBeforeSuite beforeSuite() {
        return new SequenceBeforeSuite.Builder()
                .actions(
                    sql().dataSource(testDataSource)
                        .statement("CREATE TABLE PERSON (ID integer, NAME char(250))")
                );
    }
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Configuration
public class BeanConfiguration {
    @Bean
    public SequenceBeforeSuite beforeSuite() {
        return new SequenceBeforeSuite.Builder()
                .actions(
                    sql().dataSource(testDataSource)
                        .statement("CREATE TABLE PERSON (ID integer, NAME char(250))")
                );
    }
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:citrus="http://www.citrusframework.org/schema/config"
              xmlns:citrus-test="http://www.citrusframework.org/schema/testcase"
              xsi:schemaLocation="http://www.springframework.org/schema/beans
                                  http://www.springframework.org/schema/beans/spring-beans.xsd
                                  http://www.citrusframework.org/schema/config
                                  http://www.citrusframework.org/schema/config/citrus-config.xsd
                                  http://www.citrusframework.org/schema/testcase
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">

    <citrus:before-suite id="actionsBeforeSuite">
        <citrus:actions>
            <!-- list of actions before suite -->
            <citrus-test:sql datasource="testDataSource">
                <citrus-test:statement>CREATE TABLE PERSON (ID integer, NAME char(250))</citrus-test:statement>
            </citrus-test:sql>
        </citrus:actions>
    </citrus:before-suite>
</spring:beans>
----

The example above uses an SQL test action to access the database and create a table `PERSON` which is obviously needed in our test cases.
You can think of several actions here to prepare the tst infrastructure before the suite.

TIP: Citrus offers special startup and shutdown actions that may start and stop server implementations automatically. This might be helpful when dealing with Http servers or other service containers. You can also think of starting/stopping a message broker (e.g. Kafka) before a test run.

Users may have multiple configuration components declared to run in the before suite phase.
You can use different ids to separate the beans in the Citrus of Spring bean registry.

By default, Citrus scans for all available before suite containers and runs them sequentially.
You can restrict the before suite action container execution by adding a filter criteria on the suite name, a test group name, environment variables or system properties:

.Citrus Bean
[source,java,indent=0,role="primary"]
----
public class BeanConfiguration {

    @BindToRegistry
    public SequenceBeforeSuite beforeSuite() {
        return new SequenceBeforeSuite.Builder()
                .onSuite("databaseSuite")
                .onTestGroup("e2e")
                .actions(
                    sql().dataSource(testDataSource)
                        .statement("CREATE TABLE PERSON (ID integer, NAME char(250))")
                );
    }
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Configuration
public class BeanConfiguration {
    @Bean
    public SequenceBeforeSuite beforeSuite() {
        return new SequenceBeforeSuite.Builder()
                .onSuite("databaseSuite")
                .onTestGroup("e2e")
                .actions(
                    sql().dataSource(testDataSource)
                        .statement("CREATE TABLE PERSON (ID integer, NAME char(250))")
                );
    }
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:citrus="http://www.citrusframework.org/schema/config"
              xmlns:citrus-test="http://www.citrusframework.org/schema/testcase"
              xsi:schemaLocation="http://www.springframework.org/schema/beans
                                  http://www.springframework.org/schema/beans/spring-beans.xsd
                                  http://www.citrusframework.org/schema/config
                                  http://www.citrusframework.org/schema/config/citrus-config.xsd
                                  http://www.citrusframework.org/schema/testcase
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">

    <citrus:before-suite id="actionsBeforeSuite" suites="databaseSuite" groups="e2e">
        <citrus:actions>
            <!-- list of actions before suite -->
            <citrus-test:sql datasource="testDataSource">
                <citrus-test:statement>CREATE TABLE PERSON (ID integer, NAME char(250))</citrus-test:statement>
            </citrus-test:sql>
        </citrus:actions>
    </citrus:before-suite>
</spring:beans>
----

The above before suite container is only executed with the test suite called `databaseSuite`.
Also, it adds a filter on the test group that should match the group name `e2e`.

NOTE: Test groups are only supported when using the TestNG as a testing engine.

TIP: You can define multiple suite names and test groups with comma-delimited strings as an attribute value.

Environment variables or system properties are defined as a list of key-value pairs.
When such a filter criteria is present the specified variables and properties have to be set in the environment with the respective value.
In case the property value is left out in the configuration the System property must simply exist on the in order to enable the before suite container.

.Citrus Bean
[source,java,indent=0,role="primary"]
----
public class BeanConfiguration {

    @BindToRegistry
    public SequenceBeforeSuite beforeSuite() {
        return new SequenceBeforeSuite.Builder()
                .whenEnv("GITHUB_ENV", "")
                .whenSystemProperty("test-stage", "e2e")
                .actions(
                    sql().dataSource(testDataSource)
                        .statement("CREATE TABLE PERSON (ID integer, NAME char(250))")
                );
    }
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Configuration
public class BeanConfiguration {
    @Bean
    public SequenceBeforeSuite beforeSuite() {
        return new SequenceBeforeSuite.Builder()
                .whenEnv("GITHUB_ENV", "")
                .whenSystemProperty("test-stage", "e2e")
                .actions(
                    sql().dataSource(testDataSource)
                        .statement("CREATE TABLE PERSON (ID integer, NAME char(250))")
                );
    }
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:citrus="http://www.citrusframework.org/schema/config"
              xmlns:citrus-test="http://www.citrusframework.org/schema/testcase"
              xsi:schemaLocation="http://www.springframework.org/schema/beans
                                  http://www.springframework.org/schema/beans/spring-beans.xsd
                                  http://www.citrusframework.org/schema/config
                                  http://www.citrusframework.org/schema/config/citrus-config.xsd
                                  http://www.citrusframework.org/schema/testcase
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">

    <citrus:before-suite id="actionsBeforeSuite">
        <citrus:env>
          <citrus:property name="GITHUB_ENV"/>
        </citrus:env>
        <citrus:system>
          <citrus:property name="test-stage" value="e2e"/>
        </citrus:system>
        <citrus:actions>
            <!-- list of actions before suite -->
            <citrus-test:sql datasource="testDataSource">
                <citrus-test:statement>CREATE TABLE PERSON (ID integer, NAME char(250))</citrus-test:statement>
            </citrus-test:sql>
        </citrus:actions>
    </citrus:before-suite>
</spring:beans>
----

In the example above the before suite container is restricted to environments with `GITHUB_ENV` property set.
Also, the system property `test-stage` must be set to the value `e2e`.
Otherwise, the before suite container execution is skipped for this environment.

[[after-suite]]
== After suite

A test may run some actions to clean up the test environment after the test.
Just like the before suite is keen to prepare data before the suite is executed, you can add tasks to the test run after the last test in the test suite is finished.
This means that the after suite actions are run once after the last test.

TIP: It is a good idea to clean up the test environment after the test run. For instance, you can purge all JMS destinations and Kafka topics or clean up the database after the test run. This avoids errors in follow-up test runs where left over test data may influence upcoming tests.

.Citrus Bean
[source,java,indent=0,role="primary"]
----
public class BeanConfiguration {

    @BindToRegistry
    public SequenceBeforeSuite afterSuite() {
        return new SequenceAfterSuite.Builder()
                .actions(
                    echo().message("This is run after suite")
                );
    }
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Configuration
public class BeanConfiguration {
    @Bean
    public SequenceAfterSuite afterSuite() {
        return new SequenceAfterSuite.Builder()
                .actions(
                    echo().message("This is run after suite")
                );
    }
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:citrus="http://www.citrusframework.org/schema/config"
              xmlns:citrus-test="http://www.citrusframework.org/schema/testcase"
              xsi:schemaLocation="http://www.springframework.org/schema/beans
                                  http://www.springframework.org/schema/beans/spring-beans.xsd
                                  http://www.citrusframework.org/schema/config
                                  http://www.citrusframework.org/schema/config/citrus-config.xsd
                                  http://www.citrusframework.org/schema/testcase
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">

    <citrus:after-suite id="actionsAfterSuite">
        <citrus:actions>
            <!-- list of actions after suite -->
            <citrus-test:echo>
              <citrus-test:message>This is run after suite</message>
            </citrus-test:echo>
        </citrus:actions>
    </citrus:after-suite>
</spring:beans>
----

The after suite configuration component receives a unique id and holds one to many test actions as nested configuration elements.

Users may have multiple configuration components declared to run in the after suite phase.
You can use different ids to separate the beans in the Citrus of Spring bean registry.

By default, Citrus scans for all available after suite containers and runs them sequentially.
You can restrict the after suite action container execution by adding a filter criteria on the suite name, a test group name, environment variables or system properties. Please refer to the before suite examples in this guide to see how it works.

[[before-test]]
== Before test

You may have tasks that need to run before each test is executed.
Just like you have prepared some data in the actions before the whole test suite you can do the same before each test.

TIP: It is reasonable to clean up the test environment also between the tests (e.g. purge all JMS queues or Kafka topics).
In case a previous test fails some messages might be left in the message queues. Also, a failing test may leave the database in a dirty state.
The next test may be confronted with these invalid messages and data state. You can avoid these follow-up test failures with a good clean up before a test.

.Citrus Bean
[source,java,indent=0,role="primary"]
----
public class BeanConfiguration {

    @BindToRegistry
    public SequenceBeforeSuite beforeTest() {
        return new SequenceBeforeTest.Builder()
                .actions(
                    echo().message("This is run before test")
                );
    }
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Configuration
public class BeanConfiguration {
    @Bean
    public SequenceBeforeTest beforeTest() {
        return new SequenceBeforeTest.Builder()
                .actions(
                    echo().message("This is run before test")
                );
    }
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:citrus="http://www.citrusframework.org/schema/config"
              xmlns:citrus-test="http://www.citrusframework.org/schema/testcase"
              xsi:schemaLocation="http://www.springframework.org/schema/beans
                                  http://www.springframework.org/schema/beans/spring-beans.xsd
                                  http://www.citrusframework.org/schema/config
                                  http://www.citrusframework.org/schema/config/citrus-config.xsd
                                  http://www.citrusframework.org/schema/testcase
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">

    <citrus:before-test id="actionsBeforeTest">
        <citrus:actions>
            <!-- list of actions before test -->
            <citrus-test:echo>
              <citrus-test:message>This is run before test</message>
            </citrus-test:echo>
        </citrus:actions>
    </citrus:before-test>
</spring:beans>
----

The before test configuration component receives a unique id and a list of test actions that get executed before a test case is started.
The component receives usual test action definitions just like you would write them in a normal test case definition.

NOTE: It is important to notice that the Citrus Spring bean XML configuration components belong to a separate namespace `citrus:http://www.citrusframework.org/schema/config`. You need to add the namespace declaration to the Spring bean XML root element of configuration file accordingly.
Test actions use a different namespace `citrus-test:http://www.citrusframework.org/schema/testcase` so we need to include both namespaces.

The echo test action in the example above is now executed before each test in our test suite run.
Also notice that we can restrict the before test container execution on certain filter criteria.
We can restrict the execution based on the test name, package, test groups and environment or system properties.

See following example how this works:

.Citrus Bean
[source,java,indent=0,role="primary"]
----
public class BeanConfiguration {

    @BindToRegistry
    public SequenceBeforeSuite beforeTest() {
        return new SequenceBeforeTest.Builder()
                .onTests("*_Ok_Test")
                .onPackage("org.citrusframework.longrunning.*")
                .actions(
                    echo().message("This is run before test")
                );
    }
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Configuration
public class BeanConfiguration {
    @Bean
    public SequenceBeforeTest beforeTest() {
        return new SequenceBeforeTest.Builder()
                .onTests("*_Ok_Test")
                .onPackage("org.citrusframework.longrunning.*")
                .actions(
                    echo().message("This is run before test")
                );
    }
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:citrus="http://www.citrusframework.org/schema/config"
              xmlns:citrus-test="http://www.citrusframework.org/schema/testcase"
              xsi:schemaLocation="http://www.springframework.org/schema/beans
                                  http://www.springframework.org/schema/beans/spring-beans.xsd
                                  http://www.citrusframework.org/schema/config
                                  http://www.citrusframework.org/schema/config/citrus-config.xsd
                                  http://www.citrusframework.org/schema/testcase
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">

    <citrus:before-test id="actionsBeforeTest" test="*_Ok_Test" package="org.citrusframework.longrunning.*">
        <citrus:actions>
            <!-- list of actions before test -->
            <citrus-test:echo>
              <citrus-test:message>This is run before test</message>
            </citrus-test:echo>
        </citrus:actions>
    </citrus:before-test>
</spring:beans>
----

As an example the above before test component is only executed for test cases that match the name pattern `\\*_Ok_Test` and that match the package `org.citrusframework.longrunning.*`.

You can also filter based on environment variables or system properties.
When specified the properties have to be present in the test environment with the respective value.

.Citrus Bean
[source,java,indent=0,role="primary"]
----
public class BeanConfiguration {

    @BindToRegistry
    public SequenceBeforeTest beforeTest() {
        return new SequenceBeforeTest.Builder()
                .whenEnv("GITHUB_ENV", "")
                .whenSystemProperty("test-stage", "e2e")
                .actions(
                    sql().dataSource(testDataSource)
                        .statement("CREATE TABLE PERSON (ID integer, NAME char(250))")
                );
    }
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Configuration
public class BeanConfiguration {
    @Bean
    public SequenceBeforeTest beforeTest() {
        return new SequenceBeforeTest.Builder()
                .whenEnv("GITHUB_ENV", "")
                .whenSystemProperty("test-stage", "e2e")
                .actions(
                    sql().dataSource(testDataSource)
                        .statement("CREATE TABLE PERSON (ID integer, NAME char(250))")
                );
    }
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:citrus="http://www.citrusframework.org/schema/config"
              xmlns:citrus-test="http://www.citrusframework.org/schema/testcase"
              xsi:schemaLocation="http://www.springframework.org/schema/beans
                                  http://www.springframework.org/schema/beans/spring-beans.xsd
                                  http://www.citrusframework.org/schema/config
                                  http://www.citrusframework.org/schema/config/citrus-config.xsd
                                  http://www.citrusframework.org/schema/testcase
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">

    <citrus:before-test id="actionsBeforeTest">
        <citrus:env>
          <citrus:property name="GITHUB_ENV"/>
        </citrus:env>
        <citrus:system>
          <citrus:property name="test-stage" value="e2e"/>
        </citrus:system>
        <citrus:actions>
            <!-- list of actions before suite -->
            <citrus-test:sql datasource="testDataSource">
                <citrus-test:statement>CREATE TABLE PERSON (ID integer, NAME char(250))</citrus-test:statement>
            </citrus-test:sql>
        </citrus:actions>
    </citrus:before-test>
</spring:beans>
----

In the example above the before test container is restricted to environments with `GITHUB_ENV` property set.
Also, the system property `test-stage` must be set to the value `e2e`.
Otherwise, the before test container execution is skipped for this environment.

[[after-test]]
== After test

The same logic that applies to the `before-test` configuration component can be done after each test.
The `after-test` configuration component defines test actions executed after each test.

.Citrus Bean
[source,java,indent=0,role="primary"]
----
public class BeanConfiguration {

    @BindToRegistry
    public SequenceAfterSuite afterTest() {
        return new SequenceAfterTest.Builder()
                .actions(
                    echo().message("This is run after test")
                );
    }
}
----

.Spring Bean
[source,java,indent=0,role="secondary"]
----
@Configuration
public class BeanConfiguration {
    @Bean
    public SequenceAfterTest afterTest() {
        return new SequenceAfterTest.Builder()
                .actions(
                    echo().message("This is run after test")
                );
    }
}
----

.Spring XML
[source,xml,indent=0,role="secondary"]
----
<spring:beans xmlns="http://www.citrusframework.org/schema/testcase"
              xmlns:spring="http://www.springframework.org/schema/beans"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xmlns:citrus="http://www.citrusframework.org/schema/config"
              xmlns:citrus-test="http://www.citrusframework.org/schema/testcase"
              xsi:schemaLocation="http://www.springframework.org/schema/beans
                                  http://www.springframework.org/schema/beans/spring-beans.xsd
                                  http://www.citrusframework.org/schema/config
                                  http://www.citrusframework.org/schema/config/citrus-config.xsd
                                  http://www.citrusframework.org/schema/testcase
                                  http://www.citrusframework.org/schema/testcase/citrus-testcase.xsd">

    <citrus:after-test id="actionsBeforeTest">
        <citrus:actions>
            <!-- list of actions after test -->
            <citrus-test:echo>
              <citrus-test:message>This is run after test</message>
            </citrus-test:echo>
        </citrus:actions>
    </citrus:after-test>
</spring:beans>
----

The after test configuration component receives a unique id and a list of test actions that get executed after a test case is finished.

NOTE: Notice that the after test actions are executed no matter what result (success or failure) the test case has produced.

The after suite container component receives usual test action definitions just like you would write them in a normal test case definition.
Of course, you can also restrict the after suite container execution based on filter criteria on the test name, test groups, environment variables and system properties.

Please see the explanations in the previous section about before test actions to see how it works.
