[[tools-cucumber-steps-groovy]]
== Groovy steps

The Groovy support in Citrus adds ways to configure the framework with bean configurations and test actions via
Groovy script snippets. In particular, you can add customized endpoints that send/receive data over various
messaging transports.

The Groovy script support is there to cover specific use cases where you hit limitations with the predefined
conventional BDD steps. Of course the syntax and handling of the Groovy scripts are less human-readable and more
developer-coherent.

[[steps-groovy-configuration-script]]
=== Bean configuration

Many steps use Citrus components behind the scenes. The Citrus components are configurable through a Groovy domain specific language.
You can add endpoints and other components as Citrus framework configuration like follows:

.@Given("^(?:create|new) configuration$")
[source,gherkin]
----
Given create configuration
"""
<<Groovy DSL>>
"""
----

In the next example the step uses a Groovy domain specific language to define a new Http server endpoint.

.Http server endpoint configuration
[source,gherkin]
----
Scenario: Endpoint script config
  Given URL: http://localhost:18080
  Given create configuration
  """
  citrus {
      endpoints {
          http {
              server('helloServer') {
                  port = 18080
                  autoStart = true
              }
          }
      }
  }
  """
  When send GET /hello
  Then receive HTTP 200 OK
----

The configuration step creates a new Citrus endpoint named `helloServer` with given properties (`port`, `autoStart`) in form of a Groovy configuration script.
The endpoint is a Http server Citrus component that is automatically started listening on the given port. In the following the scenario can send messages to that server endpoint.

The Groovy configuration script adds Citrus components to the test context and supports following elements:

* `endpoints`: Configure Citrus endpoint components that can be used to exchange data over various messaging transports
* `queues`: In memory queues to handle message forwarding for incoming messages
* `beans`: Custom beans configuration (e.g. data source, SSL context, request factory) that can be used in Citrus endpoint components

Let's quickly have a look at a bean configuration where a new JDBC data source is added to the test suite.

.JDBC data source configuration
[source,gherkin]
----
Scenario: Bean configuration
  Given create configuration
  """
  citrus {
      beans {
          dataSource(org.apache.commons.dbcp2.BasicDataSource) {
              driverClassName = "org.h2.Driver"
              url = "jdbc:h2:mem:camel"
              username = "sa"
              password = ""
          }
      }
  }
  """
----

The data source will be added as a bean named `dataSource` and can be referenced in all Citrus SQL test actions.

All Groovy configuration scripts that we have seen so far can also be loaded from external file resources, too.

.@Given("^load configuration {file_path}\\.groovy$")
[source,gherkin]
----
Given load configuration {file_path}.groovy
----

The file content is loaded as a Groovy configuration DSL. The next code sample shows such a configuration script.

.citrus.configuration.groovy
[source]
----
citrus {
    queues {
        queue('say-hello')
    }

    endpoints {
        direct {
            asynchronous {
                name = 'hello'
                queue = 'say-hello'
            }
        }
    }
}
----

[[steps-groovy-endpoint-script]]
=== Endpoint configuration

Endpoints describe an essential part in terms of messaging integration during a test. There are multiple ways to add custom endpoints
to a test. Endpoint Groovy scripts is one comfortable way to add custom endpoint configurations
in a test scenario. You can do so with the following step.

.@Given("^(?:create|new) endpoint {name}\\.groovy$")
[source,gherkin]
----
Given("^(?:create|new) endpoint {name}.groovy
"""
<<Groovy DSL>>
"""
----

The step receives a unique name for the endpoint and a Groovy DSL that sepcifies the endpoint component with all its properties.
In the following sample a new Http server endpoint component will be created.

.Create new Http server endpoint
[source,gherkin]
----
Scenario: Create Http endpoint
  Given URL: http://localhost:18081
  Given create endpoint helloServer.groovy
  """
  http()
    .server()
    .port(18081)
    .autoStart(true)
  """
  When send GET /hello
  Then receive HTTP 200 OK
----

The scenario creates a new Http server endpoint named `helloServer`. This server component can be used directly in the
scenario to receive and verify messages sent to that endpoint.

You can also load the endpoint configuration from an external file resources.

.@Given("^load endpoint {file_path}\\.groovy$")
[source,gherkin]
----
Given("^load endpoint {file_path}.groovy$")
----

The referenced file should contain the endpoint Groovy DSL.

.Create endpoint from file resource
[source,gherkin]
----
Scenario: Load endpoint
  Given URL: http://localhost:18088
  Given load endpoint fooServer.groovy
  When send GET /hello
  Then receive HTTP 200 OK
----

.fooServer.groovy
[source]
----
http()
    .server()
    .port(18088)
    .autoStart(true)
----

[[steps-groovy-action-script]]
=== Test actions

Citrus provides a huge set of predefined test actions that users can add to the Gherkin feature files out of the box.
However, there might be situations where you want to run a customized test action code as a step in your feature scenario.

With the Groovy script support in Citrus you can add such customized test actions via script snippets:

.@Given("^(?:create|new) actions {name}\\.groovy$")
[source,gherkin]
----
Given create actions {name}.groovy$")
"""
<<Groovy DSL>>
"""
----

The Groovy test action DSL script receives a unique `{name}`. You can reference this name later in the test in order to
apply the defined actions. When applied to the test the defined actions are executed. A sample will show how it is done.

.Create test actions with a script
[source,gherkin]
----
Scenario: Custom test actions
  Given create actions basic.groovy
  """
  $actions {
    $(echo('Hello from Groovy script'))
    $(delay().seconds(1))

    $(createVariables()
        .variable('foo', 'bar'))

    $(echo('Variable foo=${foo}'))
  }
  """
  Then apply basic.groovy
----

The example above defines the test actions with the Groovy DSL under the name `basic.groovy`. Later in the test the actions are executed with the
`apply` step.

.@Then("^(?:apply|verify) actions {name}\\.groovy$")
[source,gherkin]
----
Then apply actions {name}.groovy
----

Users familiar with Citrus will notice immediately that the action script is using the Citrus actions DSL to describe
what should be done when running the Groovy script as part of the test.

The Citrus action DSL is quite powerful and allows you to perform complex actions such as iterations, conditionals and
send/receive operations as shown in the next sample.

[source,gherkin]
----
Scenario: Messaging actions
  Given create actions messaging.groovy
  """
  $actions {
    $(send('direct:myQueue')
      .payload('Hello from Groovy script!'))

    $(receive('direct:myQueue')
      .payload('Hello from Groovy script!'))
  }
  """
  Then apply actions messaging.groovy
----

As an alternative to write the Groovy DSL directly into the test feature file you can also laod the test action script
from external file resources.

.@Given("^load actions {file_name}\\.groovy$")
[source,gherkin]
----
Given load actions {file_name}.groovy$")
----

The file name is the name of the action script. So you can use the file name to apply the script in the test for execution.

.Apply Groovy script
[source,gherkin]
----
Then apply actions {file_name}.groovy
----

You can also use a shortcut syntax to directly call a test action.

.@Then("^${{action_code})$")
[source,gherkin]
----
Then $(echo('Hello from Groovy script!'))
----

This will add a new `echo` test action and run the action. The action code uses a Groovy script that defines the test action
by using the common Citrus test action domain specific language.

You can apply multiline scripts directly, too.

.@Given("^apply script$")
[source,gherkin]
----
Given apply script
    """
    $actions {
        $(delay().seconds(1))

        $(echo('Hello from Groovy script!'))
    }
    """
----

[[steps-groovy-finally-actions]]
=== Finally actions

Sometimes it is mandatory to cleanup test data after a scenario. It would be good to have a set of test actions that
get executed in a guaranteed way - even in case the test scenario failed with errors before.

The Citrus framework provides a concept of `finally block` actions. These actions will be run after the test in all
circumstances (success and failure).

.Finally block actions
[source,gherkin]
----
Given apply script
    """
    $finally {
        echo('${greeting} in finally!')
    }
    """
----

As an alternative syntax you can add a 'doFinally()' test action to your script.

.Finally test action
[source,gherkin]
----
Given apply script
    """
    $actions {
        $(doFinally().actions(
            echo('${greeting} in finally!')
        ))
    }
    """
----

This is how you can define test actions in Groovy that get executed after the test.

