[[tools-cucumber-steps]]
= Cucumber Steps

Citrus is able to use the Cucumber runtime to execute BDD feature files as tests.
Read more about the section about xref:runtimes-cucumber[Cucumber integration with Citrus].

Cucumber feature files follow the Gherkin Given-When-Then syntax where each line in a feature file is backed by a step implementation.
The step implementation represents the actual runtime logic executed with the feature step.

Citrus provides a set of default ready-to-use step implementations that you can just add to your feature file.
The predefined steps leverage Citrus endpoints and test actions to perform integration testing with proper message exchange and validation.

IMPORTANT: If you want to use the predefined Citrus step implementations, please make sure to include the extra glue package as follows:

.MyFeatureIT.java
[source,java]
----
@RunWith(Cucumber.class)
@CucumberOptions(
    extraGlue = { "org.citrusframework.cucumber" },
    plugin = { "pretty", "org.citrusframework.cucumber.CitrusReporter" } )
public class MyFeatureIT {

}
----

As an alternative you may declare the glue package in `cucumber.properties` in your project.

.cucumber.properties
[source,properties]
----
cucumber.object-factory=org.citrusframework.cucumber.backend.CitrusObjectFactory
cucumber.glue=org.citrusframework.cucumber
cucumber.plugin=pretty,org.citrusframework.cucumber.CitrusReporter
----

NOTE: The Citrus step implementations require a special Cucumber object factory `org.citrusframework.cucumber.backend.CitrusObjectFactory`.

See the following step implementations that enable you to cover various areas of messaging and integration testing.

include::tools-cucumber-steps-core.adoc[]
include::tools-cucumber-steps-camel.adoc[]
include::tools-cucumber-steps-groovy.adoc[]
include::tools-cucumber-steps-http.adoc[]
include::tools-cucumber-steps-jdbc.adoc[]
include::tools-cucumber-steps-jms.adoc[]
include::tools-cucumber-steps-kafka.adoc[]
include::tools-cucumber-steps-kubernetes.adoc[]
include::tools-cucumber-steps-knative.adoc[]
include::tools-cucumber-steps-openapi.adoc[]
include::tools-cucumber-steps-selenium.adoc[]
include::tools-cucumber-steps-testcontainers.adoc[]
