[[schema-validation]]
== Schema validation

When structured data is transmitted from one system to another, it's important that the sender and the receiver
understand each other. To ensure this, a contract is required introducing the rules of communication for both parties.
This is mostly done by using schemas. Citrus brings the schema based validation of messages directly to your integration
test environment. This includes the management, mapping and filtering of schemas in context to your current test case
by just defining some rules in XML configuration or Java DSL. Let's start with this chapter by introducing some basic
concepts for the schema validation.

=== Managing schemas
Most complex applications have a lot of schemas that are relevant for different use cases. To organize these schemas
in your test cases, Citrus brings you some structuring capabilities.

==== Schema definitions
[source,xml]
----
<citrus:schema id="bookstore" location="classpath:com/consol/citrus/xml/BookStore.wsdl"/>
----

This xml snippet allows you to define a schema with an id located at the given classpath. Please keep in mind, that
the id of the schema has to be unique in the context.

==== Schema references
[source,xml]
----
<citrus:schema id="testSchema" location="classpath:com/consol/citrus/xml/test.xsd"/>

...
<citrus:reference schema="testSchema"/>
...
----

Citrus allows you to reuse your schema definition within your context by referencing them. For a valid reference,
the id of the schema and the value of the schema Attribute within the reference Element have to match.

==== Schema location definitions
[source,xml]
----
<citrus:location path="classpath:citrus/flightbooking/*.xsd"/>
----

Setting all schemas one by one can be verbose and uncomfortable, especially when dealing with
lots of schema files. Therefore, Citrus offers you schema location patterns which will import all matching schema files
within the given location.

==== Schema repositories
[source,xml]
----
<citrus:schema id="testSchema" location="classpath:com/consol/citrus/xml/test.xsd"/>

<citrus:schema-repository id="xmlSchemaRepository">
  <citrus:schemas>
    <citrus:schema id="bookstore" location="classpath:com/consol/citrus/xml/BookStore.wsdl"/>
    <citrus:reference schema="testSchema"/>
    <citrus:location path="classpath:com/consol/citrus/validation/*"/>
  </citrus:schemas>
</citrus:schema-repository>

<citrus:schema-repository type="json" id="jsonSchemaRepository">
    <citrus:schemas>
        <citrus:schema id="product" location="classpath:com/consol/citrus/validation/ProductsSchema.json"/>
    </citrus:schemas>
</citrus:schema-repository>
----

Citrus introduces a central schema repository component which holds all available schema files for a project disjoint
by their type (xml, json, etc.) and identified by its unique id. The default type of a schema repository is `type=xml`.

As you can see the schema repository is a simple XML component defined inside the Spring application context.
The repository can hold nested schema definitions, references and location definitions for all types of schema
repositories.

include::validation-schema-xml.adoc[]
include::validation-schema-json.adoc[]