[[plain-text-message-validation]]
== Plain text message validation

Plain text message validation is the easiest validation in Citrus that you can think of. This validation just performs an exact Java String match of received and expected message payloads.

As usual a default message validator for plaintext messages is active by default. Citrus will pick this message validator for all messages of *type="plaintext"* . The default message validator implementation can be overwritten by placing a Spring bean with id *defaultPlaintextMessageValidator* to the Spring application context.

[source,xml]
----
<bean id="defaultPlaintextMessageValidator" class="com.consol.citrus.validation.text.PlainTextMessageValidator"/>
----

In the test case receiving action we tell Citrus to use plain text message validation.

[source,xml]
----
<receive endpoint="httpMessageEndpoint">
    <message type="plaintext">
        <data>Hello World!</data>
    </message>
</receive>
----

With the message format type *type="plaintext"* set Citrus performs String equals on the message payloads (received and expected). Only exact match will pass the test.

By the way sending plain text messages in Citrus is also very easy. Just use the plain text message payload data in your sending message action.

[source,xml]
----
<send endpoint="httpMessageEndpoint">
    <message>
        <data>Hello World!</data>
    </message>
</send>
----

Of course test variables are supported in the plain text payloads. The variables are replace by the referenced values before sending or receiving the message.

Plaintext message payloads may only differ in system-dependent line separator characters (*CR*, _LF_, _CRLF_). By default the plain text message validation fails because of that differences even if only whitespace
characters are different.

You can disable this default validation behavior and ignore new line types with following system property or environment variable:

[source]
----
citrus.plaintext.validation.ignore.newline.type=true
CITRUS_PLAINTEXT_VALIDATION_IGNORE_NEWLINE_TYPE=true
----

In case you need to ignore all whitespaces during plain text validation such as multiple new line characters or tabs you need to set this system property or environment variable:

[source]
----
citrus.plaintext.validation.ignore.whitespace=true
CITRUS_PLAINTEXT_VALIDATION_IGNORE_WHITESPACE=true
----

This property will not only ignore new line types but also normalize the whitespaces. As a result all empty lines, tabs and double whitespace characters are filtered before comparison.

Of course you can also set the properties directly on the plain text message validator bean:

[source,xml]
----
<bean id="defaultPlaintextMessageValidator" class="com.consol.citrus.validation.text.PlainTextMessageValidator">
  <property name="ignoreNewLineType" value="true"/>
  <property name="ignoreWhitespace" value="true"/>
</bean>
----