[[json-schema-validation]]
=== JSON schema validation
The JSON schema validation in Citrus is based on the drafts provided by http://json-schema.org/[json-schema.org].
Because JSON schema is a fast evolving project, only JSON schema V3 and V4 are currently supported.

IMPORTANT: In contrast to the XML validation, the JSON validation is an optional feature. You have to activate it
withing every receive-message action by setting `schema-validation="true"`

[source,xml]
----
<http:receive-request server="echoHttpServer">
    <http:POST>
      <http:body type="json" schema="bookStore" schema-validation="true">
        <http:data>
          {
            "isbn" : "0345391802",
            "title": "The Hitchhiker's Guide to the Galaxy",
            "author": "Douglas Adams"
          }
        </http:data>
      </http:body>
    </http:POST>
</http:receive-request>
----

This behavior is currently required, to provide downwards compatibility to previous Citrus versions, because a
mandatory validation would cause all previous JSON based test cases to fail, due to the missing JSON schemas for the
messages within the test. That would have forced you to update all your JSON tests with the proper schema files.
This led us the decision to add the JSON validation as an optional feature initially. Nevertheless we encourage you to
add JSON schema validation to your test cases as soon as possible, because we think that message validation is a
important part of integration testing.

=== JSON schema repositories
Because Citrus supports different types of schema repositories, it is necessary to declare a JSON schema repository
as `type="json"`. This allows Citrus to collect all JSON schema files for the message validation.

[source,xml]
----
<citrus:schema-repository type="json" id="jsonSchemaRepository">
    <citrus:schemas>
        <citrus:schema id="product" location="classpath:com/consol/citrus/validation/ProductsSchema.json"/>
    </citrus:schemas>
</citrus:schema-repository>
----

=== JSON schema filtering and validation strategy
In reference to the current JSON schema definition, it is not possible to create a direct reference between a JSON
message and a set of schemas, as it would be possible with XML namespaces. Because of that, Citrus follows a rule set
for choosing the relevant schemas based on the configuration withing the test case in relation to the given context.
The following table assumes that the JSON schema validation is activated for the test action.

|===
|Scenario |Validation rules

|No JSON schema repositories are defined in the context.
|No JSON schema validation applies.

|There is at least one JSON schema repository defined in the context.
|The message of the test action must be valid regarding at least one of the available schemas within the context.

|A schema overruling is configured in the test case.
|The configured schema must exist and the message must be valid regarding to the specified schema.

|A schema repository overruling is configured in the test case.
|The configured schema repository must exist and the message must be valid regarding at least one of the schemas within
the specified schema repository.
|===