[[json-schema-validation]]
=== JSON schema validation
The JSON schema validation in Citrus is based on the drafts provided by http://json-schema.org/[json-schema.org].
Because JSON schema is a fast evolving project, only JSON schema V3 and V4 are currently supported.

IMPORTANT: In contrast to the XML validation, the JSON validation is an optional feature. You have to activate it
withing every receive-message action by setting `schema-validation="true"`

[source,xml]
----
<http:receive-request server="echoHttpServer">
    <http:POST>
      <http:body type="json" schema="bookStore" schema-validation="true">
        <http:data>
          {
            "isbn" : "0345391802",
            "title": "The Hitchhiker's Guide to the Galaxy",
            "author": "Douglas Adams"
          }
        </http:data>
      </http:body>
    </http:POST>
</http:receive-request>
----

This behavior is currently required, to provide downwards compatibility to previous Citrus versions, because a
mandatory validation would cause all previous JSON based test cases to fail, due to the missing JSON schemas for the
messages within the test. That would have forced you to update all your JSON tests with the proper schema files.
This led us the decision to add the JSON validation as an optional feature initially. Nevertheless we encourage you to
add JSON schema validation to your test cases as soon as possible, because we think that message validation is a
important part of integration testing.

=== JSON schema repositories

=== JSON schema matching strategy

