[[validation-custom]]
== Custom validation

In a previous section you have seen how to customize the global set of available message validators in a Citrus project using
the link:#message-validator-registry[validator registry].

[[validation-custom-validator]]
=== Custom message validator

You can also explicitly use a custom message validator in a receive test action. This approach skips the automatic message
validator resolving mechanism, and the receive action uses the defined validator implementation.

.Java
[source,java,indent=0,role="primary"]
----
receive("someEndpoint")
    .validator(groovyJsonMessageValidator)
    .message()
    .type(MessageType.JSON)
    .validate(groovy()
                .script("assert json.type == 'read'\n" +
                  "assert json.mbean == 'java.lang:type=Memory'\n" +
                  "assert json.attribute == 'HeapMemoryUsage'\n" +
                  "assert json.value == '${heapUsage}'");
----

.XML
[source,xml,indent=0,role="secondary"]
----
<receive endpoint="someEndpoint">
    <message type="json" validator="groovyJsonMessageValidator">
        <validate>
            <script type="groovy">
                <![CDATA[
                  assert json.type == 'read'
                  assert json.mbean == 'java.lang:type=Memory'
                  assert json.attribute == 'HeapMemoryUsage'
                  assert json.value == '${heapUsage}'
                ]]>
            </script>
        </validate>
    </message>
</receive>
----

The receive action defines the message validator to use in this specific use case. You can set a custom message validator
implementation here.

NOTE: Be careful when overwriting default message validation behavior. Setting a specific message validator has the effect
that your receive action may not use the other default validators. The explicit validator definition in a receive action
is exclusive so no further message validator resolving is performed on this receive action.

You may want to set multiple validators here in order to meet your validation requirements. For instance when setting a
`DomXmlMessageValidator` explicitly you may not be able to use the `XpathMessageValidator` capabilities on that specific
receive action anymore. Fortunately you can set multiple validators on a receive action that will all perform validation
tasks on the received message.

.Java
[source,java,indent=0,role="primary"]
----
receive("someEndpoint")
    .validators(myXmlMessageValidator, defaultXpathMessageValidator)
    .message()
    .body("...")
    .validate(xpath().expression("//some/xpath/expression", "someControlValue"));
----

.XML
[source,xml,indent=0,role="secondary"]
----
<receive endpoint="someEndpoint">
    <message type="json" validators="myXmlMessageValidator,defaultXpathMessageValidator">
        <payload>...</data>
        <validate path="//some/xpath/expression" value="someControlValue"/>
    </message>
</receive>
----

[[validation-custom-processor]]
=== Validation processor

The Java DSL offers some additional validation tricks and possibilities when dealing with messages that are sent and received
over Citrus. One of them is the validation processor functionality. With this feature you can marshal/unmarshal message payloads
and code validation steps on Java objects.

.Validation processor usage
[source,java]
----
receive(bookResponseEndpoint)
    .validate(new XmlMarshallingValidationProcessor<AddBookResponseMessage>() {
        @Override
        public void validate(AddBookResponseMessage response, MessageHeaders headers) {
            Assert.isTrue(response.isSuccess());
        }
    });
----

By default, the validation processor needs some XML unmarshaller implementation for transforming the XML payload to a Java
object. Citrus will automatically search for the unmarshaller bean in your Spring application context if nothing specific
is set. Of course, you can also set the unmarshaller instance explicitly.

.Use autowired unmarshaller
[source,java]
----
@Autowired
private Unmarshaller unmarshaller;

@CitrusTest
public void receiveMessageTest() {
    receive(bookResponseEndpoint)
        .validate(new XmlMarshallingValidationProcessor<AddBookResponseMessage>(unmarshaller) {
            @Override
            public void validate(AddBookResponseMessage response, MessageHeaders headers) {
                Assert.isTrue(response.isSuccess());
            }
        });
}
----

Obviously working on Java objects is much more comfortable than using the XML String concatenation. This is why you can
also use this feature when sending messages.

.Message body marshalling
[source,java]
----
@Autowired
private Marshaller marshaller;

@CitrusTest
public void sendMessageTest() {
    send(bookRequestEndpoint)
        .message()
        .body(createAddBookRequestMessage("978-citrus:randomNumber(10)"), marshaller)
        .header(SoapMessageHeaders.SOAP_ACTION, "addBook");
}

private AddBookRequestMessage createAddBookRequestMessage(String isbn) {
    AddBookRequestMessage requestMessage = new AddBookRequestMessage();
    Book book = new Book();
    book.setAuthor("Foo");
    book.setTitle("FooTitle");
    book.setIsbn(isbn);
    book.setYear(2008);
    book.setRegistrationDate(Calendar.getInstance());
    requestMessage.setBook(book);
    return requestMessage;
}
----

The example above creates an *AddBookRequestMessage* object and puts this as payload to a send action. In combination with
a marshaller instance Citrus is able to create a proper XML message payload then.
