[[message-validation]]
= Message validation

When Citrus receives a message from external applications it is time to verify the message content. This message validation
includes syntax rules with schema validation and message content comparison to expected templates. Citrus provides powerful
message validation capabilities for different data formats. The tester is able to define expected message headers and body
content. The Citrus message validator finds values not matching the expectations and reports the difference as test failure.

[[message-validator-registry]]
== Validation registry

Citrus provides default message validator implementations for different data formats. The Citrus project context
automatically loads these default message validators. In case one of these message validators matches the incoming
message the message validator performs its validation steps with the message.

All default message validators can be overwritten by binding a component with the same id to the project context (e.g. as
Spring bean in the application context).

The default message validator implementations of Citrus are:

[horizontal]
defaultXmlMessageValidator:: com.consol.citrus.validation.xml.DomXmlMessageValidator
defaultXpathMessageValidator:: com.consol.citrus.validation.xml.XpathMessageValidator
defaultJsonMessageValidator:: com.consol.citrus.validation.json.JsonTextMessageValidator
defaultJsonPathMessageValidator:: com.consol.citrus.validation.json.JsonPathMessageValidator
defaultPlaintextMessageValidator:: com.consol.citrus.validation.text.PlainTextMessageValidator
defaultMessageHeaderValidator:: com.consol.citrus.validation.DefaultMessageHeaderValidator
defaultBinaryBase64MessageValidator:: com.consol.citrus.validation.text.BinaryBase64MessageValidator
defaultGzipBinaryBase64MessageValidator:: com.consol.citrus.validation.text.GzipBinaryBase64MessageValidator
defaultXhtmlMessageValidator:: com.consol.citrus.validation.xhtml.XhtmlMessageValidator
defaultGroovyXmlMessageValidator:: com.consol.citrus.validation.script.GroovyXmlMessageValidator
defaultGroovyTextMessageValidator:: com.consol.citrus.validation.script.GroovyScriptMessageValidator
defaultGroovyJsonMessageValidator:: com.consol.citrus.validation.script.GroovyJsonMessageValidator

TIP: You can overwrite a default message validator with a custom implementation. Just add your customized validator implementation
as a bean to the Citrus context and use one of the default bean identifiers.

You can add a custom message validator as a component in the context (e.g. as Spring bean in the application context).

.Java DSL
[source,java,indent=0,role="primary"]
----
@Bean
public CustomMessageValidator customMessageValidator() {
    return new CustomMessageValidator();
}
----

.XML DSL
[source,xml,indent=0,role="secondary"]
----
<bean id="customMessageValidator" class="com.consol.citrus.validation.custom.CustomMessageValidator"/>
----

The listing above adds a custom message validator implementation. The message validator registry will automatically add this
validator to the list of available validators in the project.

The custom implementation class has to implement the basic interface *com.consol.citrus.validation.MessageValidator<>*. Now
Citrus will try to match the custom implementation to incoming message types and occasionally execute the message validator
logic when applicable.

[[message-validator-modules]]
== Validation modules

The list of available message validators in your project is controlled by the available message validator implementations
on the project classpath.

You need to add validator modules to the project accordingly. For instance if you want to use the default Json message validation
capabilities in Citrus you need to add the following dependency:

.Json validation module dependency
[source,xml]
----
<dependency>
  <groupId>com.consol.citrus</groupId>
  <artifactId>citrus-validation-json</artifactId>
  <version>${citrus.version}</version>
</dependency>
----

This adds the Citrus message validator component for dealing with Json message format. This includes message validators and
JsonPath support. Now your Citrus project is able to validate Json messages.

Citrus provides the following validation modules:

* link:#json-message-validation[citrus-validation-json]
* link:#xml-message-validation[citrus-validation-xml]
* link:#plaintext-message-validation[citrus-validation-text]
* link:#binary-message-validation[citrus-validation-binary]
* link:#groovy-xml-validation[citrus-validation-groovy]
* link:#hamcrest-message-validation[citrus-validation-hamcrest]

Read more about the individual validation modules in the next sections.

include::validation-json.adoc[]
include::validation-xml.adoc[]
include::validation-schema.adoc[]
include::validation-plaintext.adoc[]
include::validation-binary.adoc[]
include::validation-hamcrest.adoc[]
include::validation-custom.adoc[]
