<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://citrusframework.org/SampleService/"
                  xmlns:types="http://citrusframework.org/types/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  name="SampleService"
                  targetNamespace="http://citrusframework.org/SampleService/">

  <wsdl:import namespace="http://citrusframework.org/TestService/" location="TestService.wsdl"/>

  <wsdl:message name="sampleMessage">
    <wsdl:part element="tns:sampleMessage" name="parameters"/>
  </wsdl:message>

  <wsdl:portType name="SampleService">
    <wsdl:operation name="sampleMessage">
      <wsdl:input message="tns:sampleMessage"/>
      <wsdl:output message="tns:sampleMessageResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="SampleServiceSOAP" type="tns:SampleService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sampleMessage">
      <soap:operation soapAction="http://citrusframework.org/sample/sampleMessage"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="SampleService">
    <wsdl:port binding="tns:SampleServiceSOAP" name="SampleServiceSOAP">
      <soap:address location="http://citrusframework.org/SampleService/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
