<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:tns="http://citrusframework.org/TestService/"
                  xmlns:types="http://citrusframework.org/test/types/"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                  name="TestService"
                  targetNamespace="http://citrusframework.org/TestService/">
  <wsdl:types>
    <xsd:schema xmlns="http://citrusframework.org/TestService/" targetNamespace="http://citrusframework.org/TestService/">
      <xsd:element name="sampleMessage" type="types:TestType"/>
    </xsd:schema>

    <xsd:schema targetNamespace="http://citrusframework.org/test/types/">
      <xsd:complexType name="TestType">
        <xsd:simpleContent>
          <xsd:restriction base="xsd:string">
            <xsd:enumeration value="FOO"/>
            <xsd:enumeration value="BAR"/>
          </xsd:restriction>
        </xsd:simpleContent>
      </xsd:complexType>
    </xsd:schema>
  </wsdl:types>

  <wsdl:message name="sampleMessage">
    <wsdl:part element="tns:sampleMessage" name="parameters"/>
  </wsdl:message>

  <wsdl:portType name="TestService">
    <wsdl:operation name="sampleMessage">
      <wsdl:input message="tns:sampleMessage"/>
      <wsdl:output message="tns:sampleMessageResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="TestServiceSOAP" type="tns:TestService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sampleMessage">
      <soap:operation soapAction="http://citrusframework.org/sample/sampleMessage"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="TestService">
    <wsdl:port binding="tns:TestServiceSOAP" name="TestServiceSOAP">
      <soap:address location="http://citrusframework.org/TestService/"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
