<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="HelloService"
                  xmlns:tns="http://citrusframework.org/schemas/samples/HelloService"
                  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  targetNamespace="http://citrusframework.org/schemas/samples/HelloService"
                  xmlns="http://www.w3.org/2001/XMLSchema">

  <wsdl:documentation>Version 1.0</wsdl:documentation>

  <wsdl:types>
    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
               xmlns="http://citrusframework.org/schemas/samples/HelloService"
               targetNamespace="http://citrusframework.org/schemas/samples/HelloService"
               elementFormDefault="qualified"
               attributeFormDefault="unqualified">

      <xs:element name="HelloRequest">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Message" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

      <xs:element name="HelloResponse">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="Message" type="xs:string"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>

    </xs:schema>
  </wsdl:types>

  <wsdl:message name="HelloRequest">
    <wsdl:part name="parameters" element="tns:HelloRequest"/>
  </wsdl:message>

  <wsdl:message name="HelloResponse">
    <wsdl:part name="parameters" element="tns:HelloResponse"/>
  </wsdl:message>

  <wsdl:portType name="HelloService">
    <wsdl:operation name="sayHello">
      <wsdl:input name="HelloRequest" message="tns:HelloRequest"/>
      <wsdl:output name="HelloResponse" message="tns:HelloResponse"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:service name="HelloService">
    <wsdl:port name="HelloServiceHTTP"
               binding="tns:HelloServiceHTTPBinding">
      <soap:address location="http://localhost:18080/hello"/>
    </wsdl:port>
  </wsdl:service>

  <wsdl:binding name="HelloServiceHTTPBinding"
                type="tns:HelloService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="sayHello">
      <soap:operation style="document"
                      soapAction="/HelloService/sayHello"/>
      <wsdl:input name="HelloRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="HelloResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

</wsdl:definitions>