# A Gemfile to build the Citrus Jekyll documentation
source "https://rubygems.org"

gem "jekyll", "~> 3.4"
gem "jekyll-feed", "~> 0.9.2"
gem "jemoji", "~> 0.8.0"
gem "jekyll-sitemap", "~> 1.1"
gem "jekyll-mentions", "~> 1.2"
gem "jekyll-redirect-from", "~> 0.12.1"
